### ISSUE TITLE
remnux upgrade is failing at  ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)

### ISSUE THREAD

**Issue by haricsree** [REMnux/remnux-cli#10]
1. Ran multiple times and failing with same error.

>> Running: default-jdk
>> Running: /usr/local/src/remnux/files/ghidra_9.1.2_PUBLIC_20200212.zip
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

2. Rebooted and tried but still the same error.

remnux@remnux:~$ grep ERROR /var/cache/remnux/cli/v2020.38.3/saltstack.log 

# [ERROR   ] Command '['systemd-run', '--scope', '--description', '"salt.loaded.int.module.aptpkg"', 'apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'upgrade']' failed with return code: -11
# [ERROR   ] stdout: Reading package lists...
# [ERROR   ] stderr: Running scope as unit: run-r2fcb924253ad4ce38026107d4b9b49e8.scope
# [ERROR   ] retcode: -11
# [ERROR   ] Made the following changes:
# [ERROR   ] Command '['/usr/bin/python3', '-m', 'pip', 'install', '--disable-pip-version-check', '--upgrade', 'git+https://github.com/doomedraven/VirusTotalApi']' failed with return code: 1
# [ERROR   ] stdout: Collecting git+https://github.com/doomedraven/VirusTotalApi
# [ERROR   ] stderr: The directory '/home/remnux/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
# [ERROR   ] retcode: 1
# [ERROR   ] Failed to install packages: git+https://github.com/doomedraven/VirusTotalApi. Error: Collecting git+https://github.com/doomedraven/VirusTotalApi
# [ERROR   ] Command '['/usr/bin/python', '-m', 'pip', 'install', '--disable-pip-version-check', 'git+https://github.com/volatilityfoundation/volatility.git@2.6.1']' failed with return code: 1
# [ERROR   ] stdout: Collecting git+https://github.com/volatilityfoundation/volatility.git@2.6.1
# [ERROR   ] stderr: /usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
# [ERROR   ] retcode: 1
# [ERROR   ] Failed to install packages: git+https://github.com/volatilityfoundation/volatility.git@2.6.1. Error: Collecting git+https://github.com/volatilityfoundation/volatility.git@2.6.1
Binary file /var/cache/remnux/cli/v2020.38.3/saltstack.log matches

[saltstack.log](https://github.com/REMnux/remnux-cli/files/5262013/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi there @haricsree , it looks like, according to the error messages, that the failure causing the issue is that there was a lock on dpkg, possibly from another process. I would recommend just trying a `sudo apt update && sudo apt upgrade -y` to see if you can successfully complete an upgrade without that error code, then try again. 

This can happen frequently when Ubuntu does an unattended-upgrade or software updates in the background.

**Comment by haricsree** [comment]
1. Ran `sudo apt update && sudo apt upgrade -y` before upgrading.

Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

2. Failed again.
```
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```
[saltstack.log](https://github.com/REMnux/remnux-cli/files/5267508/saltstack.log)

**Comment by mbower** [comment]
Im seeing a similar thing, pulled this from the saltstack.log:

`# [DEBUG   ] Error loading module.boto3_elasticsearch: __init__ failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1754, in _load_module
    module_init(self.opts)
  File "/usr/lib/python3/dist-packages/salt/modules/boto3_elasticsearch.py", line 96, in __init__
    __utils__["boto3.assign_funcs"](__name__, "es")
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1278, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'boto3.assign_funcs'`

**Comment by lennyzeltser** [comment]
@mbower, could you share your saltstack.log file, please, so I can take a look?

**Comment by mbower** [comment]
Sure thing, attached. I did rerun it and whatever it was v2020.39.2 fixed it for me.

[saltstack.log](https://github.com/REMnux/remnux-cli/files/5268374/saltstack.log)

**Comment by lennyzeltser** [comment]
@mbower and @haricsree, I noticed 2 issues, which I've now corrected: One of the files for the speakeasy tool was recently updated, as was the NetworkMiner's file, so I needed to update the expected hash values. Please try the installation/upgrade again. In my tests, it has completed cleanly.

@haricsree, looking at your saltstack.log file, I saw the speakeasy error, which I can explain and have now corrected. However, I've seen other errors that suggest connectivity issues, which interfered with the proper download of some files.

**Comment by haricsree** [comment]
Thanks for looking at it.

Failed again at same place.

>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Please see the attached log.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/5269144/saltstack.log)

**Comment by lennyzeltser** [comment]
@haricsree, as far as I can tell, the issues are due to connectivity errors. I see messages like these:

```
HTTP Error 503: Service Unavailable
Error reading https://launchpad.net/api/1.0/~sift/ppas: Service Unavailable
Error: Collecting git+https://github.com/doomedraven/VirusTotalApi
Error: Collecting git+https://github.com/volatilityfoundation/volatility.git@2.6.1
```

I don't encounter these issues on my side, and looks like the installation just completed successfully for @mbower. The best I can recommend is trying connecting to the Internet via a different link. Also, sometimes local security tools interfere with downloads they consider suspicious.

I'll keep this issue open for a bit in case other people report problems that form a patter that would lead me to a different theory.

**Comment by digitalsleuth** [comment]
@hariscree Are you perhaps behind a proxy or firewall which may block access to GitHub or other resources?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by haricsree** [comment]
Thanks for your inputs.

Tried upgrading without VPN,with VPN, I am not behind proxy or firewall still failing. 

Please see this latest log. If you still think that it is due to network connectivity issues then I will try someother time. Thanks again for looking into this.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/5273985/saltstack.log)

Also, observed had CPU  lockup during upgrade. Please see this screenshot. 
![VirtualBox_REMnux v7_24_09_2020_00_16_04](https://user-images.githubusercontent.com/34885536/94110829-21b11380-fe3b-11ea-9ee2-8453a605ecda.png)

**Comment by digitalsleuth** [comment]
From this log, it seems like you have some issues with python as a whole, and not just for the installer. Could you provide the following information by running the following commands?
`which python`
`which python3`
`pip -V`
`pip3 -V`
`python -V`
`python3 -V`
`uname -a`
`lsb_release -a`

Thanks!

**Comment by haricsree** [comment]
I imported this ova from official Remnux website.

Thu Sep 24 13:11:01 remnux@remnux /tmp $which python
/usr/bin/python

Thu Sep 24 13:11:05 remnux@remnux /tmp $which python3
/usr/bin/python3

Thu Sep 24 13:11:10 remnux@remnux /tmp $pip -V
/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography import x509
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

Thu Sep 24 13:11:16 remnux@remnux /tmp $pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

Thu Sep 24 13:11:23 remnux@remnux /tmp $python -V
Python 2.7.17

Thu Sep 24 13:11:32 remnux@remnux /tmp $python3 -V
Python 3.6.9

Thu Sep 24 13:11:34 remnux@remnux /tmp $uname -a
Linux remnux 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Thu Sep 24 13:11:39 remnux@remnux /tmp $lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by haricsree** [comment]
On a sidenote, I saw this error when I ran the remnux upgrade again. Will this help to narrow down the packages issue I might be having?

virtualenv_|-remnux-python-packages-malwoverview-virtualenv_|-/opt/malwoverview_|-managed:
    __id__: remnux-python-packages-malwoverview-virtualenv
    __run_num__: 346
    __sls__: remnux.python-packages.malwoverview
    changes: {}
    comment: "An exception occurred in this state: Traceback (most recent call last):\n
      \ File \"/usr/lib/python3/dist-packages/salt/state.py\", line 2154, in call\n
      \   *cdata[\"args\"], **cdata[\"kwargs\"]\n  File \"/usr/lib/python3/dist-packages/salt/loader.py\",
      line 2087, in wrapper\n    return f(*args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/salt/states/virtualenv_mod.py\",
      line 298, in managed\n    before = set(__salt__[\"pip.freeze\"](bin_env=name,
      user=user, use_vt=use_vt))\n  File \"/usr/lib/python3/dist-packages/salt/modules/pip.py\",
      line 1209, in freeze\n    cur_version = version(bin_env, cwd)\n  File \"/usr/lib/python3/dist-packages/salt/modules/pip.py\",
      line 1336, in version\n    raise CommandNotFoundError(\"Could not find a `pip`
      binary\")\nsalt.exceptions.CommandNotFoundError: Could not find a `pip` binary\n"
    duration: 151.243
    name: /opt/malwoverview
    result: false
    start_time: '11:27:34.494212'
  virtualenv_|-remnux-python-packages-vipermonkey-virtualenv_|-/opt/vipermonkey_|-managed:
    __id__: remnux-python-packages-vipermonkey-virtualenv
    __run_num__: 283
    __sls__: remnux.python-packages.vipermonkey
    changes: {}
    comment: virtualenv exists
    duration: 3271.215
    name: /opt/vipermonkey
    result: true
    start_time: '11:25:52.766170'

[new_saltstack.log](https://github.com/REMnux/remnux-cli/files/5276314/new_saltstack.log)

**Comment by digitalsleuth** [comment]
I suspect, after a little bit of research, that the issue may be tied to the OpenSSL error you're getting. The git error which follows close after indicates that there's an issue downloading, and it may be doing the download over http (because it can't transfer properly over https). I found [this link](http://vlabs.iitb.ac.in/gitlab/help/topics/git/troubleshooting_git.md#increase-the-post-buffer-size-in-git) which indicates a similar error.

I'm testing this theory/configuration now and will let you know the outcome.

**Comment by digitalsleuth** [comment]
@haricsree I just downloaded the OVA, only ran 'sudo remnux upgrade' and it installed without issue. Can you tell me if you've made any customizations to the VM after starting it up? 

This is definitely strange, but from what I can tell it seems to be unique to your installation, and not to the VM or the CLI. Any information you can provide about additional software you might have installed besides attempting to run the CLI would be helpful.

**Comment by haricsree** [comment]
@digitalsleuth, 
1. I did not make any customizations apart from installing virtualbox guest additions and installed Chrome I am currently running Virtualbox 6.1.14 r140239 (Qt5.6.2) version.
2. This morning, I removed the previous VM and import the .ova file again and tried. Failed at same place. Please see the attached log.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/5282142/saltstack.log)
3. Last option is, ask someone to upload a upgraded ova.

**Comment by digitalsleuth** [comment]
There is one last thing I'd like to try. Can you re-import the OVA again and this time don't install the guest additions or Chrome? I'm going to do the same thing you did using Virtualbox and VMware to see if I can duplicate and figure out the issue.

**Comment by haricsree** [comment]
Removed the exising VM and re-imported the ova. After import, when I just ran `sudo remnux upgrade`. It failed again. It looks like there is some issue with python.

**Comment by haricsree** [comment]
sorry closed it by mistake.

Removed the exising VM and re-imported the ova. After import, when I just ran `sudo remnux upgrade`. It failed again. It looks like there is some issue with python. 

```
# [DEBUG   ] stderr: /usr/local/lib/python2.7/dist-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
# [INFO    ] {'olefile==0.46': 'Installed'}
# [DEBUG   ] Refreshing modules...
# [INFO    ] Loading fresh modules for state activity
# [DEBUG   ] LazyLoaded jinja.render
# [DEBUG   ] LazyLoaded yaml.render
# [INFO    ] Completed state [olefile] at time 08:49:43.892764 (duration_in_ms=9038.069)
# [DEBUG   ] LazyLoaded config.option
corrupted double-linked list
```


[saltstack.log](https://github.com/REMnux/remnux-cli/files/5282961/saltstack.log)

**Comment by digitalsleuth** [comment]
I was able to duplicate your most recent attempt using Virtualbox with no guest additions or Chrome, only just running `sudo remnux upgrade`. I believe this might be an issue with Virtualbox itself. In the process of creating the VM from the OVA, I had three failed attempts to successfully boot and run the CLI, with issues ranging from segfaults and interface failures.

This issue does not appear to occur with VMware though. I'm going to pick at this a bit more today to see what else I can determine. I'll only be using the latest Virtualbox to test, to re-create your environment, but if you have VMware you should be able to successfully load the OVA to continue.

**Comment by lennyzeltser** [comment]
@haricsree, I was able to reproduce a general networking problem when running Ubuntu 18.05 using the latest VirtualBox on Windows 10. For some reason, some of the files downloaded into the VM become corrupted. The same VM running on the same version of VirtualBox on macOS seems to behave properly.

I may have found a way to solve the issue. Could you please try the following:

Shut down your REMnux VM, then open VirtualBox settings for the VM and go to Network. There, click Advanced and under Adapter Type select `Paravirtualized Network (virtio-net)`. Click OK and start up the REMnux VM.

After you do this, please try the `remnux upgrade` operation again.

**Comment by haricsree** [comment]
1. Thanks @lennyzeltser. Sorry I forgot to mention the host OS details(Win10 + Virtualbox) initially which would have it a bit easier.

2. I changed the Adapter type to Paravirtualized Network (virtio-net) and booted the VM. I ran `remnux upgrade` and it failed again at the same place.

>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:551:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

[saltstack.log](https://github.com/REMnux/remnux-cli/files/5289123/saltstack.log)

3. What is the next thing that runs after  `>> Running: ssh` ? Because it always fails here. I suspect either ssh process did not exit properly.

**Comment by haricsree** [comment]
1. Thanks @lennyzeltser. Sorry I forgot to mention the host OS details(Win10 + Virtualbox) initially which would have it a bit easier.

2. I changed the Adapter type to Paravirtualized Network (virtio-net) and booted the VM. I ran `remnux upgrade` and it failed again at the same place.

>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:551:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

[saltstack.log](https://github.com/REMnux/remnux-cli/files/5289123/saltstack.log)

3. What is the next thing that runs after  `>> Running: ssh` ? Because it always fails here. I suspect the upgrading process for ssh did not exit properly. 

4. Found lots of requisite failed messages in `/var/cache/salt/minion/sls.p` file. Might be helpful with the debugging. 
[sls.p.zip](https://github.com/REMnux/remnux-cli/files/5289202/sls.p.zip)

**Comment by haricsree** [comment]
@digitalsleuth sorry I can't use VMware now since I have other VMs sitting in Virtualbox.

**Comment by lennyzeltser** [comment]
@haricsree, the `>> Running: ssh` message doesn't actually correlate to the nature of the problem. The only way to tell what went wrong is to examine the salstack.log file. And the issues there, once again, are tied to the downloaded file getting corrupted.

I built a new REMnux VM using the latest version of VirtualBox. Please give it a try:

https://ufile.io/3zg2oun9

The SHA-256 hash of the OVA file is `03f95420f73122b7b3c8a7bcc1d810c1893df571060cb822f583ee78ea38c5b6`

Once you import it into VirtualBox, please try the `remnux update` command.

Also, please try downloading some large file and confirm that it downloaded correctly. For example, try:

```
wget https://REMnux.org/remnux-cli
sha256sum remnux-cli
```

The hash of the remnux-cli file should be `36fc8d632541ee8771b33ffc4fe4732534927a5aa0cc7e3b7c2570e0cc85a388`.

If you run into issues with the integrity of the files with the new VM, please try setting its virtual network adapter type to `Paravirtualized Network (virtio-net)`, in case that solves the problem.

**Comment by haricsree** [comment]
1. Thanks @lennyzeltser for uploading that .ova.
2. Imported that .ova and ran `remnux update` Failed like before.

[withoutParaVirt_saltstack.log](https://github.com/REMnux/remnux-cli/files/5292509/withoutParaVirt_saltstack.log)

3. Next tried with `Paravirtualized Network (virtio-net)`. Failed. 
[withParaVirt_saltstack.log](https://github.com/REMnux/remnux-cli/files/5292520/withParaVirt_saltstack.log)

4. As you mentioned, I downloaded  big file(remnux-cli) and found the SHA256 is different everytime.

```
remnux@remnux:~$ wget https://REMnux.org/remnux-cli
remnux-cli            100%[========================>]  59.13M  4.55MB/s    in 13s     
2020-09-28 08:34:31 (4.70 MB/s) - âremnux-cliâ saved [62004186/62004186]

remnux@remnux:~$ sha256sum remnux-cli 
1df6e26a60867b249510d019e92f50811a9d74988c45282f0efbc69e331fdb40  remnux-cli
```

```
remnux@remnux:~$ wget https://REMnux.org/remnux-cli
remnux-cli.1          100%[========================>]  59.13M  4.93MB/s    in 12s     
2020-09-28 08:34:55 (4.97 MB/s) - âremnux-cli.1â saved [62004186/62004186]

remnux@remnux:~$ sha256sum remnux-cli.1
00ef8c5dcb43b6661a45cba45e7238f3db6b48ebe31e7daad00a65c8a063ef33  remnux-cli.1

```
```
remnux@remnux:~$ wget https://REMnux.org/remnux-cli
remnux-cli.2          100%[========================>]  59.13M  8.38MB/s    in 7.8s    
2020-09-28 08:35:11 (7.60 MB/s) - âremnux-cli.2â saved [62004186/62004186]

remnux@remnux:~$ sha256sum remnux-cli.2
36fc8d632541ee8771b33ffc4fe4732534927a5aa0cc7e3b7c2570e0cc85a388  remnux-cli.2
```

```
remnux@remnux:~$ ls -tlr
total 187444
-rw-r--r-- 1 remnux remnux 62004186 Sep 15 10:37 remnux-cli.2
-rw-r--r-- 1 remnux remnux 62004186 Sep 15 10:37 remnux-cli.1
-rw-r--r-- 1 remnux remnux 62004186 Sep 15 10:37 remnux-cli
drwxr-xr-x 2 remnux remnux     4096 Sep 27 15:21 Videos
drwxr-xr-x 2 remnux remnux     4096 Sep 27 15:21 Templates
drwxr-xr-x 2 remnux remnux     4096 Sep 27 15:21 Public
drwxr-xr-x 2 remnux remnux     4096 Sep 27 15:21 Pictures
drwxr-xr-x 2 remnux remnux     4096 Sep 27 15:21 Music
drwxr-xr-x 2 remnux remnux     4096 Sep 27 15:21 Downloads
drwxr-xr-x 2 remnux remnux     4096 Sep 27 15:21 Documents
drwxr-xr-x 2 remnux remnux     4096 Sep 27 15:21 Desktop
-rw-r--r-- 1 remnux remnux  2941303 Sep 28 08:17 saltstack.log_withoutParaVirt
-rw-r--r-- 1 remnux remnux  2944994 Sep 28 08:33 saltstack.log_withParaVirt
```

Its interesting the filesizes are same but the different filehashes which confirms the downloaded files are being corrupted.

**Comment by lennyzeltser** [comment]
Thanks for checking, @haricsree.

Something really appears broken with the networking capabilities of Ubuntu running in the latest version of VirtualBox on Windows. Even without REMnux, the base Ubuntu 18.04 minimal VM is unable to download the remnux-cli file without integrity issues on Windows. Though in my testing, switching to the virtio-net adapter addressed that issue

In your case, I am wondering whether selecting another adapter option for the VM might get around the problem? For example, could you try the "AMD PCNet FAST III (Am79C973)" adapter and see whether that allows you to download remnux-cli properly?

Also, I'm assuming that Hyper-V is disabled on your system, but thought I'd check just in case. Hyper-V seems to be causing some issues for VirtualBox users.

**Comment by haricsree** [comment]
@lennyzeltser Thanks for all your help.

1. I tried NAT + All the adapters in the dropdown. But none worked. 
2. Installed VirtualboxGuest additions. Tried NAT+Intel PRO/1000MT Desktop and NAT+virtio-net. Unable to download remnux-cli without integrity issues. 
3. I will try Bridged mode tomorrow and let you know.
4. Last thing is, please provide me the .ova with eveything updated.

Yes, Hyper-V was disabled all the time.

**Comment by lennyzeltser** [comment]
@haricsree, the OVA you downloaded yesterday is fresh and includes all the updates. You're welcome to continue using it.

**Comment by lennyzeltser** [comment]
I figured it out! (I think.)

The issue appears to be the interference VirtualBox is receiving from Hyper-V. Even though Hyper-V appears disabled in the Windows Features listing, VirtualBox appears to use it anyway.

As I discovered [here](https://forums.virtualbox.org/viewtopic.php?f=25&t=99390), to disable Hyper-V reliably, please use the Administrator Command Prompt to run:

```
bcdedit /set hypervisorlaunchtype off
shutdown -s -t 2
```
Then start-up your system and try downloading a large file from the VM; in my case, these steps allowed me to download the file properly. If this works, please try the `remnux upgrade` command.

**Comment by haricsree** [comment]
yay!! It worked. After turning Off Hyper-V with those commands you gave `remnux upgrade` just went smooth. 

_Thank you_ **Thank you** and a big **THANK YOU** for all your help to get this fixed.

```
>> Running: remnux-dedicated

>> COMPLETED SUCCESSFULLY! Success: 692, Failure: 0

```
