### ISSUE TITLE
CLI Install Fail on Ubuntu ARM VM in Parallels (macOS - M1): ELF Not Found

### ISSUE THREAD

**Issue by dervinfro** [REMnux/remnux-cli#100]
The CLI install is failing.  As per the install instructions on the remnux site (https://docs.remnux.org/install-distro/install-from-scratch), I'm getting an ELF Not Found.  This Ubuntu ARM VM is on Parallels (the ARM is required for the macOS M1).

Not sure if this is failing due to compatibility with Ubuntu ARM or for some other reason.  Input in greatly appreciated.

**Comment by lennyzeltser** [comment]
Sorry, REMnx is not compatible with ARM and won't work on M1 or M2 processors.

**Comment by dervinfro** [comment]
Kind of what I thought.  Appreciate the quick response.  Cheers.
