### ISSUE TITLE
Installer fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by kmilach** [REMnux/remnux-cli#101]
Hello, everyone.

The REMnux installer keeps failing when installing (Ubuntu 20.04 machine):
>>remnux-cli@1.3.4.2.g87c65ef
>> remnux-version: notinstalled
>>
>> mode: addon
>> downloading v2022.39.2
>> downloading remnux-salt-states-v2022.39.2.tar.gz.asc
>> downloading remnux-salt-states-v2022.39.2.tar.gz.sha256
>> downloading remnux-salt-states-v2022.39.2.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2022.39.2.tar.gz
> validating file remnux-salt-states-v2022.39.2.tar.gz
> validating signature for remnux-salt-states-v2022.39.2.tar.gz.sha256
> extracting update remnux-salt-states-v2022.39.2.tar.gz
> upgrading/updating to v2022.39.2
>> Log file: /var/cache/remnux/cli/v2022.39.2/saltstack.log
>>
>>Update returned exit code not zero
>>Error: Update returned exit code not zero
>>      at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
>>      at ChildProcess.emit (events.js:315:20)
>>      at maybeClose (internal/child_process.js:1021:16)
>>      at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

[saltstack.log](https://github.com/REMnux/remnux-cli/files/9906403/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @kmilach , this is an error with SaltStack caused by an upgrade in it's requirements. To remedy this, run the following, then try the installer again: 
`sudo python3 -m pip install importlib_metadata<=5.0.0`

**Comment by kmilach** [comment]
Hey @digitalsleuth, thanks for looking into this.

From what I gathered, the package is already at the required version:
![image](https://user-images.githubusercontent.com/53876300/199250129-eadba770-4c25-41d3-a6fe-3374a9e2a4ed.png)

**Comment by digitalsleuth** [comment]
Sorry, I didn't mean to include the `=`. Remove that from the command and try again.
`sudo python3 -m pip install importlib_metadata<5.0.0`

**Comment by kmilach** [comment]
Thank you! The installation proceed until another error was found, related to mismatched hashes of the 'SSView.zip' file.

>>__sls__: remnux.tools.ssview
    changes: {}
    comment: Specified sha256 checksum for /usr/local/src/remnux/files/SSView.zip
      (8ceb003a88ed985b772accb81551577ce363f268fe14ef23ec47f912b1abe111) does not
      match actual checksum (4b9ffce3bfb53013b860cbf2af97b847cb3f259d5bb8633106caa94ac006a483)
    duration: 12630.331
    name: /usr/local/src/remnux/files/SSView.zip
    result: false

[saltstack2.log](https://github.com/REMnux/remnux-cli/files/9912066/saltstack.log)

For now, I believe a quick solution would be just manually editing the expected hash value, yes?

**Comment by digitalsleuth** [comment]
To get everything set up, you can now manually install SSView. I've just submitted a PR to update the hash, so it'll be fixed for the next release.

**Comment by lennyzeltser** [comment]
I issued a new release to include the SSView update.

**Comment by Cloud-Hacking** [comment]
Having same issue. The last release I see is from April 2. Am I missing something?

**Comment by lennyzeltser** [comment]
@Cloud-Hacking, looks like the hash for the SSView zip file has changed again. I just issued a new release to reflect it, so please give `remnux upgrade` another try.

**Comment by Cybertest06** [comment]
still it is not working getting the same above error

**Comment by lennyzeltser** [comment]
@Anithaguni, I just confirmed that SSView is installing correctly, at least in my tests. Perhaps there's a different issue? Please upload your saltstack.log file after you run `remnux upgrade`, so I can take a look.

**Comment by Cybertest06** [comment]
I am trying to install the remnux first time and I am getting the above error. Attached the logs for your reference.[
[saltstack.log](https://github.com/REMnux/remnux-cli/files/9944359/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @Anithaguni , your error is caused by a recent update to the importlib_metadata python module. Try running the following command and then try to install again:

`sudo python3 -m pip install importlib_metadata<5.0.0`

**Comment by Cybertest06** [comment]
Tried the above mentioned command still I am facing same error.

**Comment by digitalsleuth** [comment]
Hi @Anithaguni , while typically you might see the same thing during output, it's not always the same cause behind the scenes. If you ran the previous command for downgrading importlib_metadata and it was successful, then you may be experiencing a new error.

Please attach your new saltstack.log file, and please also provide the output of the command I mentioned earlier.

Cheers.

**Comment by Cybertest06** [comment]
Hi @digitalsleuth I ran the command sudo python3 -m pip install importlib_metadata==4.13.0 and it downgraded the version. Later, I tried to install Remnux; initially, it ran many files but ended up with the same error. Then I tried rebooting the machine and tried to install one more time, and the installation completed successfully.

**Comment by kmilach** [comment]
Hello everyone!

I managed to successfully install de v2022.44.2 into the Ubuntu machine and upgraded it to v2022.44.5, all after the new release and downgrading the importlib_metadata package to version 4.13.0.

Thanks everyone!
