### ISSUE TITLE
remnux cannot install it in ubuntu 22.04

### ISSUE THREAD

**Issue by ghost** [REMnux/remnux-cli#102]

**Comment by lennyzeltser** [comment]
That's right. Only Ubuntu 20.04 is supported at this time.

**Comment by ghost** [comment]
> That's right. Only Ubuntu 20.04 is supported at this time.

do u mean 20.4.5??

**Comment by lennyzeltser** [comment]
Any variant of Ubuntu 20.04, also known as Focal, should work.
