### ISSUE TITLE
remnux update is failing at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)

### ISSUE THREAD

**Issue by jtpoplin** [REMnux/remnux-cli#106]
Received this error after multiple update and upgrade attempts.

>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

I have reinstalled and rebooted the VM multiple times and have ran sudo apt update && sudo apt upgrade -y before the attempts.

I downloaded the ova file from the remnux.org and the sha256 matched.
I'm running VMWare Workstation 16.2.4 build-20089737

Any help would be appreciated, thanks!

[saltstack.log](https://github.com/REMnux/remnux-cli/files/10182724/saltstack.log)

**Comment by jtpoplin** [comment]
Forgot to mention host OS:
Ubuntu 22.04.1 LTS
Release: 22.04

**Comment by lennyzeltser** [comment]
Looks like there was a connection timeout while downloading PolarProxy from the tool's website. This happens sometimes. There was also a problem with SSview--the hash of the downloaded file didn't match the expected value; perhaps an internet issue? There was also an issue with Unfurl that was addressed yesterday.

Everything else installed fine. I recommend using the REMnux system in its current state and then run `remnux upgrade` in a couple of days.

**Comment by jtpoplin** [comment]
Thank you for your prompt reply.  I have not noticed any connectivity issues, but will follow your advice in trying again after a few days with the remnux upgrade command.  Thanks again

**Comment by sibu7** [comment]
This still seems to be an issue. Here is an excerpt from my saltstack.log:

>    test_|-remnux-tools_|-remnux-tools_|-nop:
>     __run_num__: 751
>     __sls__: remnux.tools
>     changes: {}
>     comment: 'One or more requisite failed: remnux.tools.networkminer.remnux-networkminer-source,
>       remnux.tools.polarproxy.remnux-polarproxy-source, remnux.tools.polarproxy.remnux-polarproxy-archive,
>       remnux.tools.polarproxy./usr/local/polarproxy/PolarProxy, remnux.tools.ssview.remnux-tools-ssview-wrapper,
>       remnux.tools.polarproxy.remnux-polarproxy-wrapper, remnux.tools.ssview.remnux-tools-ssview-archive,
>       remnux.tools.networkminer.remnux-networkminer-wrapper, remnux.tools.networkminer.remnux-networkminer-cleanup,
>       remnux.tools.ssview.remnux-tools-ssview-source, remnux.tools.networkminer.remnux-networkminer-archive,
>       remnux.tools.networkminer./usr/local/NetworkMiner_2-7-3/NetworkMiner.exe'
>     duration: 0.008
>     result: false
>     start_time: '09:33:57.011504'

Is there any way I can skip PolarProxy, so that the update can continue?

**Comment by lennyzeltser** [comment]
@sibu7, the failure of one tool doesn't affect the other tools unless the other tools depend on it. So you can just ignore the PolarProxy error--the others will install and update regardless of this issue.
