### ISSUE TITLE
REMnux addon mode install fails on Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by MikhailOnChain** [REMnux/remnux-cli#108]
I've spent hours trying to install the REMnux addon on an Ubuntu EC2 with SIFT installed and I keep getting this error.

`> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: notinstalled

> mode: addon
> downloading v2022.49.1
>> downloading remnux-salt-states-v2022.49.1.tar.gz.asc
>> downloading remnux-salt-states-v2022.49.1.tar.gz.sha256
>> downloading remnux-salt-states-v2022.49.1.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2022.49.1.tar.gz
> validating file remnux-salt-states-v2022.49.1.tar.gz
> validating signature for remnux-salt-states-v2022.49.1.tar.gz.sha256
> extracting update remnux-salt-states-v2022.49.1.tar.gz
> upgrading/updating to v2022.49.1
>> Log file: /var/cache/remnux/cli/v2022.49.1/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)`

SaltStack logs Attached for review, and thanks in advance.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/10221311/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @mikhail03, this issue is caused by a dependency upgrade in Saltstack. It can be easily rectified by running the following:
`sudo python3 -m pip install "importlib-metadata<5.0.0"`

Let us know how it goes!

**Comment by MikhailOnChain** [comment]
Hi @digitalsleuth, thank you for the quick response, and that solved my issues. 

I'm all set, thank you.
![Screen Shot 2022-12-13 at 3 25 05 PM](https://user-images.githubusercontent.com/17266225/207439278-bfc9492c-591c-48f9-b290-c1b315315cc9.png)
