### ISSUE TITLE
Upgrade Failing on new install

### ISSUE THREAD

**Issue by JacobPimental** [REMnux/remnux-cli#109]
Hi all,

Trying to get remnux set up on a proxmox server. Was able to import the OVA fine, but am running into issues during `remnux upgrade`. Looks like several packages are failing to upgrade and I'm not sure why. Any help is appreciated!

[saltstack.log](https://github.com/REMnux/remnux-cli/files/10252174/saltstack.log)

**Comment by lennyzeltser** [comment]
Thanks for reporting this issue, @JacobPimental. The problem was with Thug; other tools were installed fine. Thug was updated a few days ago, which changed the location of some of its configuration files.

I corrected the issue and released an update. Please run `remnux upgrade` to apply it.

**Comment by JacobPimental** [comment]
Looks like that worked! Thanks a lot for the quick response!
