### ISSUE TITLE
remnux upgrade/update is failing (Bad signature for DeXRAY.pl)

### ISSUE THREAD

**Issue by gloumps** [REMnux/remnux-cli#11]
Hello,

During upgrade/update, the script is failing after the verification of signature for DeXRAY.pl.

In sls definition [https://github.com/REMnux/salt-states/blob/master/remnux/scripts/dexray.sls] the signature for DeXRAY.pl is 9f314060960677a2c5feefe4e458a17a28694d4f38c05d3be8fe3db612829371.
But if you download this file, the signature is 5a2759d89d8351a5728ce8eceb93db7bac80b062889f2d4ed33b2690303e4249.

Regards,

Bruno

**Comment by digitalsleuth** [comment]
@gloumps Good catch, thank you for noticing. Pull request #143 (referenced above) will resolve this.
