### ISSUE TITLE
REMnux install failing on Ubuntu

### ISSUE THREAD

**Issue by armymp342** [REMnux/remnux-cli#110]
I see this same error message on other threads but the fixes are not working for me. I am trying to install remnux cli onto my SIFT workstation

Update returned exit code not zero
Error: Update returned exit code not zero
      at ChildProcess.<anonymous> (snapshot/remnux-cli/remnux-cli.js:569:23)
      at ChildProcess.emit (events.js315:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.oneexit (internal/child_process.js:286:5)

**Comment by armymp342** [comment]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/10346807/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @armymp342 , the issue is with a change to Salt's requirements. Run the following command first, then try your install again:
`sudo python3 -m pip install "importlib-metadata<5.0.0"`

**Comment by armymp342** [comment]
I ran the command and then ran the following 

`sudo remnux install --mode=addon`

received the same error

[saltstack.log](https://github.com/REMnux/remnux-cli/files/10347167/saltstack.log)

**Comment by digitalsleuth** [comment]
The error you received the second time is actually a different error. It says that SHA256 hash for NetworkMiner has changed. Other than that, everything else should work fine, and we'll update the hash and package for NetworkMiner shortly.

Cheers!

**Comment by lennyzeltser** [comment]
I just issued the release that includes the new NetworkMiner version and hash. @armymp342, you can run `remnux upgrade` to get it.

**Comment by armymp342** [comment]
It worked. I appreciate it!
