### ISSUE TITLE
Problems install remnux cli + SIFT Workstation on Ubuntu 20.04.5

### ISSUE THREAD

**Issue by JessyGothik** [REMnux/remnux-cli#111]

**Comment by JessyGothik** [comment]
I have problems with the installation of Remnux CLI on Ubuntu 20.04.5 with SIFT. The installation of SIFT CLI on ubuntu was successful, I used the command: sudo sift install mode=server. But, when I attempt to install remnux cli, I get an error with the execution of "remnux-perl-packages".

**>> Running: /usr/bin/jstillery
>> Running: remnux-node-packages
>> Running: cpan install Image::ExifTool
>> Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues**



In the log of "saltstack.log", appears the next message: 

  

> test_|-remnux-scripts_|-remnux-scripts_|-nop:
>     __id__: remnux-scripts
>     __run_num__: 582
>     __sls__: remnux.scripts
>     changes: {}
>     comment: Success!
>     duration: 1.444
>     name: remnux-scripts
>     result: true
>     start_time: '14:47:46.600171'
>   test_|-remnux-tools_|-remnux-tools_|-nop:
>     __run_num__: 761
>     __sls__: remnux.tools
>     changes: {}
>     comment: 'One or more requisite failed: remnux.tools.networkminer.remnux-networkminer-wrapper,
>       remnux.tools.networkminer.remnux-networkminer-source, remnux.tools.networkminer./usr/local/NetworkMiner_2-7-3/NetworkMiner.exe,
>       remnux.tools.networkminer.remnux-networkminer-archive, remnux.tools.networkminer.remnux-networkminer-cleanup'
>     duration: 0.021
>     result: false
>     start_time: '14:48:12.932579'
>   user_|-remnux-user-dfir_|-dfir_|-present:
>     __id__: remnux-user-dfir
>     __run_num__: 352
>     __sls__: remnux.config.user
>     changes: {}
>     comment: User dfir is present and up to date
>     duration: 5.044
>     name: dfir
>     result: true
>     start_time: '14:44:22.850288'
>   virtualenv_|-remnux-python-packages-vipermonkey-virtualenv_|-/opt/vipermonkey_|-managed:
>     __id__: remnux-python-packages-vipermonkey-virtualenv
>     __run_num__: 243
>     __sls__: remnux.python-packages.vipermonkey
>     changes: {}
>     comment: virtualenv exists
>     duration: 3830.718
>     name: /opt/vipermonkey
>     result: true
>     start_time: '14:41:46.108794'
>   virtualenv_|-remnux-python3-packages-malwoverview-virtualenv_|-/opt/malwoverview_|-managed:
>     __id__: remnux-python3-packages-malwoverview-virtualenv
>     __run_num__: 353
>     __sls__: remnux.python3-packages.malwoverview
>     changes: {}
>     comment: virtualenv exists
>     duration: 6048.396
>     name: /opt/malwoverview
>     result: true
>     start_time: '14:44:22.861439'

Can you help me, please?

**Comment by JessyGothik** [comment]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/10347422/saltstack.log)

**Comment by lennyzeltser** [comment]
@JessyGothik, I just fixed an issue that probably affected you. Could you run `remnux upgrade` to see if it worked?

**Comment by JessyGothik** [comment]
Thank you @lennyzeltser . I will try to execute the command.

**Comment by JessyGothik** [comment]
Thank you @lennyzeltser . The commands was success.

> >> Running: dbus-run-session -- dconf load /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/ < /usr/local/share/remnux/terminal-profiles.ini
> >> Running: /etc/xdg/autostart/gnome-keyring-ssh.desktop
> >> Running: /usr/share/applications/cutter.desktop
> >> Running: /usr/share/icons/binnavi.png
> >> Running: /usr/share/applications/binnavi.desktop
> >> Running: /usr/share/icons/cyberchef.png
> >> Running: /usr/share/icons/networkminer.png
> >> Running: /usr/share/applications/networkminer.desktop
> >> Running: /usr/share/applications/cyberchef.desktop
> >> Running: remnux-theme-gnome-config
> >> Running: /usr/share/icons/die.png
> >> Running: /usr/share/applications/die.desktop
> >> Running: /usr/share/remnux
> >> Running: /etc/gdm3/custom.conf
> >> Running: /etc/gdm3/custom.conf
> >> Running: /etc/sudoers.d/remnux
> >> Running: yelp
> >> Running: avahi-daemon
> >> Running: unattended-upgrades
> >> Running: /etc/apt/apt.conf.d/20auto-upgrades
> >> Running: bluetooth
> >> Running: docker
> >> Running: /usr/local/bin/docker
> >> Running: apt-get autoremove -y
> >> Running: /etc/ssh/sshd_config
> >> Running: /etc/ssh/sshd_config
> >> Running: /etc/ssh/sshd_config
> >> Running: /etc/ssh/sshd_config
> >> Running: /etc/ssh/sshd_config
> >> Running: /etc/ssh/sshd_config
> >> Running: away-from-the-dog
> >> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
> >> Running: wireshark
> >> Running: remnux-theme
> >> Running: ssh
> >> Running: remnux-dedicated
> 
> >> COMPLETED SUCCESSFULLY! Success: 826, Failure: 0
