### ISSUE TITLE
Installing Remnux as addon to SIFT failed

### ISSUE THREAD

**Issue by MartinRocak** [REMnux/remnux-cli#112]
Hello.

I was trying to set up new VM with SIFT as a main build with Remnux as addon. While installing I received an error.

Please check attached log file
[saltstack.log](https://github.com/REMnux/remnux-cli/files/10366438/saltstack.log)

Can you please help me solve this issue?

Thank you.

**Comment by digitalsleuth** [comment]
Hi @MartinRocak , it looks like you had a temporary issue with apt during the repo setup portion, most likely a connectivity issue. Can you try running the following and post the output:

`sudo apt-get update`

**Comment by MartinRocak** [comment]
Output of sudo apt-get update

$ sudo apt-get update
Hit:1 http://deb.nodesource.com/node_14.x focal InRelease
Hit:2 https://download.docker.com/linux/ubuntu focal InRelease                                                                        
Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease                                                                      
Hit:4 http://ppa.launchpad.net/gift/stable/ubuntu focal InRelease                                                                     
Hit:5 http://www.inetsim.org/debian binary/ InRelease                                                                                 
Hit:6 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3003 focal InRelease                                                         
Hit:7 https://download.mono-project.com/repo/ubuntu stable-focal InRelease                                                            
Hit:8 http://packages.microsoft.com/repos/code stable InRelease                                                                       
Get:9 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004 focal InRelease [2,125 B]                                               
Hit:10 http://packages.microsoft.com/repos/vscode stable InRelease                                                                    
Hit:11 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu focal InRelease                                                                  
Hit:12 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease                                                               
Hit:13 http://ppa.launchpad.net/remnux/stable/ubuntu focal InRelease                                                       
Hit:14 http://archive.ubuntu.com/ubuntu focal InRelease             
Hit:15 http://ppa.launchpad.net/sift/stable/ubuntu focal InRelease             
Hit:16 http://download.draios.com/stable/deb stable-amd64/ InRelease
Hit:17 http://archive.ubuntu.com/ubuntu focal-updates InRelease                
Hit:18 http://ppa.launchpad.net/wireshark-dev/stable/ubuntu focal InRelease    
Hit:19 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:20 http://archive.ubuntu.com/ubuntu focal-security InRelease
Err:9 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004 focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E08A149DE57BFBE
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3003 focal InRelease' doesn't support architecture 'i386'
W: GPG error: https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004 focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E08A149DE57BFBE
E: The repository 'https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004 focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by digitalsleuth** [comment]
Well it looks like there is a configuration issue with your current repos, especially the salt ones. Can you remove the file `saltstack.list` and / or `salt.list` from `/etc/apt/sources.list.d/` , then run `sudo apt-get update`.

If that completes without errors, try running the remnux install command again.

**Comment by MartinRocak** [comment]
Eyyy, problem solved! 

Thank you @digitalsleuth for your help!
