### ISSUE TITLE
[Question] REMnux AMI?

### ISSUE THREAD

**Issue by HuskyHacks** [REMnux/remnux-cli#114]
I wanted to throw this out there to gauge interest. I'm developing the cloud lab lecture material for PMAT and part of the setup is to have the student build a REMnux host by provisioning an Ubuntu 20.04 host and installing the REMnux distro from scratch for use in a cloud malware analysis lab.

That got me thinking - is there any interest in maintaining an official REMnux AMI that's publically available on the AMI catalog? Or does this already exist somewhere?

**Comment by lennyzeltser** [comment]
Hi, @HuskyHacks. This sounds interesting, we just haven’t had a chance to set this up. I’m also unsure about the fees AWS might charge for the AMI. Would you be interested in guiding me through this effort so I better understand what’s involved? If so, please [send me an email](https://zeltser.com/contact).

**Comment by HuskyHacks** [comment]
Sounds great, Lenny! I'll send you an email here shortly.

Closing for now.
