### ISSUE TITLE
Broken KVM/QEMU conversion link

### ISSUE THREAD

**Issue by handyj** [REMnux/remnux-cli#115]
On the instruction page for 'Get the Virtual Appliance', https://docs.remnux.org/install-distro/get-virtual-appliance, Step 3, Import the OVA file, the link for KVM/QEMU (https://blog.ricosharp.com/posts/2019/Converting-ova-file-to-qcow2) is broken. 

In Firefox it returns:

Secure Connection Failed

An error occurred during a connection to blog.ricosharp.com. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

**Comment by lennyzeltser** [comment]
Thanks for letting me know, @handyj. I modified the link to point to another blog. (https://www.vinchin.com/en/blog/convert-ova-to-qcow2.html)
