### ISSUE TITLE
Remnux-CLI not installing on Ubuntu 20.04.5

### ISSUE THREAD

**Issue by Cloud-Hacking** [REMnux/remnux-cli#119]
Hello,

I seem to be unable to install remnux any longer, potentially as result of an update in Ubuntu.

There's no saltstack.log file under /var/cache/remnux/cli to provide further information. I suspect this might be the [same issue that impacted Sift CLI](https://github.com/teamdfir/sift/issues/594) since they're both based on SaltStack, although I'm not entirely clear what the fix is.

On a related note, I did try installation via the proposed [cast](https://github.com/ekristen/cast) tool that SIFT is shifting to, but it also failed.

`
$ sudo remnux install --mode=cloud --user=ubuntu
> remnux-cli@1.3.4.2.g87c65ef

Invalid OS or unable to determine Ubuntu version
Error: Invalid OS or unable to determine Ubuntu version
    at validOS (/snapshot/remnux-cli/remnux-cli.js:176:11)
    at run (/snapshot/remnux-cli/remnux-cli.js:681:9)
    at main (/snapshot/remnux-cli/remnux-cli.js:778:11)
    at Object.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:784:1)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:17:47

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you’re installing.
Search for the log file for “result: false” messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues`

**Comment by digitalsleuth** [comment]
Hi @Cloud-Hacking , can you confirm that you are on Ubuntu 20.04 by running `cat /etc/os-release`?

**Comment by Cloud-Hacking** [comment]
Hello,

My apologies, I have a few boxes and one wasn’t upgraded from 20.04.5, which it now is.

However, I’m still getting an error:

>> Running: echo *wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -fnoninteractive wireshark-common
>> Running: wireshark
Update returned exit code not zero
Error: Update returned exit code not zero
at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
at ChildProcess.emit (events.js:315:20)
at maybeClose (internal/child_process.js:1021:16)
at Socket. <anonymous> (internal/child_process.js:443:11)
at Socket.emit (events.js:315:20)
at Pipe. <anonymous> (net.js:674:12)

**Comment by lennyzeltser** [comment]
@Cloud-Hacking, please share your saltstack.log file.

**Comment by oDaruma** [comment]
Hi, I have the same issue, but it is because the Ubuntu version changed to LTS

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

And the current support version should be named Focal Fossa

**Comment by maxchowhk** [comment]
Hi, I have the same issue, but it is because the Ubuntu version changed to LTS

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

**Comment by digitalsleuth** [comment]
@maxchowhk Currently REMnux does not support Ubuntu 22.04 (Jammy), but it is in the works. That is the reason for the `Invalid OS` error.

**Comment by Cloud-Hacking** [comment]
Pardon the confusion on my behalf. I was testing this on a fresh EC2 instance and I accidentally chose 22.04, which @digitalsleuth noted does not work.

I re-tested this on a fresh EC2 instance with 20.04, and it did work. I think part of the issue is I'm trying to do a combined build of SIFT + Remnux. This has worked without issue in the past, and just started failing about a month ago.

@lennyzeltser, I've attached the requested saltstack.log file from the instance that's already had SIFT installed.

[saltstack-remnux.log](https://github.com/REMnux/remnux-cli/files/10932849/saltstack-remnux.log)

I'm aware this is probably outside of the "paved path", but any insight is appreciated!

**Comment by digitalsleuth** [comment]
Hi @Cloud-Hacking , can you try running `apt-get update && apt-get upgrade -y` and try the install again? For some reason it looks like there's an issue configuring the Docker GPG key and installing Docker, which cascades causing an issue installing anything else using `apt`. It could be due to an outdated apt database, so this would be the quickest way to test that theory.

The other issue could be that there's an extra repo already setup in the sources. Could you also run:
`ls /etc/apt/sources.list.d/`

I'll take a look to see if there's anything else causing the issue.

**Comment by Cloud-Hacking** [comment]
@digitalsleuth my image baking pipeline already does `apt-get update && apt-get upgrade -y` at the beginning, so it would be updated at that time. However, I tried it again, and I get the following error which is similar to the one in the saltstack.log:

`E: Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/ubuntu/ focal: /usr/share/keyrings/DOCKER-PGP-KEY.asc !=
E: The list of sources could not be read.`

output requested:

`ls /etc/apt/sources.list.d/
docker.list       gift-ubuntu-stable-focal.list       microsoft.list                  openjdk-r-ubuntu-ppa-focal.list       saltstack.list                      vscode.list
docker.list.save  gift-ubuntu-stable-focal.list.save  mono-official-stable.list       openjdk-r-ubuntu-ppa-focal.list.save  saltstack.list.save                 wireshark-dev-ubuntu-stable-focal.list
draios.list       inetsim.list                        mono-official-stable.list.save  remnux-ubuntu-stable-focal.list       sift-ubuntu-stable-focal.list
draios.list.save  inetsim.list.save                   nodesource.list                 remnux-ubuntu-stable-focal.list.save  sift-ubuntu-stable-focal.list.save`

**Comment by digitalsleuth** [comment]
Can you provide the contents of the docker.list file in /etc/apt/sources.list.d ?

**Comment by Cloud-Hacking** [comment]
`deb [arch=amd64 signed-by=/usr/share/keyrings/DOCKER-PGP-KEY.asc] https://download.docker.com/linux/ubuntu focal stable
deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable`

**Comment by digitalsleuth** [comment]
Looks like we found the problem. From this file, remove everything after the first `stable` so your file contents should look like this:

`deb [arch=amd64 signed-by=/usr/share/keyrings/DOCKER-PGP-KEY.asc] https://download.docker.com/linux/ubuntu focal stable`

Then run `sudo apt update` and you should be good to go.

**Comment by Cloud-Hacking** [comment]
@digitalsleuth,

Removing just that section alone doesn't seem to work. However, once I deleted the entire docker.list file, did the trick.

I've never looked at SaltStack before, but I think the "pkgrepo.managed" state is a simple append action. The reason I say this is because I looked at both SaltStates for sift and remnux, and they seem to follow the order in which they were ran - which in my case was the output from sift followed by what's effectively a duplicate line from remnux.

Sift:
```
sift-docker-repo:
  pkgrepo.managed:
    - humanname: Docker
    - name: deb [arch=amd64 signed-by=/usr/share/keyrings/DOCKER-PGP-KEY.asc] https://download.docker.com/linux/ubuntu {{ grains['lsb_distrib_codename'] }} stable
    - dist: {{ grains['lsb_distrib_codename'] }}
    - file: /etc/apt/sources.list.d/docker.list
    - refresh: True
    - require:
      - sls: sift.packages.software-properties-common
      - sls: sift.packages.apt-transport-https
```


Remnux:
```
docker:
  pkgrepo.managed:
    - humanname: Docker
    - name: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ grains['lsb_distrib_codename'] }} stable
    - dist: {{ grains['lsb_distrib_codename'] }}
    - file: /etc/apt/sources.list.d/docker.list
    - key_url: https://download.docker.com/linux/ubuntu/gpg
    - refresh: true
```

I'm not sure if adding "consolidate" would fix this? https://docs.saltproject.io/en/latest/ref/states/all/salt.states.pkgrepo.html

As a hack, I guess I could remove the docker.list file at the end of the SIFT install build script. I'm just not quite sure why installing both on the same machine worked for several months and stopped recently.

Thanks for your advice!

**Comment by digitalsleuth** [comment]
Hi @Cloud-Hacking , I can update the docker state to check if the repo file exists and is in the correct state, or use the `clean_file` option instead, which will empty the file first then put in the necessary date.

I'll have to update the REMnux state first anyways because the apt-key function (used in the back end by key_url) is deprecated and should be updated to reflect the same method as the SIFT state.

I'll be back at the computer shortly and will submit a PR for this.

Thanks for your help!

**Comment by lennyzeltser** [comment]
I just issued a release to incorporate the changes by @digitalsleuth that should address this.

**Comment by Cloud-Hacking** [comment]
Hello,

The previous error went away, but I'm getting different errors now.

[saltstack-latest.log](https://github.com/REMnux/remnux-cli/files/11019644/saltstack-latest.log)

Thanks!

**Comment by digitalsleuth** [comment]
Hi @Cloud-Hacking , can you run `sudo apt-get update && sudo apt-get upgrade -y` and see if that gives you any errors? Error code 100 (as seen in your log) typically comes about when there are network connectivity issues, when `apt` is unable to reach the repo or download a newer database.

**Comment by Cloud-Hacking** [comment]
Pardon the slow response. Sadly, this is still failing for me.
[saltstack-03302022.log](https://github.com/REMnux/remnux-cli/files/11110301/saltstack-03302022.log)

**Comment by digitalsleuth** [comment]
Hi @Cloud-Hacking , I took a look at the log you provided and think I've identified this particular issue. Over the last couple of days, the 'cryptography' module has been upgraded and there seem to be a few kinks with some imports. 

What I would recommend trying to resolve the immediate issue, is to run: `sudo python3 -m pip install "cryptography<40.0.0"` then try your install again. This should resolve most, if not all of the errors in the installation. If it does not, then you can try the following:

```bash
wget https://github.com/ekristen/cast/releases/download/v0.14.0/cast_v0.14.0_linux_amd64.deb
sudo dpkg -i cast_v0.14.0_linux_amd64.deb
sudo cast install --mode cloud --user ubuntu remnux
```

This will download [Erik Kristensen's new Cast tool](https://github.com/ekristen/cast) which is designed to install Salt-based repos (SIFT, REMnux etc) by pulling them from GitHub. We are planning to move towards this model shortly, but we have not yet finished our deployment setup for production. However, this option should work for you as well, and works based on SaltStack 3005.1.

**Comment by Cloud-Hacking** [comment]
Hi @digitalsleuth,

It did get a bit farther, but still having some failures. I've attached saltstack and cast output.

I'd already migrated my sift installation to cast so it's no issue to do the same for remnux. However, if any failed states occurs, then cast returns a 1, so I'll have to eat the error if I want the pipeline to succeed as-is.

[saltstack-03312022.log](https://github.com/REMnux/remnux-cli/files/11119895/saltstack-03312022.log)
[cast-remnux-install.log](https://github.com/REMnux/remnux-cli/files/11119896/cast-remnux-install.log)

**Comment by digitalsleuth** [comment]
I've identified 5 main errors in your installation now, one is a simple fix with the draios repo on our end (which I'm submitting a PR for right now), the other 4 errors seem centered around crypto and OpenSSL. I'm looking into those errors now.

Could you run the following command and attach the output in a file?

`sudo python3 -m pip list`

**Comment by Cloud-Hacking** [comment]
As requested:

[remnux-pip-list.txt](https://github.com/REMnux/remnux-cli/files/11122509/remnux-pip-list.txt)

In my build, I do `sudo python3 -m pip install importlib-metadata==4.13.0 "cryptography<40.0.0"` in order to get around the issues related to importlib-metadata and cryptography for SaltStack.

Appreciate the help - sorry for the hassles!

**Comment by digitalsleuth** [comment]
Hi @Cloud-Hacking , I've managed to come up with a solution which should resolve your current issue. Once the PR is pulled and a new release generated, you can try again and it should work. Just make sure you again do a `sudo apt-get update && sudo apt-get upgrade -y` before running the install.

**Comment by lennyzeltser** [comment]
Thank you very much, @digitalsleuth. I incorporated your fix into the new release.

**Comment by Cloud-Hacking** [comment]
@digitalsleuth I still seem to be having the other errors related to the remnux components failing, sadly. Wondering if this is an incompatibility caused by the SIFT install?

[saltstack-04042023.log](https://github.com/REMnux/remnux-cli/files/11150642/saltstack-04042023.log)

**Comment by digitalsleuth** [comment]
Hi @Cloud-Hacking , this issue is caused by the draios repo being missing for some reason. I've raised an issue [here](https://github.com/draios/sysdig/issues/1985) already to track this, and once I know more I'll let you know.

Everything else seems to have installed properly.

**Comment by digitalsleuth** [comment]
Hi @Cloud-Hacking , it looks like this may have been caused by some global DNS maintenance, but it appears the issue may be resolved. You can try again and see if this issue persists.
