### ISSUE TITLE
Error when running 'remnux upgrade' command on Remnux VMware guest

### ISSUE THREAD

**Issue by wyser-ca** [REMnux/remnux-cli#121]
After running 
remnux upgrade command 
it fails with the following message:

>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
**Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)**

[saltstack.log](https://github.com/REMnux/remnux-cli/files/10912947/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @wyser-ca , it looks like, for some reason, there was an SSL connectivity error when downloading apktool, however I cannot duplicate the error. All of the other tools installed correctly, it appears that only apktool did not download.

You can attempt the install again to get apktool and it should work fine. If the error persists, please let us know if you are behind a proxy, and provide the output of the following commands:
```bash
openssl version  
date  
lsb_release -a  
remnux version  
```

**Comment by wyser-ca** [comment]
Hi
I believed I wasn't behind a proxy, but I am currently visiting a country where the government has a reputation for pressuring ISPs to restrict access to specific websites, services, and IP addresses. To test whether this is the issue, I established a VPN connection to the United Kingdom, and it proved effective. Thank you for your help.
