### ISSUE TITLE
I can't upgrade my REMnux

### ISSUE THREAD

**Issue by 0K-cool** [REMnux/remnux-cli#122]
Hi,

I'm having issue upgrading my REMnux which I just installed by using the following command in my existing Ubuntu 20.04.6 LTS (Focal) VM:
`sudo remnux install`

I get the following error: 

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

I included my saltstack.log for your review:
[saltstack.log](https://github.com/REMnux/remnux-cli/files/11006800/saltstack.log)

Thanks.

**Comment by digitalsleuth** [comment]
Hi @nebu10uz , try running the following command then trying again:  
`sudo python3 -m pip install 'importlib-metadata<5.0.0'`

**Comment by 0K-cool** [comment]
That worked.

Thank you!

**Comment by digitalsleuth** [comment]
Glad to be of assistance :)
