### ISSUE TITLE
REMnux fails on installing ssh

### ISSUE THREAD

**Issue by LightJester** [REMnux/remnux-cli#130]
My remnux install fails to install when running ssh, see screenshot below for more info

 ![20230502_154627.jpg](https://user-images.githubusercontent.com/128987937/235701695-fdfcee0f-4666-4481-91f2-ba11c614af38.jpg)

**Comment by lennyzeltser** [comment]
Hi, @LightJester. If you share your saltstack.log file, we'll be glad to take a look to diagnose the issue. The "ssh" error message is generic and doesn't pinpoint the nature of the problem.

**Comment by LightJester** [comment]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/11374666/saltstack.log)
here you are @lennyzeltser

**Comment by lennyzeltser** [comment]
Please run the following command:

```
sudo python3 -m pip install "importlib-metadata<5.0.0"
```

Then give `remnux upgrade` another try.

**Comment by LightJester** [comment]
remnux@REMnux:/var/cache/remnux/cli/v2023.15.1$ sudo python3 -m pip install "importlib-metadata<5.0.0"
Collecting importlib-metadata<5.0.0
  Downloading importlib_metadata-4.13.0-py3-none-any.whl (23 kB)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib-metadata<5.0.0) (1.0.0)
Installing collected packages: importlib-metadata
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 6.6.0
    Uninstalling importlib-metadata-6.6.0:
      Successfully uninstalled importlib-metadata-6.6.0
Successfully installed importlib-metadata-4.13.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 
this is the output i get after running this command

**Comment by lennyzeltser** [comment]
OK, now please run `remnux upgrade`

**Comment by LightJester** [comment]
ok, will keep you updated

**Comment by LightJester** [comment]
@lennyzeltser  i am getting the same error, see the new saltstack.log 
[saltstack.log](https://github.com/REMnux/remnux-cli/files/11375037/saltstack.log)

**Comment by LightJester** [comment]
can anyone help???

**Comment by lennyzeltser** [comment]
Looks like everything installed/upgraded just fine in this round except one tool: unfurl. You can use REMnux without any issues while we look into this tool.

**Comment by LightJester** [comment]
it is not letting me install completely though

**Comment by lennyzeltser** [comment]
Even if a single tool fails, you'll see the "ssh" error you observed. The saltstack.log file shows that all tools except unfurl installed fine.

**Comment by LightJester** [comment]
i have tried 
wget https://github.com/tomnomnom/unfurl/releases/download/v0.0.1/unfurl-linux-amd64-0.0.1.tgz
tar xzf unfurl-linux-amd64-0.0.1.tgz
sudo mv unfurl /usr/bin/
from the github but i still get the error

**Comment by LightJester** [comment]
out of interest, are there any older releases of REMnux that i can download?

**Comment by lennyzeltser** [comment]
You can [download the REMnux virtual appliance](https://docs.remnux.org/install-distro/get-virtual-appliance), which encapsulates the state of REMnux at the time when the virtual appliance was created. I think I last updated the appliance a few months ago.

**Comment by digitalsleuth** [comment]
Hi @LightJester the Unfurl issue will be resolved this evening once I get back to my computer and submit a PR. I'll keep you posted here.
