### ISSUE TITLE
error while manual installation of remnux on Ubuntu 20.04

### ISSUE THREAD

**Issue by d3ne0x** [REMnux/remnux-cli#131]
Hi, i have been getting errors while installing remnux on Ubuntu 20.04.
Attached is the saltstack.log file.
Thanks
[saltstack.log](https://github.com/REMnux/remnux-cli/files/11425702/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @d3ne0x , if you run the following command, the issue should be resolved and you can attempt the installation again:
`sudo python3 -m pip install "importlib-metadata<5.0.0"`

**Comment by d3ne0x** [comment]
Hi @digitalsleuth, i still got the error while installation. error appeared after showing "running ssh"
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by d3ne0x** [comment]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/11442690/saltstack.log)
attached is the new log file.

**Comment by digitalsleuth** [comment]
Hi @d3ne0x , it looks like the error you're seeing now is related to an error I'm investigating in another issue, regarding "blinker". I'll keep you posted once I figure out a resolution for this!

**Comment by digitalsleuth** [comment]
Hi @d3ne0x this issue will be addressed in a PR I'll be submitting this evening after final testing is complete.

Cheers!
