### ISSUE TITLE
Error when installing REMnux on Ubuntu 20.04

### ISSUE THREAD

**Issue by LyNx-oBscuRe** [REMnux/remnux-cli#132]
Hey, been attempting to install remnux on an Ubuntu 20.04 VM but been having some difficulties and would appreciate some help. 
Here is my attached saltstack file. Thanks in advance!
[saltstack.log](https://github.com/REMnux/remnux-cli/files/11461557/saltstack.log)

**Comment by Wigoox** [comment]
Duplicate of https://github.com/REMnux/remnux-cli/issues/131

The manuel install on Ubuntu 20.04 seems to be bugged atm. I'm having the same problem.

**Comment by digitalsleuth** [comment]
Hi @LyNx-oBscuRe , @Wigoox is correct, in that this is the same issue as referenced above. I am almost at a workable solution for this issue, and hope to have it resolved in the next 24 hours.

**Comment by LyNx-oBscuRe** [comment]
Thanks all, apologies for reposting the same issue but I appreciate the quick responses and look forward to the fix and being able to use the tool :)

**Comment by digitalsleuth** [comment]
This issue should be resolved by end of day today. I'll keep you posted.

**Comment by LyNx-oBscuRe** [comment]
Thanks @digitalsleuth haven't had a chance to try any of the tools yet but the install completed with no errors! Much appreciated :)
