### ISSUE TITLE
Issue like  Fix for droidlysis, dc3-mwcp, unfurl, importlib #242" 

### ISSUE THREAD

**Issue by Aramane700** [REMnux/remnux-cli#133]

**Comment by digitalsleuth** [comment]
Hi @Aramane700 , the last action to run in the list of commands which builds REMnux has to do with ssh, so it's not actually failing, it's just the last function to finish before the results of the total install are presented.

From what you've provided here, it appears that there was an issue installing volatility3. Can you provide us your saltstack.log file so we can take a look to see what happened?

Cheers!

**Comment by Aramane700** [comment]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/11615958/saltstack.log)
It's kinda jam packed, I went at it for quite some time. Thanks for your diligence! @digitalsleuth
