### ISSUE TITLE
Remnux showing notinstalled

### ISSUE THREAD

**Issue by Puglord6383** [REMnux/remnux-cli#134]
I am running remnux on qemu from scratch following this: https://docs.remnux.org/install-distro/install-from-scratch.
The install has an error after a while, so I restart the VM.
On restart, it appears remnux has booted up. I run remnux upgrade:

(note that this is copied with OCR because I cannot copy/paste from VM to host yet, there might be small typos)

remnux@ubuntu:~$ remnux upgrade
> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: notinstalled

> downloading V2023.20.1
>> downloading remnux-salt-states-v2023.20.1. tar.gz.asc
>> downloading remnux-salt-states-v2023.20.1. tar.gz.sha256
>> downloading remnux-salt-states-v2023.20.1. tar.gz. sha256. asc
>> downloading remnux-salt-states-v2023.20.1. tar.gz
> validating file remnux-salt-states-v2023.20.1.tar.gz
> validating signature for remnux-salt-states-v2023.20.1. tar.gz. sha256
> extracting update remnux-salt-states-v2023.20.1. tar.gz
> no previous REMnux version found; performing a new 'dedicated* installation.
> upgrading/updating to v2023.20.1
>> Log file: /var/cache/remnux/cli/v2023.20.1/saltstack. log

Update returned exit code not zero
Error: Update returned exit code not zero
    at childProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events. js: 315:20 )
    at maybeclose (internal/child process.js: 1021:16)
    at Process.ChildProcess. handle.onexit (internal/child process. js:286:5)
    
    
will provide log file in next message

**Comment by Puglord6383** [comment]
[DEBUG] Missing configuration file: /etc/salt/minion
[DEBUG ] Using cached minion ID from /etc/salt/minion id: ubuntu
[DEBUG ] Using importlib metadata to load entry points
[ERROR 'EntryPoints' object has no attribute 'items'
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 210, in parse args
mixin after parsed func(self)
File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 887, in setup extended logging log.setup extended logging(self.config)
File "/usr/lib/python3/dist-packages/salt/log/setup.py", line 414, in setup extended logging providers = salt.loader.log handlers(opts)
File "/usr/lib/python3/dist-packages/salt/loader/ init .py", line 686, in log handlers module dirs(
File "/usr/lib/python3/dist-packages/salt/loader/ init py", line 148, in module dirs for entry point in entrypoints.iter entry points("salt.loader");:
File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 43, in wrapped return f(*args, **kwargs)
File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py",
line 62, in iter entry points
for entry point group, entry points list in entry points.items(): AttributeError: 'EntryPoints' object has no attribute 'items' Usage: salt-call [options] <function> [arguments]
salt-call: error: Error while processing <function LogLevelMixin. setup extended logging at 0x7fa9076714c0>: Traceback (most recent call last): File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 210, in parse args
mixin after parsed func(self)
File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 887, in setup extended logging
log.setup extended logging(self.config)
File "/usr/lib/python3/dist-packages/salt/log/setup.py", line 414, in setup extended logging
providers = salt.loader.log handlers(opts)
File "/usr/lib/python3/dist-packages/salt/loader/init.py", line 686, in log handlers module dirs(
File "/usr/lib/python3/dist-packages/salt/loader/ init py", line 148, in module dirs
for entry point in entrypoints.iter entry points("salt.loader"):
File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 43, in wrapped return f(*args, **kwargs)
File
"/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 62, in iter entry points for entry point group, entry points list in entry points.items(): AttributeError: 'EntryPoints' object has no attribute 'items'


![image](https://github.com/REMnux/remnux-cli/assets/119639039/3c878e64-b230-4c09-9def-a1cfd086625d)

**Comment by digitalsleuth** [comment]
Hi @Puglord6383 , this is an issue with SaltStack, which can be fixed by running the following:
`sudo python3 -m pip install "importlib-metadata<5.0.0"`

Give that a shot and try the upgrade command again.

**Comment by Puglord6383** [comment]
![image](https://github.com/REMnux/remnux-cli/assets/119639039/59a184be-3f79-498c-8615-59d202304479)


and the same thing happens when doing remnux upgrade after

**Comment by Puglord6383** [comment]
I ran
> sudo pip3 uninstall importlib_metadata
> sudo python3 -m pip install "importlib-metadata<5.0.0"
> remnux upgrade

and it seems to be finishing the installation as normal. I will update and close if it is successful.

**Comment by Puglord6383** [comment]
![image](https://github.com/REMnux/remnux-cli/assets/119639039/a9f57ddc-cc4f-4eb0-aff6-f2ece4e88fa9)
![image](https://github.com/REMnux/remnux-cli/assets/119639039/e503ee90-f45f-4bbc-adb9-660389221ba9)

It reached >>Running: ssh then hit an error. when running remnux upgrade the same thing happens again as last time.

**Comment by digitalsleuth** [comment]
Hi @Puglord6383 , the error after `>> Running: ssh` isn't related to ssh, it just means that since ssh was the last package to configure, it reported its overall status, which was an error. Can you attach the `saltstack.log` file so we can troubleshoot the actual cause?

**Comment by Puglord6383** [comment]
[logfile2.txt](https://github.com/REMnux/remnux-cli/files/11647902/logfile2.txt)

sorry that took a bit i had to figure out how to send it to my host lol

**Comment by digitalsleuth** [comment]
All good. Looks like there was a temporary internet connection issue when downloading apktool:
```bash
[ERROR   ] Failed to cache https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.7.0.jar: Error: HTTP 599: Timeout while connecting reading /iBotPeaches/apktool/downloads/apktool_2.7.0.jar
```
Aside from this download issue, everything else installed correctly. If you manually download the apktool_2.7.0.jar file from [iBotPeaches](https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.7.0.jar) and place it in `/usr/local/apktool/`, your installation will be all set. Otherwise, you can re-run the `upgrade` command again.

For the future, when using a VM instance without a GUI, or without the proper "vmtools" setup, you can always run `ip a` to find your VM's IP address, then change to the directory containing the files you want and run `python3 -m http.server` to start a simple web server from the VM. Then on your host machine, simply browse to the web address using a browser, or wget / curl.

Cheers!

**Comment by Puglord6383** [comment]
i did PS C:\Windows\system32> $listener = New-Object System.Net.HttpListener
>> $listener.Prefixes.Add("http://*:8000/")
>> $listener.Start()
>> $context = $listener.GetContext()
>> $request = $context.Request
>> $outputStream = [System.IO.File]::OpenWrite('C:\Users\Admin\OneDrive\Desktop\yourfile.txt')
>> $request.InputStream.CopyTo($outputStream)
>> $outputStream.Close()
>> $listener.Stop()
PS C:\Windows\system32>

then curl -F 'file=@/path/to/input/file.txt' http://10.0.2.2:8000
(in case you were curious)

thanks for the help :)

**Comment by Puglord6383** [comment]
it appears that link (https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.7.0.jar) has an issue, I cant open it from any of my operating systems. Is there a workaround to skip that step in the installation or something? The installation wont complete because of the error which means I can't, for example, run remnux update, because it is not fully installed.

**Comment by digitalsleuth** [comment]
Hi @Puglord6383 , is there any chance that you're behind a proxy or firewall which might prevent access to bitbucket.org? If so, you might want to consider seeing if you can configure your environment to accept a proxy, or modify the firewall to allow access to that URL.

If you're in an enterprise environment, you may want to see if there's a chance you could get an exception either for this URL, or get access to the company proxy (if there is one). Hope this helps!

**Comment by Puglord6383** [comment]
Yes that was it, I figured the site was down or something because I couldn’t access the link on multiple devices. But it was my wifi. Thank you.
