### ISSUE TITLE
remnux upgrade is failing at ChildProcess.<<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)

### ISSUE THREAD

**Issue by KhaledEid020** [REMnux/remnux-cli#138]
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

and here is the saltstack.log file:
https://drive.google.com/file/d/162Wp3u6-4hg9xGoUsw7qAgwRjecuZK9C/view?usp=sharing

**Comment by digitalsleuth** [comment]
Hi @KhaledEid020 , it looks like you had a temporary loss of connectivity during the installation process. I can see some "Temporary failure in name resolution" errors, and some other connectivity issues.

If you are working behind a proxy, that could cause an issue as well. You can follow the steps [here](https://docs.remnux.org/tips/remnux-config-tips#behind-proxy) to configure your system to allow REMnux to install behind a proxy. Also, I would recommend testing your internet connection first then trying again.

**Comment by KhaledEid020** [comment]
Thank you, Worked!
