### ISSUE TITLE
REMnux does not boot on proxmox using OVA import

### ISSUE THREAD

**Issue by tylerwhardy** [REMnux/remnux-cli#141]
Using general OVA
root@lab:~# sha256sum remnux.ova
76a12cc8ccf482e83f84b42ebfd9019ae47cf27915d0c2d686a9a407f8ee51ab  remnux.ova

Currently all combinations of [qcow2 format created at import time | qcow2 created separately | raw format import], [SATA | IDE | SCSI], and [OVA import to new | VMDK Mount on existing] have been attempted.

Either one of the two error scenarios presents:
1) Fails to find hard disk
2) Boot starts and immediately results in black screen with CPU dropping to 0% and staying that way for at least 8 hours. 

Tested on Proxmox 8.0.3 and replicated by 3rd party malware researcher 'pursepizza'

**Comment by lennyzeltser** [comment]
Perhaps someone from the community with Proxmox experience can assist. Otherwise, consider [creating a new minimal Ubuntu VM and installing REMnux](https://docs.remnux.org/install-distro/install-from-scratch) into it instead of starting with the OVA.

**Comment by tylerwhardy** [comment]
I've tried that but end up on a journal recovery page repeatedly.

/dev/sda5: recovering journal
/dev/sda5: clean, 63627/3899392 files, 1319304/15596800 blocks

I got an Ubuntu 20.04 LTS install to work with errors thrown (posted in #139 ) which will get me to the Remnux CLI. However, at that point I cant rerun the install to try to recover whatever failed.

**Comment by lennyzeltser** [comment]
@tylerwhardy, did Ubuntu install successfully? Until Ubuntu gets to that state, you won't be able to count on the REMnux installer working properly.

**Comment by tylerwhardy** [comment]
@lennyzeltser I'm not sure. I managed to get from an Ubuntu server fresh download to a Remnux desktop environment. It did throw errors along the way and tell me the install failed .. but after rebooting, it landed in the DE. I'm going to go ahead and use it, am just nervous that something somewhere broke and I'll never figure out what :D Are you aware of any self-test that REMnux can do to verify it has a valid install?

**Comment by lennyzeltser** [comment]
Usually, if the installation of the tool completes successfully, it should be functional. And if the tool won't work, it will usually be easy to notice.
