### ISSUE TITLE
File hash exception?

### ISSUE THREAD

**Issue by 0x783kb** [REMnux/remnux-cli#143]
remnux-cli@1.3.4.2.g87c65ef
> remnux-version: notinstalled

> downloading v2023.31.1
>> downloading remnux-salt-states-v2023.31.1.tar.gz.asc
>> downloading remnux-salt-states-v2023.31.1.tar.gz.sha256
>> downloading remnux-salt-states-v2023.31.1.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2023.31.1.tar.gz
> validating file remnux-salt-states-v2023.31.1.tar.gz

Hashes for remnux-salt-states-v2023.31.1.tar.gz do not match. Expected: . Actual: 1010a949d507cdb992ef72955b5a8548b3dc1ce4ef043df528b18cee1b06ce9a  /tmp/remnux-salt-states-v2023.31.1.tar.gz
.
Error: Hashes for remnux-salt-states-v2023.31.1.tar.gz do not match. Expected: . Actual: 1010a949d507cdb992ef72955b5a8548b3dc1ce4ef043df528b18cee1b06ce9a  /tmp/remnux-salt-states-v2023.31.1.tar.gz
.

**Comment by digitalsleuth** [comment]
Hi @0x783kb , this can happen sometimes if you have a connectivity issue, or if you're behind a proxy. If you are behind a proxy, you can try following the steps [here](https://docs.remnux.org/tips/remnux-config-tips#behind-proxy) to see if that resolves your issue.
