### ISSUE TITLE
2 failed 'remnux upgrade'

### ISSUE THREAD

**Issue by QVIigQZHRyov** [REMnux/remnux-cli#147]
Need some help, can someone take a look at my upgrade and point me in the right direction.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/12498037/saltstack.log)

thank you in advance.

**Comment by digitalsleuth** [comment]
Hi @QVIigQZHRyov , one of the python scripts (dotnetfile_dump.py) has an incorrect SHA256 hash, so it failed to download, but everything else installed correctly, so you should have no issues.
I've got a pull request in which will fix this for the next release.

**Comment by QVIigQZHRyov** [comment]
awesome thank you very much for the reply and help
