### ISSUE TITLE
Automater.py

### ISSUE THREAD

**Issue by geeksailor** [REMnux/remnux-cli#149]
Just wanted to let the devs know that Automater.py requires two .xml files that have to be in the same folder as the program for it to run. It also does not allow for pointing the program to where the .xml files are. It also seems to have some other .py files that I think are a part of the main script and some .pyc files from the git grab that I did that. I am not sure if you want all that in the /usr/local/bin/ folder. I would suggest to restructure it in the future to where the git gets its own folder in maybe the /opt folder for the python script(s) and all its supporting files and then linking the main script to /usr/local/bin/ for the main python script.
Cheers!

**Comment by digitalsleuth** [comment]
Thanks @geeksailor , I'll take a look at this!

**Comment by geeksailor** [comment]
@digitalsleuth 
Just wanted to let you know I ran another update this afternoon and now Automater.py tripped me up because of my previous symlink. 
> cat saltstack.log | grep -i -B 12 'result: false'
    duration: 31.176
    name: /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
    result: true
    start_time: '16:30:49.817634'
  file_|-remnux-addon-version-file_|-/etc/remnux-version_|-managed:
    __id__: remnux-addon-version-file
    __run_num__: 779
    __sls__: remnux.addon
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.remnux-tools'
    duration: 0.009
    name: /etc/remnux-version
    result: false
--
    name: /usr/local/bin/Automater.py
    result: true
    start_time: '16:41:05.550891'
  file_|-remnux-tools-automater-symlink_|-/usr/local/bin/Automater.py_|-symlink:
    __id__: remnux-tools-automater-symlink
    __run_num__: 687
    __sls__: remnux.tools.automater
    changes: {}
    comment: 'Unable to create new symlink /usr/local/bin/Automater.py -> /usr/local/automater/Automater.py:
      Found existing symlink: /usr/local/bin/Automater.py'
    duration: 30.781
    name: /usr/local/bin/Automater.py
    result: false
--
    duration: 7.13
    name: remnux-config
    result: true
    start_time: '16:40:59.021419'
  test_|-remnux-dedicated_|-remnux-dedicated_|-nop:
    __id__: remnux-dedicated
    __run_num__: 836
    __sls__: remnux.dedicated
    changes: {}
    comment: 'One or more requisite failed: remnux.addon.remnux-addon-version-file'
    duration: 0.022
    name: remnux-dedicated
    result: false
--
    duration: 1.356
    name: remnux-theme
    result: true
    start_time: '16:41:58.430304'
  test_|-remnux-tools_|-remnux-tools_|-nop:
    __id__: remnux-tools
    __run_num__: 772
    __sls__: remnux.tools
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.automater.remnux-tools-automater-symlink'
    duration: 0.011
    name: remnux-tools
    result: false

Saw the changes you made to the salt so I deleted my symlink and reran it and it worked! Your new salt is gtg! Nice job! You can close out this ticket!
Thanks for the quick fix on this Digital!

**Comment by digitalsleuth** [comment]
Hi @geeksailor , I'm glad you got this working again. I've just finished updating Automater to Python 3 with a new updated XML and an option to select the XML as well. I'm fine-tuning the API queries and reflex, and hope to push it out in a couple days. 

In the meantime, you may also want to check out the malwoverview features as well. They do provide some overlap but have a very good output structure.

**Comment by geeksailor** [comment]
@digitalsleuth,
Sorry to circle back on this but I was just messing with some of the tools while testing creating some menus I'm building and when I tested Automater.py it's still giving me an error for Python2 is no longer supported with OpenSSL. When I looked in Automater.py the header has `#/usr/bin/env python2` which I see is added by the saltstack script. Comparing the script provided by the latest build to the script provided by the source on git by 1aN0rmus, they are identical besides the #/usr/bin/env python2 change made by the saltstack. 
I know you said you updated it to Python 3 but I wanted to make sure that if you did, it didn't get overridden by salt still pulling from like the old git source or something.

Cheers!

**Comment by digitalsleuth** [comment]
Hi @geeksailor , you're absolutely right, and that's my fault. I didn't end up submitting the pull request but I thought I had. I'll get to that this weekend!

**Comment by geeksailor** [comment]
@digitalsleuth,
All good buddy. Just glad it got caught so that your work gets to be used. Looking forward to seeing your work in action!

**Comment by digitalsleuth** [comment]
So, took some time to review Automater, then started finding things I wanted to update, change, fix etc. I'm about 80% of the way there to the first release of the python3 updated version. I'll keep you posted!
