### ISSUE TITLE
Issue in REMnux upgrade

### ISSUE THREAD

**Issue by NotMorphus** [REMnux/remnux-cli#153]
Just installed REMnux in vsphere by importing the OVA file
Earlier i got the error of draios so i changed the apt source repository and it got working but still the upgrade was failing at another step(thanks for the issues posted here)
Also im now getting a notice while I tried remnux upgrade:

> remnux-cli@1.3.9.1.g849ae31
> remnux-version: v2022.28.1
NOTICE: Fixing incorrect Saltstack version configuration.
Installing and configuring Saltstack properly ...

Because of this now i am getting 2 different directories in the remnux/cli
v2022.28.1
v2023.40.2

This is the error im getting right now:
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

>>Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

>>To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

>> Log file: /var/cache/remnux/cli/v2023.40.2/saltstack.log

just noticed this could be helpful while fidning the error!

Please find attached the saltstack.log file as well
[saltstack.log v2022.28.1](https://github.com/REMnux/remnux-cli/files/13214069/saltstack.log)
[saltstack.log v2023.40.2](https://github.com/REMnux/remnux-cli/files/13214089/saltstack.log)

**Comment by NotMorphus** [comment]
>> Log file: /var/cache/remnux/cli/v2023.40.2/saltstack.log
just noticed this and thought this might be useful in finding out the issue

**Comment by NotMorphus** [comment]
Seems like the issue while i checked on the log file was that there is a temporary issue is name resolution. I checked on the host system and it seems like the website is down for some reason.

What would be plausible solution for the same?

**Comment by digitalsleuth** [comment]
Hi @NotMorphus , the error you encountered is only for the 2023.40.2 log, as the VM was installed with version 2022.28.1 on setup, and doesn't affect the issues you're experiencing now.

As for the actual error itself, there was a temporary issue with name resolution for the netresec.com page, which prevented the installers ability to download PolarProxy and NetworkMiner. Sometimes this can occur if you're behind a proxy, or behind a firewall which may not allow access to certain sites.

Everything else installed correctly, your installation is just missing those two tools. You can download them manually, or re-run the installer.

Cheers!

**Comment by NotMorphus** [comment]
Is there a way i can delete those tools 
Well i am behind a proxy but it is confirmed that there's no rule to disallow the URL 
Also this is just a concern but what is the difference between remnux upgrade and just a regular sudo apt-get update/upgrade for that matter

**Comment by NotMorphus** [comment]
While doing update also I'm facing the same issue 
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

[saltstack.log](https://github.com/REMnux/remnux-cli/files/13216835/saltstack.log)

**Comment by lennyzeltser** [comment]
@NotMorphus Everything on your system is fine based on the saltstack.log file. The only issue was that due to a networking issue, NetworkMiner and PolarProxy didn't update. Don't worry about it. Keep using the system and likely in a few days when you run `remnux upgrade` that issue will be resolved by the folks that are hosting those tools.

To answer your earlier question: Use `remnux upgrade`. This will run `apt-get` behind the scenes and also update other tools that the REMnux installer supplies without the use of `apt-get`.

**Comment by NotMorphus** [comment]
Hey thanks!
but i think you forgot to answer this question -> Is there a way i can delete those tools

**Comment by lennyzeltser** [comment]
Theoretically, yes, if you figure out which files or packages to delete, possibly after reviewing the REMnux state files that describe how the tools are installed. But even if you do that, the next time you run `remnux upgrade`, these tools will be automatically reinstalled.

**Comment by NotMorphus** [comment]
Right okay thanks!
Closing this now will open the same if I dont get the update soon ;)
