### ISSUE TITLE
Remnux installation failed @ Remnux-Pearl-Package 

### ISSUE THREAD

**Issue by varunkrs33** [REMnux/remnux-cli#155]
Installation failed due to update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

Adding the saltslack logfile for your references
[saltstack.log](https://github.com/REMnux/remnux-cli/files/13386723/saltstack.log)

For assistance go to https://github.com/REMnux/remnux-cli/issues--

Kindly someone please check and let the issue resolved

Thanks :) 

[saltstack.log](https://github.com/REMnux/remnux-cli/files/13386724/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @varunkrs33 , it looks like you are experiencing an issue with a python package which may have been installed prior to our previous fix. You can try running the following command and it should resolve the issue:
```bash
sudo python3 -m pip install --force-reinstall --break-system-packages protobuf 
sudo python3 -m pip install --force-reinstall --break-system-packages pyelftools
```
You did have one other issue listed in the log which looks like you lost network connection during the attempting install of speakeasy. This isn't related to the above, and should only have been temporary.

If you run the commands above and try the install again, you shouldn't have any issues.

Cheers!

**Comment by varunkrs33** [comment]
hi @digitalsleuth  I have tried the above solution but the same error is coming up can you suggest me any other resolution for this ?

>> Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

[saltstack.log](https://github.com/REMnux/remnux-cli/files/13388058/saltstack.log)

**Comment by varunkrs33** [comment]
@digitalsleuth After upgrading the python3 environment it is working fine now thanks for the support :)
