### ISSUE TITLE
Issue uploading OVA file to AWS

### ISSUE THREAD

**Issue by mo-kd-5343** [REMnux/remnux-cli#156]
Hi,

I am planning to use REMnux on an AWS. I am attempting to upload the image via VM import to run REMnux on an ec2 instance I have followed the guide: https://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-image-import.html , and use of the REMnux installation advice: https://docs.remnux.org/install-distro/get-virtual-appliance which includes advice on importing REMnux to AWS.

I have followed the guide and have the image located in an S3 bucket, upon running the command

 **aws ec2 import-image --description "REMnux VM Image" --disk-containers "[file://C:\Users\\OneDrive -\Documents\Project - malware enviroment\json\containers.json](file:///C:/Users//OneDrive%20-%2/Documents/Project%20-%20malware%20enviroment/json/containers.json)""**

I receive the following output:

"ImportImageTasks" : [
{
        "Description": "REMnux VM Image".
         "import TaskID": "import-ami-099f022472866b45c"
         "SnapshotDetails" : [
     {
           "DeviceName": "/dev/sde",
           "DiskImageSize": 518016469.0,
            "Format" : "RAW
           "Status": "completed",
           "UserBucket": {
                   "S3Bucket": "vm-importbucket",
                    "S3Key": "remnux-v7-focal.raw"
               }
      ]
          "Status": "deleted",
           StatusMessage": "ClientError: No valid partition. Not a valid volume.
            "tags":[]
       }
   ]
 }

I attempted this using .ova and .raw files and have received the same issue. I am unsure where to proceed the remnux file is unchanged and the file hash matches that on the documentation. Are there any solutions to this particular problem/ is there any documentation on uploading the image to aws via vm import I have struggled to find any online.

Thanks, any advice would be greatly appreciated. 

Attatched screenshot of the issue: 
![image](https://github.com/REMnux/remnux-cli/assets/152160719/775a1a39-394f-4b49-9684-9ca3b0aed06c)

**Comment by lennyzeltser** [comment]
I haven't tried this, so I cannot comment directly on the nature of the problem. However, perhaps you can instantiate an Ubuntu 20.04 minimal instance in AWS, then add REMnux to it by following the [Install from Scratch instructions](https://docs.remnux.org/install-distro/install-from-scratch)?

**Comment by mo-kd-5343** [comment]
Hi,

Thanks to help from my friend managed to get it to work, involved first using tar then gunzip to uncompress the vmdk file. From there following the instructions on VM/import page worked.

Commands: 
Untar .ova:
tar xf remnux-v7-focal.ova

Uncompress the VMDK file:
gunzip remnux-v7-focal-disk1.vmdk.gz

Screenshot of successful command:
![image](https://github.com/REMnux/remnux-cli/assets/152160719/c6ecc99e-eb56-4f6e-ad72-f843d3b310f4)

Screenshot of AMI on AWS:
![image](https://github.com/REMnux/remnux-cli/assets/152160719/389405ec-d550-4ba7-a8ee-cce25f0e5164)


Thanks for your response.
