### ISSUE TITLE
Exiftool compile failing with missing LZMA requirement

### ISSUE THREAD

**Issue by digitalsleuth** [REMnux/remnux-cli#159]
As mentioned [here](https://github.com/REMnux/remnux-cli/issues/158#issuecomment-1855979279), the compile of Exiftool failed with the following error:
```bash
Lzma.xs:18:10: fatal error: lzma.h: No such file or directory
   18 | #include "lzma.h"
      |          ^~~~~~~~
compilation terminated.
```

This issue has been opened to track the cause and provide a solution.

**Comment by Pir00t** [comment]
The upgrade completed successfully after I ran

`sudo apt-get install liblzma-dev`

Then re-ran `remnux upgrade`

**Comment by digitalsleuth** [comment]
That's what I was testing too, however when installing without it, I saw the errors (as expected) but the install completed successfully. I'll update the state file for exiftool to include liblzma-dev anyways, but it's strange that it returned success with the errors.

I'll still keep an eye on it though. Cheers!

**Comment by Pir00t** [comment]
Nice one - thanks for looking into it!

**Comment by digitalsleuth** [comment]
This issue was resolved with the recent pull and version release. Closing.
