### ISSUE TITLE
Updating to v2023.51.1 Failing

### ISSUE THREAD

**Issue by r4nd0mlyCh0sen** [REMnux/remnux-cli#160]
Good afternoon. 

I downloaded the ova and attempted to upgrade Remnux today and it keeps failing regardless of what I try.

Attached is the saltstack.log. 
[saltstack.log](https://github.com/REMnux/remnux-cli/files/13789135/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @r4nd0mlyCh0sen , I noticed you raised this issue, but then closed it as completed without comment. Not sure if you've managed to fix the issue or not, but it looks like it might be a proxy issue, or a connection issue. The errors you received were related to a "connection reset by peer" error:
```bash
	Line 63788: # [ERROR   ] Failed to cache https://www.netresec.com/?download=NetworkMiner: Error: [Errno 104] Connection reset by peer reading /
	Line 65221: # [ERROR   ] Failed to cache https://www.netresec.com/?download=PolarProxy: Error: [Errno 104] Connection reset by peer reading /
	Line 65231: # [ERROR   ] Failed to cache https://www.mitec.cz/Downloads/SSView.zip: Error: [Errno 104] Connection reset by peer reading /Downloads/SSView.zip
```

If you're still having the issue, please let us know. If you are behind a proxy, you can also review the REMnux docs for [working behind a proxy](https://docs.remnux.org/tips/remnux-config-tips#behind-proxy) to see if this helps.

Cheers!
