### ISSUE TITLE
Update returned exit code not zero

### ISSUE THREAD

**Issue by sjoshi17** [REMnux/remnux-cli#161]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/13791562/saltstack.log)

**Comment by lennyzeltser** [comment]
Looks like there was an issue with an outdated dependency of pdnstool. I just issued an update that should address it. Could you try running `remnux upgrade` to see if the installation completes successfully?

**Comment by digitalsleuth** [comment]
@lennyzeltser We might be able to close this as well.
