### ISSUE TITLE
Issue while upgrading to 2023.51.1

### ISSUE THREAD

**Issue by NotMorphus** [REMnux/remnux-cli#162]
So I was trying the upgrade from 2023.28.1 to 2023.51.1 in my home lab.
I downloaded the OVA file today itself and the upgrade is happening till ghidra and then it gets stuck there like I waited for a while but no luck!
here are the logs attached for you to check out!
[saltstack.log](https://github.com/REMnux/remnux-cli/files/13812958/saltstack.log)

**Comment by NotMorphus** [comment]
Hey an Update!
I just switched the internet and ran the commands again and saw that it was working fine!
Will update and close once it is done!

**Comment by NotMorphus** [comment]
It failed!
Please find the updated log file
[saltstack.log](https://github.com/REMnux/remnux-cli/files/13813138/saltstack.log)
If you feel this has something to do with the sources.list.d's draios.list and inetsim.list 
Here is the output of both the files
`deb [arch=amd64 signed-by=/usr/share/keyrings/DRAIOS-GPG-KEY.asc] https://download.sysdig.com/stable/deb stable/amd-64`
`deb [signed-by=/usr/share/keyrings/INETSIM-GPG-KEY.asc] http://www.inetsim.org/debian binary/`

Also, check out the sources.list file's output
`deb http://us.archive.ubuntu.com/ubuntu/ focal main restricted`
`deb http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted`
`deb http://us.archive.ubuntu.com/ubuntu/ focal universe`
`deb http://us.archive.ubuntu.com/ubuntu/ focal-updates universe`
`deb http://us.archive.ubuntu.com/ubuntu/ focal multiverse`
`deb http://us.archive.ubuntu.com/ubuntu/ focal-updates multiverse`
`deb http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse`
`deb http://security.ubuntu.com/ubuntu focal-security main restricted`
`deb http://security.ubuntu.com/ubuntu focal-security universe`
`deb http://security.ubuntu.com/ubuntu focal-security multiverse`

**Comment by lennyzeltser** [comment]
Looks like the location of the repo-signing key for Sysdig has changed. I updated it and issue a new release. Could you please run `remnux upgrade` to see if that fixed the issue?

**Comment by NotMorphus** [comment]
Hey it was done!
Thanks for the prompt response!
