### ISSUE TITLE
REMnux upgrade to v2024.1.4 failure

### ISSUE THREAD

**Issue by Nick-Ilsley** [REMnux/remnux-cli#164]
Can anyone help with the errors regarding the upgrade please?

Attach the saltstack.log "result: false"

[saltstack.log](https://github.com/REMnux/remnux-cli/files/13854955/saltstack.log)

**Comment by lennyzeltser** [comment]
@digitalsleuth, looks like some issues related to https://github.com/REMnux/salt-states/pull/270. I'll take a closer look later if you won't get a chance.

**Comment by digitalsleuth** [comment]
No, you're right that's exactly the cause. I think something messed up in my PR. I had some uninstalls in there but they didn't show. I'll get right on it.

**Comment by digitalsleuth** [comment]
Yup, I edited the state files in the VM and didn't copy the uninstall data to the final. Doing that now and testing.

**Comment by digitalsleuth** [comment]
Fixed the issues with [a new PR](https://github.com/REMnux/salt-states/pull/272). This should do the trick.

**Comment by lennyzeltser** [comment]
I just issued v2024.2.1 to include the fix. @NiicKDFIR94, please run `remnux upgrade` to see whether it worked.

**Comment by Nick-Ilsley** [comment]
@lennyzeltser @digitalsleuth all sorted, thanks guys!
