### ISSUE TITLE
I can't upgrade from v2023.11.1 to v2024.4.1

### ISSUE THREAD

**Issue by 0K-cool** [REMnux/remnux-cli#167]
I'm having issue upgrading from v2023.11..1 to v2024.4.1 by running the remnux upgrade command.

Everything looks fine at the beginning: 

![image](https://github.com/REMnux/remnux-cli/assets/1797583/e09f489a-9e52-480e-8098-f8e99dd5b252)

But at the end, I get errors and the upgrade was unsuccessful:

![image](https://github.com/REMnux/remnux-cli/assets/1797583/2e468087-e89a-4ac2-a844-0defdb045dec)

From the `/var/cache/remnux/cli/v2024.4.1/saltstack.log `

```
__id__: remnux-addon-version-file
    __run_num__: 826
    __sls__: remnux.addon
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.remnux-python3-packages,
      remnux.config.remnux-config, remnux.scripts.remnux-scripts, remnux.packages.remnux-packages'
    duration: 0.01
    name: /etc/remnux-version
    result: false

  file_|-remnux-config-bash-completion-oledump_|-/etc/bash_completion.d/oledump_|-managed:
    __id__: remnux-config-bash-completion-oledump
    __run_num__: 701
    __sls__: remnux.config.bash-completion
    changes: {}
    comment: 'One or more requisite failed: remnux.packages.oledump.remnux-packages-oledump'
    duration: 0.01
    name: /etc/bash_completion.d/oledump
    result: false

  file_|-remnux-config-bash-completion-xxxswf_|-/etc/bash_completion.d/xxxswf_|-managed:
    __id__: remnux-config-bash-completion-xxxswf
    __run_num__: 693
    __sls__: remnux.config.bash-completion
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.xxxswf.remnux-python3-packages-xxxswf'
    duration: 0.016
    name: /etc/bash_completion.d/xxxswf
    result: false

  file_|-remnux-scripts-emldump-binary_|-/usr/local/bin/emldump.py_|-managed:
    __id__: remnux-scripts-emldump-binary
    __run_num__: 480
    __sls__: remnux.scripts.emldump
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.yara-python3.remnux-python-packages-yara-python3'
    duration: 0.011
    name: /usr/local/bin/emldump.py
    result: false

  file_|-remnux-scripts-emldump-shebang_|-/usr/local/bin/emldump.py_|-replace:
    __id__: remnux-scripts-emldump-shebang
    __run_num__: 481
    __sls__: remnux.scripts.emldump
    changes: {}
    comment: 'One or more requisite failed: remnux.scripts.emldump.remnux-scripts-emldump-binary'
    duration: 0.005
    name: /usr/local/bin/emldump.py
    result: false

      WARNING: Error parsing requirements for yara-python: [Errno 2] No such file\
      \ or directory: '/usr/local/lib/python3.8/dist-packages/yara_python-4.3.1.dist-info/METADATA'\n\
      \    WARNING: No metadata found in /usr/local/lib/python3.8/dist-packages\n\
      ERROR: Cannot uninstall yara-python 4.3.1, RECORD file not found. You might\
      \ be able to recover from this via: 'pip install --force-reinstall --no-deps\
      \ yara-python==4.3.1'."
    duration: 5478.41
    name: yara-python
    result: false

      \ [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/pyelftools-0.29.dist-info/METADATA'\n\
      WARNING: Error parsing requirements for yara-python: [Errno 2] No such file\
      \ or directory: '/usr/local/lib/python3.8/dist-packages/yara_python-4.3.1.dist-info/METADATA'\n\
      \    WARNING: No metadata found in /usr/local/lib/python3.8/dist-packages\n\
      ERROR: Cannot uninstall pyelftools 0.29, RECORD file not found. You might be\
      \ able to recover from this via: 'pip install --force-reinstall --no-deps pyelftools==0.29'."
    duration: 5275.244
    name: pyelftools
    result: false

  pip_|-remnux-python3-packages-ratdecoders_|-malwareconfig_|-installed:
    __id__: remnux-python3-packages-ratdecoders
    __run_num__: 360
    __sls__: remnux.python3-packages.ratdecoders
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.yara-python3.remnux-python-packages-yara-python3'
    duration: 0.011
    name: malwareconfig
    result: false

      \ (557 bytes)\nCollecting gcsfs>=2023.1.0 (from -r https://raw.githubusercontent.com/volatilityfoundation/volatility3/develop/requirements.txt\
      \ (line 21))\n  Using cached gcsfs-2024.2.0-py2.py3-none-any.whl.metadata (1.6\
      \ kB)\nCollecting s3fs>=2023.1.0 (from -r https://raw.githubusercontent.com/volatilityfoundation/volatility3/develop/requirements.txt\
      \ (line 22))\n  Using cached s3fs-2024.2.0-py3-none-any.whl.metadata (1.6 kB)\
      \ ERROR: Could not install packages due to an OSError: [Errno 2] No such file\
      \ or directory: '/usr/local/lib/python3.8/dist-packages/yara_python-4.3.1.dist-info/METADATA'"
    duration: 1827.629
    name: remnux-python3-packages-volatility3-requirements
    result: false

  pip_|-remnux-python3-packages-xxxswf_|-git+https://github.com/viper-framework/xxxswf.git_|-installed:
    __id__: remnux-python3-packages-xxxswf
    __run_num__: 333
    __sls__: remnux.python3-packages.xxxswf
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.yara-python3.remnux-python-packages-yara-python3'
    duration: 0.007
    name: git+https://github.com/viper-framework/xxxswf.git
    result: false

  pkg_|-remnux-packages-oledump_|-oledump_|-installed:
    __id__: remnux-packages-oledump
    __run_num__: 202
    __sls__: remnux.packages.oledump
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.yara-python3.remnux-python-packages-yara-python3'
    duration: 0.006
    name: oledump
    result: false

    __id__: remnux-config
    __run_num__: 729
    __sls__: remnux.config
    changes: {}
    comment: 'One or more requisite failed: remnux.config.bash-completion.remnux-config-bash-completion-xxxswf,
      remnux.config.bash-completion.remnux-config-bash-completion-oledump'
    duration: 0.009
    name: remnux-config
    result: false

  test_|-remnux-dedicated_|-remnux-dedicated_|-nop:
    __id__: remnux-dedicated
    __run_num__: 883
    __sls__: remnux.dedicated
    changes: {}
    comment: 'One or more requisite failed: remnux.addon.remnux-addon-version-file'
    duration: 0.008
    name: remnux-dedicated
    result: false

  test_|-remnux-packages_|-remnux-packages_|-nop:
    __id__: remnux-packages
    __run_num__: 229
    __sls__: remnux.packages
    changes: {}
    comment: 'One or more requisite failed: remnux.packages.oledump.remnux-packages-oledump'
    duration: 0.008
    name: remnux-packages
    result: false

    __sls__: remnux.python3-packages
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.xxxswf.remnux-python3-packages-xxxswf,
      remnux.python3-packages.pyelftools.remnux-python3-packages-pyelftools, remnux.python3-packages.yara-python3.remnux-python-packages-yara-python3,
      remnux.python3-packages.volatility3.remnux-python3-packages-volatility3-requirements,
      remnux.python3-packages.ratdecoders.remnux-python3-packages-ratdecoders'
    duration: 0.009
    name: remnux-python3-packages
    result: false

    __id__: remnux-scripts
    __run_num__: 639
    __sls__: remnux.scripts
    changes: {}
    comment: 'One or more requisite failed: remnux.scripts.emldump.remnux-scripts-emldump-shebang,
      remnux.scripts.emldump.remnux-scripts-emldump-binary'
    duration: 0.009
    name: remnux-scripts
    result: false
```

I did performed the following but it didn't help:
```
pip install --force-reinstall --no-deps yara-python==4.3.1
pip install --force-reinstall --no-deps pyelftools==0.29
```
Here's my current environment:

![image](https://github.com/REMnux/remnux-cli/assets/1797583/8dad9948-37ab-4629-8d6d-ab976aa68ff1)

**Comment by pitanga** [comment]
I have the same problem.

**Comment by nicolasazuara** [comment]
I have the same issue even with a fresh copy of REMnux VM

**Comment by digitalsleuth** [comment]
Hi folks, sorry about the delay in getting back to you. Could all of you provide your saltstack.log files for your installation? This will help us track down the errors in the install process.

Cheers!

**Comment by nicolasazuara** [comment]
Thank you @digitalsleuth

[saltstack.log](https://github.com/REMnux/remnux-cli/files/14307584/saltstack.log)

A fresh copy of REMnux VM, running in VirtualBox, no proxy or VPN

**Comment by 0K-cool** [comment]
Hi @digitalsleuth,

As requested, here is the log:
[saltstack.log](https://github.com/REMnux/remnux-cli/files/14334682/saltstack.log)

Thank you!

**Comment by jemaiah** [comment]
Same problem, Blocked in ssh install , I also tried 
#remnux update
and now I had this problem : 
remnux@remnux:~$ remnux update
> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: v2022.28.1

Installing and configuring SaltStack properly ...

Command failed: apt-get update
E: Failed to fetch http://download.draios.com/stable/deb/stable-amd64/InRelease  403  Forbidden [IP: 52.216.215.21 80]
E: The repository 'http://download.draios.com/stable/deb stable-amd64/ InRelease' is not signed.

Error: Command failed: apt-get update
E: Failed to fetch http://download.draios.com/stable/deb/stable-amd64/InRelease  403  Forbidden [IP: 52.216.215.21 80]
E: The repository 'http://download.draios.com/stable/deb stable-amd64/ InRelease' is not signed.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Seems the repository used is broken

**Comment by nicolaioestergaard** [comment]
Hi,
I have the same issue only I cannot upgrade from v2022.28.1 to v2024.4.1.
I did a fresh download of the general OVA (since I use VMWare Fusion) as mentioned in the [documentation](https://docs.remnux.org/install-distro/get-virtual-appliance#download-virtual-appliance) and v2022.28.1 was the version that the OVA file came with.

Here is my [saltstack.log](https://github.com/REMnux/remnux-cli/files/14398168/saltstack.log) file and here is my setup:
```
remnux@remnux:~$ cat /etc/remnux-config 
version: v2022.28.1
mode: dedicated
user: remnux
remnux@remnux:~$ cat /etc/remnux-version 
v2022.28.1
remnux@remnux:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
I also tried what @jemaiah did by running ```remnux update``` and got the same error (the error also occurred if I ran ```remnux install --version=v2024.4.1```).
I tried visiting http://download.draios.com/stable/deb in a browser and got a 403. I then tried visiting just http://draios.com and got redirected to https://sysdig.com/.
After searching for sysdig I found this [Github repo](https://github.com/draios/sysdig) and went to the releases page where I found some deb packages listed which could indicate that the deb package for sysdig is now hosted on Github.

**Comment by digitalsleuth** [comment]
Hi @nicolaioestergaard and @jemaiah , the repo you currently have in your system for sysdig is outdated, and this is what is causing the issue. You can try the following and it should resolve the immediate issue:
```bash
sudo wget -O /usr/share/keyrings/DRAIOS-GPG-KEY.asc "https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public"
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/DRAIOS-GPG-KEY.asc] https://download.sysdig.com/stable/deb stable-amd64/' | sudo tee /etc/apt/sources.list.d/draios.list
sudo apt update
```

Now you can re-run the install command and it should work.

**Comment by digitalsleuth** [comment]
@nebu10uz For your issue, the following should work:
```bash
sudo touch /usr/local/lib/python3.8/dist-packages/yara_python-4.3.1.dist-info/METADATA
sudo touch /usr/local/lib/python3.8/dist-packages/yara_python-4.3.1.dist-info/RECORD
sudo touch /usr/local/lib/python3.8/dist-packages/pyelftools-0.29.dist-info/METADATA
sudo touch /usr/local/lib/python3.8/dist-packages/pyelftools-0.29.dist-info/RECORD
```
Once that's done, you can try the install command again and you should be good to go.

**Comment by digitalsleuth** [comment]
@nicolasazuara Your issue should be resolved now with the recent releases. It was originally caused by m2crypto not installing due to their no longer supporting Python 2.

**Comment by nicolasazuara** [comment]
> @nicolasazuara Your issue should be resolved now with the recent releases. It was originally caused by m2crypto not installing due to their no longer supporting Python 2.

Thank you, I confirm that it works now (in VM image and from scratch)

**Comment by 0K-cool** [comment]
> @nebu10uz For your issue, the following should work:
> 
> ```shell
> sudo touch /usr/local/lib/python3.8/dist-packages/yara_python-4.3.1.dist-info/METADATA
> sudo touch /usr/local/lib/python3.8/dist-packages/yara_python-4.3.1.dist-info/RECORD
> sudo touch /usr/local/lib/python3.8/dist-packages/pyelftools-0.29.dist-info/METADATA
> sudo touch /usr/local/lib/python3.8/dist-packages/pyelftools-0.29.dist-info/RECORD
> ```
> 
> Once that's done, you can try the install command again and you should be good to go.

Yes, that worked. Thank you!

You may close this issue if anybody else doesn't have a problem or all is resolved.

**Comment by nicolaioestergaard** [comment]
> Hi @nicolaioestergaard and @jemaiah , the repo you currently have in your system for sysdig is outdated, and this is what is causing the issue. You can try the following and it should resolve the immediate issue:
> 
> ```shell
> sudo wget -O /usr/share/keyrings/DRAIOS-GPG-KEY.asc "https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public"
> echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/DRAIOS-GPG-KEY.asc] https://download.sysdig.com/stable/deb stable-amd64/' | sudo tee /etc/apt/sources.list.d/draios.list
> sudo apt update
> ```
> 
> Now you can re-run the install command and it should work.

Thank you, that fixed it for me.

**Comment by digitalsleuth** [comment]
@lennyzeltser I think we can close this issue.
