### ISSUE TITLE
 Error when manually installing REMnux on Ubuntu 20.04 Virutalbox

### ISSUE THREAD

**Issue by ghuser19** [REMnux/remnux-cli#169]
Hi, I attempted to install REMnux on an Ubuntu 20.04 Virutalbox a couple of times, but always ended with errors and would appreciate some help.
I installed it as addon mode. The host OS is also a Linux, not a Windows (no hyper-v issues). Set the VM network to Bridge Adapt, also tried Bridge Adapt - Paravirtualized Network.

Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Tried the following, it doesn't work.
sudo apt update
sudo apt autoremove
sudo apt --fix-broken install

Here is my saltstack file. Thanks in advance!
[saltstack.log](https://github.com/REMnux/remnux-cli/files/14469003/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @ghuser19 , it looks like you attempted the install just before the update was released which fixes the issue with m2crypto (which you've encountered here). I'd recommend attempting the installation again.

**Comment by ghuser19** [comment]
Thanks for your prompt reply. Will try again and let you know if it works or not.

**Comment by ghuser19** [comment]
Hi @digitalsleuth, I tried again and the installation completed without errors. Thanks again.
