### ISSUE TITLE
errors upgrading to saltstack v2020.48.13

### ISSUE THREAD

**Issue by jdubp** [REMnux/remnux-cli#17]
Below is the output of the saltstack log. It appears to be an issue with polar proxy

remnux@remnux:~$ cat /var/cache/remnux/cli/v2020.48.13/saltstack.log | grep -a -i -C 5 'result: false'
    __run_num__: 659
    __sls__: remnux.tools.polarproxy
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-source'
    duration: 0.007
    result: false
    start_time: '12:39:11.413326'
  archive_|-remnux-scripts-base64dump-archive_|-/usr/local/src/remnux/base64dump-0.0.12_|-extracted:
    __id__: remnux-scripts-base64dump-archive
    __run_num__: 424
    __sls__: remnux.scripts.base64dump
--
    __run_num__: 660
    __sls__: remnux.tools.polarproxy
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-archive'
    duration: 0.008
    result: false
    start_time: '12:39:11.427090'
  file_|-/usr/share/applications/debian-uxterm.desktop_|-/usr/share/applications/debian-uxterm.desktop_|-absent:
    __id__: /usr/share/applications/debian-uxterm.desktop
    __run_num__: 690
    __sls__: remnux.theme.gnome-config.remove-app-icons
--
    __run_num__: 680
    __sls__: remnux.addon
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.remnux-tools'
    duration: 0.007
    result: false
    start_time: '12:39:36.113418'
  file_|-remnux-config-android-project-creator-permissions_|-/opt/AndroidProjectCreator/library_|-directory:
    __id__: remnux-config-android-project-creator-permissions
    __run_num__: 585
    __sls__: remnux.config.android-project-creator
--
    comment: Specified sha256 checksum for /usr/local/src/remnux/files/PolarProxy_0-8-15-1_linux-x64.tar
      (c71601921633bc60b0bbb507ca291b5bf2c22b0bf82faebab83937c285bcb7b9) does not
      match actual checksum (9c0bef3bff91ef66f70daf91a423829104728f99d0a2a52bbc13a5c1d7ed60b8)
    duration: 42861.793
    name: /usr/local/src/remnux/files/PolarProxy_0-8-15-1_linux-x64.tar
    result: false
    start_time: '12:38:28.536468'
  file_|-remnux-polarproxy-wrapper_|-/usr/local/bin/polarproxy_|-managed:
    __run_num__: 661
    __sls__: remnux.tools.polarproxy
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy./usr/local/polarproxy/PolarProxy'
    duration: 0.012
    result: false
    start_time: '12:39:11.441898'
  file_|-remnux-pyinstaller-shebang_|-/usr/local/bin/pyinstxtractor.py_|-prepend:
    __id__: remnux-pyinstaller-shebang
    __run_num__: 440
    __sls__: remnux.scripts.pyinstaller-extractor
--
    __run_num__: 734
    __sls__: remnux.dedicated
    changes: {}
    comment: 'One or more requisite failed: remnux.addon.remnux-addon-version-file'
    duration: 0.008
    result: false
    start_time: '12:39:41.339691'
  test_|-remnux-node-packages_|-remnux-node-packages_|-nop:
    __id__: remnux-node-packages
    __run_num__: 677
    __sls__: remnux.node-packages
--
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-wrapper,
      remnux.tools.polarproxy./usr/local/polarproxy/PolarProxy, remnux.tools.polarproxy.remnux-polarproxy-archive,
      remnux.tools.polarproxy.remnux-polarproxy-source'
    duration: 0.01
    result: false
    start_time: '12:39:18.001541'
  user_|-remnux-user-remnux_|-remnux_|-present:
    __id__: remnux-user-remnux
    __run_num__: 342
    __sls__: remnux.config.user

**Comment by lennyzeltser** [comment]
Looks like the PolarProxy file has changed, so the REMnux installer was expecting a different hash value for that file. I adjusted the expected value now. Could you try the installation again? I'm thinking PolarProxy was the issue that may have also caused the other errors you saw in the log file.

**Comment by jdubp** [comment]
Thanks Lenny! That fixed it. Amazing work on Remnux btw.

**Comment by najashark** [comment]
Hi @lennyzeltser 
can you update source_hash for polarproxy to match the new version `PolarProxy_0-8-16_linux-x64.tar`

**Comment by digitalsleuth** [comment]
Good morning @najashark, when looking at the salt state for PolarProxy, it's actually the version that needs to be updated, not the hash itself. I've submitted a pull request [here](https://github.com/REMnux/salt-states/pull/185) to update the version to match what's downloaded.

Thanks for the attention to detail!

**Comment by lennyzeltser** [comment]
Thanks for reporting the issue, @najashark, and for addressing it, @digitalsleuth! I just issued the new release to incorporate the fix.
