### ISSUE TITLE
REMnux boots into blackscreen on Proxmox VE 8.1

### ISSUE THREAD

**Issue by r3dpan** [REMnux/remnux-cli#174]
Hello,

i'm currently trying to setup a remnux vm on proxmox ve 8.1. While trying this, i always seem to run into the issue that, after the successful setup, remnux always boots into a black screen from which i can't recover.

Methods i tried for setting up the vm:
1. Using the virtual appliance
_-> Importing the vmdk (from inside ova) on the vm works successfully but booting from it (disk attached with scsi/sata/ide) always results in a black screen that doesn't resolve even after waiting for ~1h_
2. Installing ubuntu mini 20.04 (https://docs.remnux.org/install-distro/install-from-scratch) and running the remnux-cli for setup
_-> I am able to boot into ubuntu after installation and the remnux-cli script runs trough without a single error. After rebooting i get a black screen displayed from which i can not recover. Even after applying the tweaks from the docs (display settings: spice) this does not resolve. When shutting down the vm i do however get the ubuntu 20.04 logo displayed._

So far i'm always following the recommended settings mentioned on the remnux docs but i'm still unable to successfully create a vm that doesn't boot me straight to a black screen. Is this a general problem with using proxmox ve 8.1 as a hypervisor for remnux or is there something i'm still missing to successfully set this up?

I would really appreciate any help.

**Comment by digitalsleuth** [comment]
Hi @r3dpan , this is an interesting issue you've encountered. I'm wondering if you might be able to answer a few questions for me to help resolve the problem:
  - When in the black screen, have you tried switching TTY's (selecting keys between F1-F7) to see if it's a GUI issue and if you can get a terminal?
  - Have you attempted to ping / ssh into the VM once it was booted up into the black screen to see if it is in fact fully booted with services enabled?
  - Have you tried importing the same OVA as an independent VM in something other than proxmox?

By no means are you typically expected to do these things to make the OVA work, these are just things that might help narrow down the source of the issue. I will try to set up a proxmox installation in the next day or two and attempt to do the same thing you have to see if I get the same result.

Cheers.

**Comment by r3dpan** [comment]
@digitalsleuth I'm trying to answer your questions as good as i can:

> When in the black screen, have you tried switching TTY's (selecting keys between F1-F7) to see if it's a GUI issue and if you can get a terminal?

When i try this nothing actually changes on the black screen so i guess this is not working.

> Have you attempted to ping / ssh into the VM once it was booted up into the black screen to see if it is in fact fully booted with services enabled?

 I do see the vm on my router with an ipadress assigned to it that i can ping.

> Have you tried importing the same OVA as an independent VM in something other than proxmox?

I do currently have not the option to test this.

I also did a little bit more digging and found out that if i select 'vmware compatible' in the display settings (hardware) of the vm i'm able to successfully boot into the remnux desktop.
After that i made sure those two packages were installed (missing when installing from scratch - ubuntu mini iso):

- qemu-guest-agent
- spice-vdagent

Sadly this still didn't resolve the issue as i still get booted to a black screen when switching display settings (default/spice) again.

Further research does however hint that this could probably be related to the auto-login (and automatically window/desktop resizing afterwards) that the remnux-cli script configures. It seems like many people online had a pretty similar issue when configuring auto-login on a ubuntu (18 - 22) vm on proxmox. I am however unable to fix the issue with the workarounds i found so far.

**Comment by r3dpan** [comment]
@digitalsleuth 
It seems like i have found the culprit.
There is a known bug for ubuntu 19.x - 20.x (maybe even 22.x) where the splash screen breaks auto-login.
https://ubuntuhandbook.org/index.php/2020/01/login-loop-auto-login-enabled-in-ubuntu-19-10-with-nvidia-driver/

For future people finding this thread:

You can solve this issue by editing the file /etc/default/grub
`GRUB_CMDLINE_LINUX_DEFAULT="quiet **splash**"`

Simply remove the 'splash'-keyword and save the file.

Afterwards regenerate grub and reboot the machine.
`update-grub`

**Comment by digitalsleuth** [comment]
Hi @r3dpan , this is an interesting find. I had never come across this before, but thanks for keeping us posted and providing a resolution for this issue.

Cheers!
