### ISSUE TITLE
PolarProxy new release

### ISSUE THREAD

**Issue by TheDanielM** [REMnux/remnux-cli#176]
I was doing `sudo remnux install` several times, but it did not work. I checked the `saltstack.log` and saw that there is an error with PolarProxy sha256 checksum.

I looked into it and realised, that renmux is using [https://www.netresec.com/?download=PolarProxy](url) and is expecting PolarProxy 0.9 to be downloaded, but gets in fact PolarProxy 1.0 which was actually released today - [https://www.netresec.com/?page=Blog&month=2024-05&post=PolarProxy-1-0-Released](url)

**Comment by Scttpr** [comment]
Probably handled here: https://github.com/REMnux/salt-states/pull/284

**Comment by lennyzeltser** [comment]
Yes.
