### ISSUE TITLE
upgrade failing

### ISSUE THREAD

**Issue by dondurma-00** [REMnux/remnux-cli#18]
Dear Lenny
I use your platform and it is great and very helpful - thank you.
Lately I cannot upgrade it (using v7) - remnux upgrade always ends with an error (cat of the result:false below)
"
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
"
cat /var/cache/remnux/cli/v2020.48.13/saltstack.log | grep -a -i -C 5 'result: false'
    __run_num__: 537
    __sls__: remnux.config.ghidra
    changes: {}
    comment: 'One or more requisite failed: remnux.config.ghidra.remnux-config-ghidra-gdt-file'
    duration: 0.006
    result: false
    start_time: '16:43:47.558017'
  archive_|-remnux-mitmproxy-archive_|-/usr/local/bin/_|-extracted:
    __id__: remnux-mitmproxy-archive
    __run_num__: 287
    __sls__: remnux.python3-packages.mitmproxy
--
    __run_num__: 534
    __sls__: remnux.tools.ghidra
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.ghidra.remnux-tools-ghidra-source'
    duration: 0.006
    result: false
    start_time: '16:43:47.533224'
  archive_|-remnux-tools-jad-archive_|-/usr/local/src/remnux/jad-1.5.8_|-extracted:
    __id__: remnux-tools-jad-archive
    __run_num__: 609
    __sls__: remnux.tools.jad
--
    __run_num__: 535
    __sls__: remnux.tools.ghidra
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.ghidra.remnux-tools-ghidra-archive'
    duration: 0.006
    result: false
    start_time: '16:43:47.543620'
  file_|-/usr/local/bin/ipwhois_cli.py_|-/usr/local/bin/ipwhois_cli.py_|-managed:
    __id__: /usr/local/bin/ipwhois_cli.py
    __run_num__: 283
    __sls__: remnux.python3-packages.ipwhois
--
    __run_num__: 680
    __sls__: remnux.addon
    changes: {}
    comment: 'One or more requisite failed: remnux.config.remnux-config, remnux.tools.remnux-tools'
    duration: 0.006
    result: false
    start_time: '16:44:33.542388'
  file_|-remnux-config-android-project-creator-permissions_|-/opt/AndroidProjectCreator/library_|-directory:
    __id__: remnux-config-android-project-creator-permissions
    __run_num__: 585
    __sls__: remnux.config.android-project-creator
--
    __run_num__: 538
    __sls__: remnux.config.ghidra
    changes: {}
    comment: 'One or more requisite failed: remnux.config.ghidra.remnux-config-ghidra-gdt-archive'
    duration: 0.006
    result: false
    start_time: '16:43:47.570791'
  file_|-remnux-config-ghidra-file-tool-code-browser_|-/home/remnux/.ghidra/.ghidra_9.2_PUBLIC/tools/_code_browser.tcd_|-managed:
    __run_num__: 539
    __sls__: remnux.config.ghidra
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.ghidra.remnux-tools-ghidra-source,
      remnux.tools.ghidra.remnux-tools-ghidra-archive, remnux.tools.ghidra./usr/local/bin/ghidra'
    duration: 0.007
    result: false
    start_time: '16:43:47.581396'
  ? file_|-remnux-config-ghidra-file-tool-version-tracking_|-/home/remnux/.ghidra/.ghidra_9.2_PUBLIC/tools/_version
    _tracking.tcd_|-managed
  : __run_num__: 540
    __sls__: remnux.config.ghidra
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.ghidra.remnux-tools-ghidra-source,
      remnux.tools.ghidra.remnux-tools-ghidra-archive, remnux.tools.ghidra./usr/local/bin/ghidra'
    duration: 0.006
    result: false
    start_time: '16:43:47.594280'
  file_|-remnux-config-ghidra-gdt-file_|-/usr/local/src/remnux/files/ghidra-data-type.zip_|-managed:
    __run_num__: 536
    __sls__: remnux.config.ghidra
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.ghidra.remnux-tools-ghidra-source,
      remnux.tools.ghidra.remnux-tools-ghidra-archive, remnux.tools.ghidra./usr/local/bin/ghidra'
    duration: 0.004
    result: false
    start_time: '16:43:47.545887'
  file_|-remnux-config-ghidra-icon_|-/usr/share/applications/ghidra.desktop_|-managed:
    __run_num__: 542
    __sls__: remnux.config.ghidra
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.ghidra.remnux-tools-ghidra-source,
      remnux.tools.ghidra.remnux-tools-ghidra-archive, remnux.tools.ghidra./usr/local/bin/ghidra'
    duration: 0.006
    result: false
    start_time: '16:43:47.612613'
  file_|-remnux-config-ghidra-owner_|-/home/remnux/.ghidra_|-directory:
    __run_num__: 541
    __sls__: remnux.config.ghidra
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.ghidra.remnux-tools-ghidra-source,
      remnux.tools.ghidra.remnux-tools-ghidra-archive, remnux.tools.ghidra./usr/local/bin/ghidra'
    duration: 0.006
    result: false
    start_time: '16:43:47.604281'
  file_|-remnux-config-inetsim-permissions_|-/var/lib/inetsim/certs/default_key.pem_|-managed:
    __id__: remnux-config-inetsim-permissions
    __run_num__: 504
    __sls__: remnux.config.inetsim
--
    changes: {}
    comment: 'Failed to cache https://ghidra-sre.org/ghidra_9.2_PUBLIC_20201113.zip:
      Error: HTTP 403: Forbidden reading https://ghidra-sre.org/ghidra_9.2_PUBLIC_20201113.zip'
    duration: 345.18
    name: /usr/local/src/remnux/files/ghidra_9.2_PUBLIC_20201113.zip
    result: false
    start_time: '16:43:47.177645'
  file_|-remnux-tools-jad-binary_|-/usr/local/bin/jad_|-managed:
    __id__: remnux-tools-jad-binary
    __run_num__: 610
    __sls__: remnux.tools.jad
--
    comment: 'One or more requisite failed: remnux.config.ghidra.remnux-config-ghidra-file-tool-version-tracking,
      remnux.config.ghidra.remnux-config-ghidra-file-preferences, remnux.config.ghidra.remnux-config-ghidra-owner,
      remnux.config.ghidra.remnux-config-ghidra-gdt-archive, remnux.config.ghidra.remnux-config-ghidra-icon,
      remnux.config.ghidra.remnux-config-ghidra-file-tool-code-browser, remnux.config.ghidra.remnux-config-ghidra-gdt-file'
    duration: 0.006
    result: false
    start_time: '16:43:50.937666'
  test_|-remnux-dedicated_|-remnux-dedicated_|-nop:
    __run_num__: 734
    __sls__: remnux.dedicated
    changes: {}
    comment: 'One or more requisite failed: remnux.addon.remnux-addon-version-file'
    duration: 0.009
    result: false
    start_time: '16:44:37.245805'
  test_|-remnux-node-packages_|-remnux-node-packages_|-nop:
    __id__: remnux-node-packages
    __run_num__: 677
    __sls__: remnux.node-packages
--
    __sls__: remnux.tools
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.ghidra.remnux-tools-ghidra-source,
      remnux.tools.ghidra.remnux-tools-ghidra-archive, remnux.tools.ghidra./usr/local/bin/ghidra'
    duration: 0.006
    result: false
    start_time: '16:44:08.791921'
  user_|-remnux-user-remnux_|-remnux_|-present:
    __id__: remnux-user-remnux
    __run_num__: 342
    __sls__: remnux.config.user

IMHO the problem is that ghidra-sre download from the site http://ghidra-sre.org/ is blocked from my location (Israel). Is it any way to comment out ghidra only to by able to upgrade the rest of the system?
Thank you for this great project
Gaia

**Comment by lennyzeltser** [comment]
Gaia,

You're right. The issue is that the website hosting Ghidra is blocking downloads from your location.

To avoid this issue, I adjusted how REMnux installs Ghidra, so that the REMnux installer no longer needs to download the Ghidra file from ghidra-sre.

Please try installing/upgrading REMnux now and let me know if it works for you.

**Comment by dondurma-00** [comment]
Works great - thank you very much Lenny
