### ISSUE TITLE
Cannot upgrade REMnux VM

### ISSUE THREAD

**Issue by CataTBH** [REMnux/remnux-cli#182]
Hello!
[saltstack.log](https://github.com/user-attachments/files/15535070/saltstack.log)

I've attached the saltstack log, seems to be some issues regarding

remnux.addon.remnux-addon-version-file

remnux.python3-packages.malwoverview.remnux-python3-packages-malwoverview-config-file

remnux.python3-packages.remnux-python3-packages

**Comment by lennyzeltser** [comment]
@CataTBH, I just issued a new release (v2024.23.1) in attempt to address this issue. Please run `remnux upgrade` when you get the chance to see if it works as intended.

**Comment by CataTBH** [comment]
> @CataTBH, I just issued a new release (v2024.23.1) in attempt to address this issue. Please run `remnux upgrade` when you get the chance to see if it works as intended.

Fixed it.Thank you very much.
