### ISSUE TITLE
Getting error at SSH during install

### ISSUE THREAD

**Issue by sashlabs-cyber** [REMnux/remnux-cli#19]
Getting the following error:

`
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
`

I have attached saltstack.log file for your reference.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/5652842/saltstack.log)

**Comment by lennyzeltser** [comment]
Thanks for reporting the issue! Looks like the problem was due to the recent change in pyinstxtractor.py, which caused the REMnux installer to complain about the unexpected value of the file. I made a tweak to address this. Please give it a try.

**Comment by sashlabs-cyber** [comment]
Hi @lennyzeltser,

The issue seems to be still exist. I am still getting the same error when i ran the command "remnux upgrade". Please let me know if there is anything that i am missing here. I have attached the recent saltstack.log file for your reference.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/5656862/saltstack.log)

**Comment by lennyzeltser** [comment]
Are you running the "remnux" command directly as root, by any chance? If so, please run it as the user "remnux" instead.

**Comment by sashlabs-cyber** [comment]
Hi @lennyzeltser ,

I tried running the remnux command with non-root user but still i got the same error. Should i create a new user account with remnux for this to work ?

Just a little background, I am trying to fresh install a remnux on the Ubuntu 18.04.

**Comment by sashlabs-cyber** [comment]
Hi @lennyzeltser ,

When i tried a fresh install with the user remnux, It worked and the installation completed without any errors. Closing this issue since its resolved.

**Comment by hartescout** [comment]
I am having the same issue with it stopping on ssh on the 18.04 ova and fresh install. I do not think this error is fixed quite yet.

**Comment by lennyzeltser** [comment]
Please share your saltstack.log file and I will be glad to take a look. Unfortunately, ssh is the point when SaltStack reports most errors, even those unrelated to ssh.
