### ISSUE TITLE
ova import error,vmware worksation

### ISSUE THREAD

**Issue by smartzh** [REMnux/remnux-cli#192]
[remnux-v7-focal.ova](https://sourceforge.net/projects/remnux/files/ova-general/remnux-v7-focal.ova/download)

Unzip the file show data error.
![1](https://github.com/user-attachments/assets/0576d783-b442-40d0-acf4-7d0b265b0f65)

**Comment by lennyzeltser** [comment]
Thanks for reporting this issue, @smartzh. Looks like the file on SourceForge is corrupted. I'll supply a new version of the file and let you know once it's there.

**Comment by lennyzeltser** [comment]
@smartzh, I've re-uploaded the OVA file to SourceForge, then downloaded and confirmed that the file has the expected SHA256 hash. Please give it another try. I'm wondering whether SourceForge consistently servers the file correctly or whether it sometimes corrupts the file.

**Comment by smartzh** [comment]
@lennyzeltser it worked,thanks for your great support.
