### ISSUE TITLE
[KNOWN ISSUE] Saltstack repo migration

### ISSUE THREAD

**Issue by digitalsleuth** [REMnux/remnux-cli#194]
Due to [recent shifts in the Saltstack architecture](https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/), the current methods of installing / upgrading REMnux are non-functioning. This is something we are aware of and are working towards a solution.

**Comment by lennyzeltser** [comment]
@digitalsleuth, with the recent updates we should be able to close this one. Do you agree?

**Comment by digitalsleuth** [comment]
Nice timing, I was just typing out that the tests were successful. I'm closing this now.
