### ISSUE TITLE
Fresh Install Failure, of Remnux from scratch | Version 2024.44.3

### ISSUE THREAD

**Issue by parr0** [REMnux/remnux-cli#197]
Hi - Upgrade to v2024.44.3 failed, so I decided it was time for a fresh install. Installed Ubuntu 20.04 as done multiple times previously, and kicked off install of Remnux with sudo remnux install, as done multiple times previously. No dice. Please help. 
[saltstack1.log](https://github.com/user-attachments/files/17835182/saltstack1.log)
)

**Comment by lennyzeltser** [comment]
Hmm... I see a new-to-me error in yada-python:

> tarfile.py\", line 2385, in next\n\
>       \    raise ReadError(str(e))\nReadError: invalid header"

@digitalsleuth, do you happen to have any insights into this one?

**Comment by digitalsleuth** [comment]
Sorry, just seeing this now! I'll take a look :)

**Comment by digitalsleuth** [comment]
Hi @parr0 , is there any chance you happen to be behind a proxy?

**Comment by lennyzeltser** [comment]
There was another failure with InetSim that indicated a network issue. But I was able to replicate the yara-python issue locally in a container.

**Comment by digitalsleuth** [comment]
I was just typing that out and a possible cause, but you've already rebuked what I thought it might be :) I'm waiting for my tests to finish right now.

**Comment by digitalsleuth** [comment]
Well, I hate to say it, but it looks like this is specifically a python2 issue, and it appears to only be with python packages that are not wheels (downloading as .tar.gz files). There are no wheels available for these packages, so unfortunately, these packages may have to go in the near future. Let me take a look at the requirements for this and the other packages and I'll see what we can do to get them to Py3 ASAP.

The python 2 packages in question:
- m2crypto
- yara-python
- regex
- shodan

**Comment by parr0** [comment]
> Hi @parr0 , is there any chance you happen to be behind a proxy?

Hi @digitalsleuth - Using VMware Fusion 13.6.1 with a custom network connection but no proxy.

**Comment by parr0** [comment]
Howdy @digitalsleuth Awesome turnaround, great work and thank you! Cleared nearly the whole trail of results:false for me. Please see attached log, Inetsim install still failing. Sorry for the trouble... 

[saltstack_20241126.log](https://github.com/user-attachments/files/17925734/saltstack_20241126.log)

**Comment by digitalsleuth** [comment]
Hi @parr0 , the issue in this run is inetsim, but every time I check it out, there doesn't seem to be an issue. Let me look into this a little more tonight and I'll see what I can find.

**Comment by digitalsleuth** [comment]
Hello again @parr0 , this issue should now be fixed with v2024.48.7, added last night. Give it a shot and let us know how it goes!

**Comment by parr0** [comment]
Woohoo! @digitalsleuth you're a wizard ;) Thank ya Sir. All is well once more.
