### ISSUE TITLE
remnux upgrade error

### ISSUE THREAD

**Issue by s0uIch1** [REMnux/remnux-cli#22]
Hello.
I get an error during remnux upgrade.
Could you please check the error log?

remnux version:v2020.41.2 (Ubuntu 18.04)
remnux@remnux:~$ remnux -v
Version: 1.3.2.1.g8b3ed34

archive_|-remnux-polarproxy-archive_|-/usr/local/polarproxy/_|-extracted:
__run_num__: 653
__sls__: remnux.tools.polarproxy
changes: {}
comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-source'
duration: 0.011
result: false
start_time: '21:54:07.459756'

file_|-/usr/local/polarproxy/PolarProxy_|-/usr/local/polarproxy/PolarProxy_|-managed:
__run_num__: 654
__sls__: remnux.tools.polarproxy
changes: {}
comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-archive'
duration: 0.009
result: false

file_|-remnux-addon-version-file_|-/etc/remnux-version_|-managed:
__run_num__: 675
__sls__: remnux.addon
changes: {}
comment: 'One or more requisite failed: remnux.tools.remnux-tools'
duration: 0.017
result: false
start_time: '21:54:37.497132'

file_|-remnux-polarproxy-source_|-/usr/local/src/remnux/files/PolarProxy_0-8-15-1_linux-x64.tar_|-managed:
__id__: remnux-polarproxy-source
__run_num__: 652
__sls__: remnux.tools.polarproxy
changes: {}
comment: 'Failed to cache https://www.netresec.com/?download=PolarProxy: Error:
  HTTP 599: Connection closed reading https://www.netresec.com/?download=PolarProxy'
duration: 124554.33
name: /usr/local/src/remnux/files/PolarProxy_0-8-15-1_linux-x64.tar
result: false
start_time: '21:52:02.893229'

file_|-remnux-polarproxy-wrapper_|-/usr/local/bin/polarproxy_|-managed:
__run_num__: 655
__sls__: remnux.tools.polarproxy
changes: {}
comment: 'One or more requisite failed: remnux.tools.polarproxy./usr/local/polarproxy/PolarProxy'
duration: 0.008
result: false
start_time: '21:54:07.485585'

test_|-remnux-dedicated_|-remnux-dedicated_|-nop:
__run_num__: 730
__sls__: remnux.dedicated
changes: {}
comment: 'One or more requisite failed: remnux.addon.remnux-addon-version-file'
duration: 0.013
result: false
start_time: '21:54:40.045701'

test_|-remnux-tools_|-remnux-tools_|-nop:
__run_num__: 669
__sls__: remnux.tools
changes: {}
comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-archive,
  remnux.tools.polarproxy.remnux-polarproxy-source, remnux.tools.polarproxy.remnux-polarproxy-wrapper,
  remnux.tools.polarproxy./usr/local/polarproxy/PolarProxy'
duration: 0.011
result: false
start_time: '21:54:14.583773'

**Comment by lennyzeltser** [comment]
Looks like there was an issue with downloading the PolarProxy file from the website that hosts it. We've seen sporadic timeout issues with that site. Please try the operation later today or tomorrow, and it will likely succeed. We're looking into the possibility of hosting the file elsewhere to avoid issues like this in the future.
