### ISSUE TITLE
Install from Scratch fails at wireshark setup

### ISSUE THREAD

**Issue by benmcgarry** [REMnux/remnux-cli#23]
When I try to install the install from scratch setup it always fails after running wireshark.

![image](https://user-images.githubusercontent.com/9434920/106182948-7c66cd00-6197-11eb-8de3-73a04ecba6c2.png)

Ive attatched my [saltstack.log](https://github.com/REMnux/remnux-cli/files/5889484/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @BenMcGarry ! While you do see the error appear after the `Running: wireshark` statement, the error isn't actually related to wireshark. The error only presents after the CLI has finished attempting all activities, and it just so happens that wireshark is the last package to be managed before the CLI finishes its normal tasks.

After reviewing your saltstack.log, there are really only two real concerns: The first is an issue with the installation of python2 and the get-pip command. I've seen this a couple of times over the last couple of days, so this isn't unique to your system. I'm actually looking into the cause of the get-pip error, and will provide an update once I figure out the cause. This appears only to be an issue on Ubuntu Focal; you won't have this issue on Ubuntu Bionic if time is a concern and you need this installed soonest.

The remainder of the errors all fall under one category, disk space. From the looks of it your system/VM ran out of disk space during the installation and, as such, the remainder of the packages could not install. I would recommend perhaps increasing the disk size of your VM by approximately 4-5GB to allow you to complete the install, or try removing unused packages and kernels then try again.

You can stay tuned to this issue for resolution of the python2 error. Once we determine the issue, we'll apply a fix (if possible) and post the results here.

**Comment by benmcgarry** [comment]
Thanks for the info! With disk size what is the minimum size for everything? The plan is to push this image to Azure so ideally I need it to be as small as possible. I started with 15GB on the drive. I can use bionic for the python error :)

**Comment by digitalsleuth** [comment]
For the minimum size, I would probably do the install as 20GB, then once finished delete the unnecessary directories containing the cached files, then the disk space can be reclaimed. Although, if using a cloud environment, you could also try using the [REMnux Distro docker](https://docs.remnux.org/install-distro/remnux-as-a-container).

As for the python2 error, the get-pip script was recently changed to support only python3. However, bootstrap.pypa.io still has a 2.7/get-pip.py script which works. Testing is ongoing to ensure the toolkit builds properly with this change, then I'll submit a PR for the fix.

**Comment by benmcgarry** [comment]
Installs working perfectly on Bionic thank you - so I know which directories contain the cache files?

**Comment by lennyzeltser** [comment]
Thanks, @digitalsleuth for [addressing the get-pip issue](https://github.com/REMnux/salt-states/pull/163)! 

@BenMcGarry, the installation should work now for both Focal and Bionic. To remove cache files, you can do:

```
rm -rf /srv && \
rm -rf /var/cache/salt/* && \
rm -rf /root/.cache/*
```

**Comment by benmcgarry** [comment]
@lennyzeltser - it looks like the v2021.4.4 release has started to trigger the same install failure. [saltstack.log](https://github.com/REMnux/remnux-cli/files/5898998/saltstack.log)

**Comment by lennyzeltser** [comment]
@BenMcGarry, thanks for reporting the issue. In this case, the problem was due to Volatility3 removing the "master" branch tag from their Github repo, which was the branch the REMnux installer was explicitly looking for. I made an adjustment to get around this, so it should be working now.
