### ISSUE TITLE
Install from scratch fails due to expired certificate at https://nowrap.de

### ISSUE THREAD

**Issue by ondrejmokos** [REMnux/remnux-cli#25]
Install from scratch fails due to expired certificate at https://nowrap.de. The certificate expired on the 5th of February 2021. Is there a workaround so that the installation is not aborted?

**Comment by lennyzeltser** [comment]
Thanks for reporting this issue, @ondrejmokos! @digitalsleuth addressed It in a new pull request, so this should be fixed now.
