### ISSUE TITLE
Problems with the install on Ubuntu 20

### ISSUE THREAD

**Issue by fenster1138** [REMnux/remnux-cli#26]
Here is one of the failures....

# [INFO    ] Completed state [curl -o /tmp/get-pip.py https://bootstrap.pypa.io/2.7/get-pip.py] at time 11:02:17.035453 (duration_in_ms=163.342)
# [INFO    ] Running state [python2 /tmp/get-pip.py] at time 11:02:17.044704
# [INFO    ] Executing state cmd.run for [python2 /tmp/get-pip.py]
# [DEBUG   ] Could not LazyLoad cmd.mod_run_check: 'cmd.mod_run_check' is not available.
# [INFO    ] Executing command 'which' in directory '/root'
# [DEBUG   ] retcode: 1
# [DEBUG   ] Last command return code: 1
# [INFO    ] Executing command 'python2' in directory '/root'
# [ERROR   ] Command 'python2' failed with return code: 1
# [ERROR   ] stderr: 
Hi there!

The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:

    https://bootstrap.pypa.io/pip/2.7/get-pip.py

Sorry if this change causes any inconvenience for you!

We don't have a good mechanism to make more gradual changes here, and this
renaming is a part of an effort to make it easier to us to update these
scripts, when there's a pip release. It's also essential for improving how we
handle the `get-pip.py` scripts, when pip drops support for a Python minor
version.

There are no more renames/URL changes planned, and we don't expect that a need
would arise to do this again in the near future.

Thanks for understanding!

- Pradyun, on behalf of the volunteers who maintain pip.

**Comment by lennyzeltser** [comment]
Thanks for reporting this issue, @fenster1138. I fixed the problem, so this should be working now.
