### ISSUE TITLE
Certificate error retrieving mitmproxy

### ISSUE THREAD

**Issue by Shauny-Boi** [REMnux/remnux-cli#27]
Hello - I'm following the guide on https://dfirmadness.com/building-a-dfir-analysis-fort/ which then points me towards your installation page https://docs.remnux.org/install-distro/add-to-existing-system

I reviewed my saltstack log and noticed a lot of the result: failed was due to a missing dependency mitmproxy, so I searched the log for that and located the below lines:

```
[INFO    ] Running state [/usr/local/src/remnux/files/mitmproxy-5.1.1-linux.tar.gz] at time 15:17:24.197905
[INFO    ] Executing state file.managed for [/usr/local/src/remnux/files/mitmproxy-5.1.1-linux.tar.gz]
[DEBUG   ] Requesting URL https://snapshots.mitmproxy.org/5.1.1/mitmproxy-5.1.1-linux.tar.gz using GET method
[DEBUG   ] Using backend: tornado
[WARNING ] SSL Error on 15 ('13.224.179.104', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
[DEBUG   ] Cannot perform 'http.query': https://snapshots.mitmproxy.org/5.1.1/mitmproxy-5.1.1-linux.tar.gz - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
[ERROR   ] Failed to cache https://snapshots.mitmproxy.org/5.1.1/mitmproxy-5.1.1-linux.tar.gz: Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852) reading https://snapshots.mitmproxy.org/5.1.1/mitmproxy-5.1.1-linux.tar.gz
[INFO    ] Completed state [/usr/local/src/remnux/files/mitmproxy-5.1.1-linux.tar.gz] at time 15:17:24.350227 (duration_in_ms=152.322)
[DEBUG   ] Could not LazyLoad archive.mod_watch: 'archive.mod_watch' is not available.
```

I'd assume this is out of your control and the owner of mitmproxy needs to update their certs?

Here's my saltstack in case you'd like to review it further.

[saltstack.log](https://github.com/REMnux/remnux-cli/files/6201050/saltstack.log)

Thank you :)

**Comment by lennyzeltser** [comment]
Thanks for reporting this issue, @Shauny-Boi.

I couldn't reproduce the error in my environment. However, there's no need to use HTTPS to download the file, because the REMnux installer validate the SHA256 hash of the downloaded file anyway. I switched to the HTTP version of the URL to avoid the potential HTTPS issue altogether. If the downloaded file doesn't match the expected hash value, the installation will fail, but at least it won't depend on the SSL certificate anymore.

Also, I used this as an opportunity to retrieve the latest version of mitmproxy.

**Comment by Shauny-Boi** [comment]
Hi Lenny - I now get a hash mismatch - I've tried a couple of times:

[ERROR   ] Specified sha256 checksum for /usr/local/src/remnux/files/mitmproxy-6.0.2-linux.tar.gz (86e96c9a6f50f2863e69dcdfe91c38b4f0844ee1ab0037373689db8aaacb5191) does not match actual checksum (9471db0040e0c896b9eed785d8b127e1ff8c311056f496b33684106993eaae49)

I'm assuming it deletes the file if there's a mismatch? I can't locate the file in /usr/local/src/remnux/files to double check the hash post-installation.

Is there anything I should be doing in between attempts to "clear out" any old files or should the script take care of that automatically? Watching my network it seems to download less on subsequent tries.

Thank you :)

[saltstack.log](https://github.com/REMnux/remnux-cli/files/6201946/saltstack.log)

**Comment by lennyzeltser** [comment]
Very interesting. I do believe the correct SHA256 hash of mitmproxy-6.0.2-linux.tar.gz 86e96c9a6f50f2863e69dcdfe91c38b4f0844ee1ab0037373689db8aaacb5191, which is what the REMnux installer expects. I haven't encountered the issue you're seeing in my environment as well as another environment where I tried to reproduce the problem.

I'm wondering whether something upstream from your REMnux VM is tampering with this file. For example, the antivirus tool on your physical system might be flagging it as malware. It's also possible that some security tool at the network is doing this. Could you try the operation from another network? Another host?

You can retrieve the file yourself directly by downloading it from http://snapshots.mitmproxy.org/6.0.2/mitmproxy-6.0.2-linux.tar.gz and checking the hash yourself from different systems.

**Comment by Shauny-Boi** [comment]
Yep - you guessed it: The corporate firewall/proxy/whatever was interfering with the download.

I had previously tried just using wget to grab the file to desktop to hash it and each time it was a different hash, so I'd been wondering if _maybe_ it was my end for this particular file.

I knew it was 100% my issue when this morning I used my personal phone's shared connection for internet, and saw that the download size was many megabytes - my test downloads were all under 1MB so it was definitely delivering a corrupt partial download.

Sorry to waste your time - hopefully I can be a lesson to someone in the future :)

**Comment by lennyzeltser** [comment]
No worries. Thanks to you, I realized that REMnux was installing an older version of mitmproxy, and now everyone will benefit from the latest version.

**Comment by Shauny-Boi** [comment]
Glad to have helped achieve something :)

Unfortunately I'm still getting a return code not zero.

I've been reviewing the latest log for a few hours now to see if I could figure it out and maybe fix it myself (ha), and all I've really achieved is the amount of open browser tabs growing exponentially.

I _think?_ its nodejs possibly not installing, but I'm not sure - it's certainly not as easy to find and figure out as the last issue was.

For order of operations, do we go by "run_num" as the log seems to not be sequential?

If so, the earliest failure is:
```
  npm_|-box-js_|-box-js_|-installed:
    __run_num__: 559
    changes: {}
    comment: 'State ''npm.installed'' was not found in SLS ''remnux.node-packages.box-js''

      Reason: ''npm'' __virtual__ returned False: ''npm'' binary not found on system
```


[saltstack.log](https://github.com/REMnux/remnux-cli/files/6209161/saltstack.log)

**Comment by lennyzeltser** [comment]
You're right, it seems that SaltStack is unable to find the "npm" binary. Yet, I don't see any indication in the log file that there was an issue with its installation. 

Indeed, run_num displays the order in which the state files were processed and the output captured in the log file is not sequential.

I'm at a loss here, to tell you the truth. @digitalsleuth, perhaps you might have an idea?

**Comment by digitalsleuth** [comment]
Interesting dilemma. Give me a few minutes here to take a look!

**Comment by digitalsleuth** [comment]
@Shauny-Boi Can you run the commands `salt-minion -V` and `salt-call -V` for me, as well as `which npm`, `which node` and paste the output here? I have some theories, but need to check them first.

**Comment by digitalsleuth** [comment]
@Shauny-Boi I suspect that you downloaded the SIFT-Workstation VM from SANS, then attempted to install REMnux in that, am I correct?

**Comment by digitalsleuth** [comment]
I was able to duplicate this issue using the SIFT-Workstation VM. I noticed in your saltstack.log file that the user was /home/sansforensics which is the default user for the SIFT VM. I downloaded the VM and did the following:

- Updated and upgraded
- Downloaded the remnux cli and began the install

The reason for the error is that the SIFT VM comes with nodejs installed (v8.10.0), but NOT npm, as this version of nodejs didn't  install npm as well. When the REMnux nodejs saltstate installs nodejs, it checks to see if it's installed (which technically it is) and doesn't install the latest version over it. 

Thus, since the newest version comes with npm, and the old one doesn't, npm doesn't get installed, and box-js and jstillery fail. We can rectify this by adding the pkg.uptodate or the specific version of nodejs we want to install (from the source repo we provide) to avoid this. Otherwise, we could add npm as a separate state and force the install of it.

Keep in mind, the SIFT-Workstation VM has not yet been updated (still has salt-minion 2018.x.x). It will likely be updated soon, as Erik has mentioned he will update it, but this issue shouldn't happen (and doesn't happen) when using the sift-cli along with the remnux-cli.

I'll work on some solutions today, but in the meantime, manually installing the latest nodejs version (14.x) and re-running the CLI will fix the problem.

**Comment by Shauny-Boi** [comment]
Hi @lennyzeltser and @digitalsleuth,

Thanks for looking into this and apologies for my delay getting back to you. I’m Australian so I was asleep!

You’re correct, it’s the SIFT VM default setup +update/upgrade and then remnux DL.

I won’t be back at work in my lab until Monday morning I’m afraid (about 50 hours away), but I’ll try the above once I get in.

Thanks again!

**Comment by lennyzeltser** [comment]
@Shauny-Boi, @digitalsleuth addressed this issue today. Give it a try, and thanks for reporting the problem!

**Comment by Shauny-Boi** [comment]
Sorry for keeping you waiting - I got to work and instantly found I had training today for a new system.

So once I connected the SIFT VM to the internet and tried to update nodejs, it told me the automated installer was doing something.

I opened the software updates app to see if that would show me what was happening, and it found a bunch of newer versions for things I assume installed either by SIFT or REMnux, and (here's where I might have broken things) I let it update them all.

So then when I went to update nodejs it told me the most recent version (14.16.0-1nodesource1) is already installed.

So I re-ran sudo remnux install --mode=addon and now it's failing right at the start:

```
validating file remnux-salt-states-v2021.12.3.tar.gz

Hashes for remnux-salt-states-v2021.12.3.tar.gz do not match. Expected: bc1a86ded80bc660689bb5b3868f59c79f7f6ec39040393508da7b549a126ef7  /tmp/remnux-salt-states-v2021.12.3.tar.gz
. Actual: 98f9828a5a7a881339d19826aef4c0007ce9acdc6cda5335f568e0f9f4fc2a00  /tmp/remnux-salt-states-v2021.12.3.tar.gz
```

I confirmed it wasn't back on the corporate wifi that was messing with the previous hash comparison.

Have I borked it by letting it update packages? Should I blow it away and start again?

I can't attach the saltstack as it doesn't even get that far! :)

**Comment by lennyzeltser** [comment]
@Shauny-Boi, the installer is expecting the correct hash (`bc1a86ded80bc660689bb5b3868f59c79f7f6ec39040393508da7b549a126ef7`), so the downloaded file (remnux-salt-states-v2021.12.3.tar.gz) is corrupted for some reason. At this point I would consider restarting from scratch to have a more predictable installation environment.

**Comment by Shauny-Boi** [comment]
>> Running: /etc/remnux-version

>> COMPLETED SUCCESSFULLY! Success: 698, Failure: 0

Hooray! Just in time for my Easter leave :)

Thank you again!
