### ISSUE TITLE
The "remnux upgrade" command fails, stating in saltstack.log: ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by lennyzeltser** [REMnux/remnux-cli#28]
On Ubuntu 18.04 (bionic), salt-states v2021.15.2 introduced an error that broke subsequent remnux upgrades. This issue did not effect Ubuntu 20.04 (focal) systems.

On the affected system, a `remnux upgrade` command would with the generic error message:

```
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:568:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

The the bottom of the saltstack.log file that the tool generated under /var/cache/remnux/cli would state:

```
ModuleNotFoundError: No module named 'yaml'
```

If you encountered this issue, run the following command to fix it:

```
apt install --reinstall python3-yaml
```

**Comment by lennyzeltser** [comment]
This has been fixed, but if you downloaded the Ubuntu 18.04 (bionic) OVA or upgraded REMnux during the recent one-week period, you can fix the issue via the `apt` command above.

**Comment by javinotfound** [comment]
Hello,

I'm having the same issue in Ubuntu 20.04. I've installed REMnux from General OVA. I attach you my saltstack.log, because I tried reinstalling python3-yaml without solution. Could you help me?

[saltstack.log](https://github.com/REMnux/remnux-cli/files/6488004/saltstack.log)

Thank you.

**Comment by digitalsleuth** [comment]
Hi @javier-es , It looks like an issue with the python2 implementation of pefile. Taking a look at it now!

**Comment by digitalsleuth** [comment]
Looks like it's being tracked here as well: https://github.com/erocarrera/pefile/issues/318

**Comment by lennyzeltser** [comment]
@javier-es, @digitalsleuth submitted a [temporary fix](https://github.com/REMnux/salt-states/pull/179) to the pefile issue. The REMnux installer/upgrader should now complete without issues.
