### ISSUE TITLE
20.04.2 LTS Fresh install failure (Google Cloud)

### ISSUE THREAD

**Issue by jonathanccfeng** [REMnux/remnux-cli#30]
I'm seeing issues when installing through:
` remnux install --mode=cloud`

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

Log:
[saltstack (1).log](https://github.com/REMnux/remnux-cli/files/6511941/saltstack.1.log)

**Comment by lennyzeltser** [comment]
Thanks for reporting this issue. I thought I had corrected it a few weeks ago, but looks like it is persisting in some configurations. 

The problem is with the installation of the flare-capa tool and its dependency vivisect. Both depend on a PIP module pyasn1-modules, but for some reason its installation fails and generates the error:

```
Cannot uninstall 'pyasn1-modules'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

And for some reason the workaround I created for this isn't working on your system. I'm wondering, if you run the following command, does it work and, if not, what error does it produce?

```
sudo pip3 install vivisect
```
In case you're wondering the other REMnux tools were installed correctly on your system. The issue is just with flare-capa.

**Comment by jonathanccfeng** [comment]
failed

**sudo pip3 install vivisect**
WARNING: Keyring is skipped due to an exception: entry_points() got an unexpected keyword argument 'group'
Collecting vivisect
  Using cached vivisect-1.0.3-py3-none-any.whl (4.1 MB)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.5 in /usr/local/lib/python3.8/dist-packages (from vivisect) (0.4.5)
Collecting msgpack<1.1.0,>=1.0.0
  Using cached msgpack-1.0.2-cp38-cp38-manylinux1_x86_64.whl (302 kB)
Collecting pyasn1-modules<0.3.0,>=0.2.4
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting cxxfilt<0.3.0,>=0.2.1
  Using cached cxxfilt-0.2.2-py2.py3-none-any.whl (3.9 kB)
Requirement already satisfied: pycparser>=2.20 in /usr/local/lib/python3.8/dist-packages (from vivisect) (2.20)
Collecting pyasn1<0.5.0,>=0.4.5
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Installing collected packages: pyasn1, pyasn1-modules, msgpack, cxxfilt, vivisect
  Attempting uninstall: pyasn1
    Found existing installation: pyasn1 0.4.5
    Uninstalling pyasn1-0.4.5:
      Successfully uninstalled pyasn1-0.4.5
  Attempting uninstall: pyasn1-modules
    Found existing installation: pyasn1-modules 0.2.1
ERROR: Cannot uninstall 'pyasn1-modules'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by lennyzeltser** [comment]
Could you please run `remnux upgrade`? I made a couple of changes that may have fixed the issue.

**Comment by jonathanccfeng** [comment]
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

[saltstack (2).log](https://github.com/REMnux/remnux-cli/files/6512346/saltstack.2.log)

**Comment by lennyzeltser** [comment]
Hmmm, looks like my changes didn't fix the issue, as the same problem persists. Not sure what's going on, and I'm unable to reproduce the issue in my environment.

Would you be able to share the output of this command, please?

```
ls /usr/lib/python3/dist-packages/PyYAML-*.egg-info
```

And also:

```
pip3 list|grep YAML
```

**Comment by lennyzeltser** [comment]
@jonathanccfeng, I made another couple of tweaks in an attempt to fix the issue. Could you please give `remnux upgrade` another try?

**Comment by jonathanccfeng** [comment]
@lennyzeltser i think running the command somehow blocked ssh. I can't log into the cloud server now. I know blocking SSH is one of the functionalities of remnux, but i made sure to use the 'cloud' flag.

**Comment by lennyzeltser** [comment]
Sorry for the trouble, @jonathanccfeng!

@digitalsleuth has been looking at the solution to the vivisect and capa issue you reported, and believes he found a way to address it. We should have likely fix available today or tomorrow.

**Comment by digitalsleuth** [comment]
Hi @jonathanccfeng, the pull request has been submitted [here](https://github.com/REMnux/salt-states/pull/180) which addresses this issue. A release for this is coming shortly. In the meantime, if you wish to fix the issue with your existing install prior to the release, you can run the following:

`sudo apt-get remove python3-pyasn1 python3-pyasn1-modules`

**Comment by lennyzeltser** [comment]
Release v2021.20.6 now includes @digitalsleuth's fix, which I believe addresses the original issue.
