### ISSUE TITLE
Ubuntu 20.04 AWS Installation Fails

### ISSUE THREAD

**Issue by ErikHarmon** [REMnux/remnux-cli#31]
Region: us-east-2
Ubuntu AMI: ami-03b6c8bd55e00d5ed
Fresh install

lsb_release -a
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

  sudo remnux install --mode=cloud

fails here:
```
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

My security group outbound is unrestricted and I have 80gb of space. I tried three separate times and it failed in the same place. I also tried upgrading after the failure and it didn't solve the problem. I had trouble solving the problem myself so I came here. I am available to try anything to get it working. I have attached my log.

[saltstack.log](https://github.com/REMnux/remnux-cli/files/6517239/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @ErikHarmon, this issue appears to be similar in nature to #30 , where pyasn1-modules seems to be causing an issue. Is there any chance you ran this install yesterday, or the day prior? If so, then the steps in #30 may actually help fix the issue.

**Comment by ErikHarmon** [comment]
I tried last night and just a few minutes ago. I will peruse #30 and see if it helps.

**Comment by ErikHarmon** [comment]
I tried upgrade again and it failed in the same place, unfortunately. Here is the output you asked for in the other issue, however.

```
$ ls /usr/lib/python3/dist-packages/PyYAML-*.egg-info
ls: cannot access '/usr/lib/python3/dist-packages/PyYAML-*.egg-info': No such file or directory
```
and
```
$ pip3 list|grep YAML
PyYAML                 5.4.
```

**Comment by digitalsleuth** [comment]
Any chance you can tell me what type of AWS image you're using? I'd like to try to duplicate the issue to see if it might have anything to do with the image itself.

**Comment by ErikHarmon** [comment]
AMI is: ami-03b6c8bd55e00d5ed
AMI Name: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210518
AMI Description: Canonical, Ubuntu, 20.04 LTS, amd64 focal image build on 2021-05-18

so, HVM virtualization and was built relatively recently. I have tried the installation before and after doing a dist-upgrade

I have not tried another region because I need it in this region basically.

**Comment by digitalsleuth** [comment]
Looks like in the AMI images, python3-pyasn1 and python3-pyasn1-modules are both installed via apt and can't be 'removed' because they weren't installed using pip. These versions don't match the requirement of capa/vivisect, thus causing the error. I believe we can modify the state to check for and remove those two APT packages, then it should work.

I'll build it and run some tests, then get back to you.

**Comment by digitalsleuth** [comment]
Hi @ErikHarmon , the pull request has been submitted [here](https://github.com/REMnux/salt-states/pull/180) which addresses this issue. A release for this is coming shortly. In the meantime, if you wish to fix the issue with your existing install prior to the release, you can run the following:

`sudo apt-get remove python3-pyasn1 python3-pyasn1-modules`

**Comment by ErikHarmon** [comment]
It worked, thank you! I will note that I had to install from scratch, but that was not a problem.

**Comment by muhtyo1102** [comment]
@ErikHarmon 
What EC2 instance type did you choose for REMnux ? t2.micro or t2.small or t2.medium or t2.large ?

**Comment by digitalsleuth** [comment]
@muhtyo1102 The full installation size of REMnux is between 5-7GB, depending on requirements and versions which may be installed during the timeframe you plan to install it.

With that, you should probably consider the size of the data you will want to routinely interact with inside your instance, and the processing you will do. The T2 instances are flexible for vCPU and memory, but use EBS-Only storage so there's limited flexibility balanced with cost there. If you're looking to analyze small subsets of data, but high-processing T2 is great, and you should be able to compare here: https://aws.amazon.com/ec2/instance-types/

If your plan is large amounts of data, then you can use that comparison tool to give you an idea of what would be a better balance of storage and cost.

Either way, REMnux should install easily on any of those T2 instances, but the ultimate determining factor for your choice will be based on what types of activities you plan on doing with the instance. For average use, I would say a medium or large should be more than enough.

**Comment by muhtyo1102** [comment]
@ErikHarmon 
Thank you for your reply. I appreciate you.
