### ISSUE TITLE
Intalling error on Ubuntu 20.04.2 TLS

### ISSUE THREAD

**Issue by msaltini** [REMnux/remnux-cli#32]
I'm seeing issues when installing through:
sudo remnux install

Distributor ID: Ubuntu
Description: Ubuntu 20.04.2 LTS
Release: 20.04
Codename: focal
[saltstack.log](https://github.com/REMnux/remnux-cli/files/6555719/saltstack.log)

**Comment by lennyzeltser** [comment]
Looks like an issue installing ViperMonkey. We'll look into it. The other tools installed successfully, though.

**Comment by lennyzeltser** [comment]
Fixed by @digitalsleuth in https://github.com/REMnux/salt-states/pull/183
