### ISSUE TITLE
Remnux (focal) upgrade problem couldnt solve in Vmware workstation pro 16

### ISSUE THREAD

**Issue by aar789** [REMnux/remnux-cli#34]
> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:568:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
[saltstack.log](https://github.com/REMnux/remnux-cli/files/6593698/saltstack.log)

**Comment by lennyzeltser** [comment]
Thanks for reporting this issue, @aar789. Looks like the problem was too to the recent revision to oletools. The other tools installed correctly. I adjusted the configuration to address it. Please run `remnux upgrade` to incorporate the fix into your environment.
