### ISSUE TITLE
Remnux will not install via CLI on Ubuntu Focal 20.

### ISSUE THREAD

**Issue by lagro05** [REMnux/remnux-cli#37]
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by lennyzeltser** [comment]
Thanks for reporting the issue, @lagro05!

This output alone just says there was a problem, and doesn't provide any context that would allow me to troubleshoot. 

What did you observe or experience prior to the error?

Was there a log file generated, perhaps at `/var/cache/remnux/cli/v2021.29.4/saltstack.log` or in another directory under `/var/cache/remnux/cli`? If so, please share it.

**Comment by lagro05** [comment]
Hi Lenny,

Here is what happened.

I formatted a hard so I can install a clean Ubuntu 20.04 Focal Desktop
version instead of the mini as prescribed in the website. I downloaded all
the updates of Ubuntu. I then followed the instructions on installing
Remnux using CLI. After I got the error, I re-installed the script again,
rebooted and when I run Remnux, it says it is not installed.

I am not writing this on a Linux box so if you think you need the logs to
troubleshoot, I will send them on Github tomorrow.

Thanks,

Delfino

**Comment by lennyzeltser** [comment]
Yes, please share the log file when you get the chance.

**Comment by lagro05** [comment]
Lenny,

Attached are two files {B ,C} I grep per your website instructions on how
to check for errors. The saltstack log is 4.7M.

I hope this helps.

Del

**Comment by lennyzeltser** [comment]
Sorry, I cannot se the attachment. You you confirm that you included it?
