### ISSUE TITLE
Fresh install from scratch fails 

### ISSUE THREAD

**Issue by xor-al-ex** [REMnux/remnux-cli#39]
Hi,
I've been trying for the last couple of days to make the installation of REMnux on a new Ubuntu system work. I've tried both ISO from Ubuntu and the mini.iso from the wiki, but it fails the same place. I've tried to edit DNS, bypass checks and update system, to no avail. 

[remnux_install_output.txt](https://github.com/REMnux/remnux-cli/files/6922322/remnux_install_output.txt)
[saltstack.log](https://github.com/REMnux/remnux-cli/files/6922323/saltstack.log)

Thank you for your great work!

**Comment by lennyzeltser** [comment]
@xor-al-ex, it looks like there was a network error while installing one of the Perl libraries:

```
stderr: 'read failed: Connection reset by peer at /usr/share/perl5/LWP/Protocol/http.pm
...
comment: Command "cpan install Archive::Zip" run
```
Try installing it yourself by hand by running this command:
```
sudo cpan install Archive::Zip
```

You can run that command after installing REMnux, and if that works, run `remnux update` to finish installing the missing tools that depend on that library.

Everything else appears to have installed fine, so even if you cannot get this dependency to work, just a handful of tools will be unavailable, and you can use REMnux normally.

**Comment by xor-al-ex** [comment]
Thank you for your quick answer. Since the install tool didn't recognize that the tools had been executed before, I thought maybe the installation were too faulty. :) After some quick testing it seems that my most used tools are installed. Guess I'll try again later to get a complete install. 

Thank you for your time.
