### ISSUE TITLE
Unable to install Remnux v2021.36.1 on WSL2 Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by cgisecurity** [REMnux/remnux-cli#42]
I have a fresh install of Ubuntu 20.04, completely up-to-date, using WSL 2. I have been trying to install Remnux for a couple of days with no success. I have installed the distro, updated, and rebooted the entire system before trying the Remnux install. Attached is the saltstack.log file, and this screenshot is from the last install attempt I just completed. After it failed, I tried to run remnux update and received this:
![image](https://user-images.githubusercontent.com/40150040/132620431-2aecd73f-723c-4cd9-a45c-a3de3a3e4113.png)
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7133299/saltstack.log)

**Comment by lennyzeltser** [comment]
Thanks for reporting this issue, @cgisecurity!

Looks like there was a problem installing ViperMonkey. Here's the relevant excerpt from saltstack.log:

```
  /tmp/pip-req-build-XcHg7l\nERROR: Package 'unidecode' requires a different Python:
  2.7.18 not in '>=3.5'"
duration: 4509.634
name: git+https://github.com/decalage2/ViperMonkey.git
result: false
```

Everything else seemed to have installed fine, so you can use REMnux on your system without ViperMonkey for now until we've addressed this dependency issue.

**Comment by lennyzeltser** [comment]
Thanks, @digitalsleuth, for fixing this issue!

@cgisecurity, you can run the `remnux upgrade` command to finalize your REMnux installation by installing VIperMonkey.
