### ISSUE TITLE
WSL 2 & Ubuntu-20.04 Remnux-cli install failing

### ISSUE THREAD

**Issue by cgisecurity** [REMnux/remnux-cli#43]
Lenny,

You just closed issue #42 for me, but when I attempted to run "sudo remnux upgrade --mode=addon" to complete the installation, it still failed. I reset the distro, and attempted to reinstall from the start and it still failed. Attached is the saltstack.log file.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7147116/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @cgisecurity , it looks like the current version of pyinstxtractor was updated yesterday. This then caused the hash value we validate to change, throwing the new error. All of the other tools installed correctly, so you can continue to use those.

I'll update the hash value for that soonest and submit the PR shortly.

**Comment by lennyzeltser** [comment]
Should be good now. Thanks for the fix, @digitalsleuth!
