### ISSUE TITLE
remnux upgrade fail. Error: Update returned exit code not zero. Upgrade to v2021.36.3.

### ISSUE THREAD

**Issue by shagun-jain-security-ai** [REMnux/remnux-cli#44]
Ran multiple times "remnux upgrade" and failing with same error.
Already done with successful sudo apt upgrade and sudo apt update.
Rebooted system. Hyper-v is off.
Seems to be some issue with github resources as checked from saltstack.log (attached)
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7147587/saltstack.log)

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:568:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by digitalsleuth** [comment]
Hi @shagunjain123 , your saltstack log shows you're having the same issue as described in Issue [#43](https://github.com/REMnux/remnux-cli/issues/43). This should be remedied shortly!

**Comment by lennyzeltser** [comment]
Thanks, @digitalsleuth, for addressing this issue.

@shagunjain123, it should work now, please try `remnux upgrade` again.

**Comment by gebhard73** [comment]
fix has worked for me, tnx
