### ISSUE TITLE
Error with InspIRCd

### ISSUE THREAD

**Issue by germanh2** [REMnux/remnux-cli#45]
Hello, 

I have tried stopping and starting the inspircd service, however, that is not working. Not sure if this is the actual cause for the error I am receiving, however, that is what was found in the saltstack.log. Please assist. Thank you!

>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

# [DEBUG   ] stdout: * inspircd.service - InspIRCd - Internet Relay Chat Daemon
     Loaded: loaded (/lib/systemd/system/inspircd.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2021-09-20 17:12:39 EDT; 53min ago

**Comment by digitalsleuth** [comment]
Good morning @germanh2 , Any chance you can provide your saltstack.log file so we can examine the cause of the installation error? Additionally, I'll take a look at the inspircd service to see what might be happening with that specifically.

**Comment by germanh2** [comment]
Good morning! Thank you for responding. I’m not sure what changed but it works fine now and was able to run install, update and upgrade commands without issues. Power of the reboot.
