### ISSUE TITLE
remnux upgrade/update fails

### ISSUE THREAD

**Issue by didelphodon** [REMnux/remnux-cli#46]
Hi,

I just wanted to eventually update/upgrade my REMnux VM to the latest stable throw, but ran into that familiar looking update-error that I've seen a couple of times here. I have to admit that my installed version is a bit old (v2020.51.8) so maybe that's the reason why :-(

Help is very much appreciated! :-)

The saltstack.log is attached to this post.

[saltstack.log](https://github.com/REMnux/remnux-cli/files/7237054/saltstack.log)

Thx in advance!

Christian

**Comment by lennyzeltser** [comment]
Christian, did you run the `remnux upgrade` command?

If you ran `remnux update`, please run `remnux upgrade` instead.

**Comment by didelphodon** [comment]
I ran both of them. Both had the same result.

Lenny Zeltser ***@***.***> schrieb am Mo. 27. Sep. 2021 um
16:50:

**Comment by lennyzeltser** [comment]
Hmm... I'm wondering whether the saltstack.log you uploaded had the artifacts from the `update` command, which made it hard for me to diagnose the issue.

So I can help troubleshoot, could you please delete that saltstack.log file from your REMnux system, run `remnux upgrade` and then share the saltstack.log file again?

To clarify, in almost all cases, there is no need to run `remnux update`.

**Comment by didelphodon** [comment]
Gave another try with the upgrade command and now the whole process was successful. No idea why it worked out now and I swear I tried various commands including options and the like before. Maybe cleaning up caches and rebooting had a positive impact. Thx for your help Lenny, seems your presence is enough to make REMnux behave :-)

**Comment by lennyzeltser** [comment]
:-)
