### ISSUE TITLE
remnux update is stuck (?)

### ISSUE THREAD

**Issue by TrueTheos** [REMnux/remnux-cli#48]
Hello there,

I executed "remnux update" command and everything was going good up until this point.
![Przechwytywanie](https://user-images.githubusercontent.com/26145867/135722683-eb1f1c9c-4ea2-4aa3-93c5-1358a3918e5a.PNG)

I waited more than one hour now and I don't know if it is stuck or installation just finished?

**Comment by digitalsleuth** [comment]
Hi @Loiuy123 , when you were running the command, did you append an ampersand `&` to the end of the command? Also, this might sound like a silly question, but have you tried hitting enter or `CTRL-C` to end the update?

To assist in finding the cause of this problem, could you also provide your saltstack.log file?
Thanks!

**Comment by TrueTheos** [comment]
Hey, I did not try to hit CTRL-C because I wasn't sure if it wouldn't "break" updating process. I did it now and it seems like everything is working :)
