### ISSUE TITLE
Cannot install on Ubuntu 20.04

### ISSUE THREAD

**Issue by eyMiko** [REMnux/remnux-cli#49]
This is the error that I am getting.

request to https://api.github.com/repos/REMnux/salt-states/releases failed, reason: connect ETIMEDOUT 140.82.114.6:443
HttpError: request to https://api.github.com/repos/REMnux/salt-states/releases failed, reason: connect ETIMEDOUT 140.82.114.6:443
    at /snapshot/remnux-cli/node_modules/@octokit/request/dist-node/index.js:107:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getValidReleases (/snapshot/remnux-cli/remnux-cli.js:293:18)
    at async run (/snapshot/remnux-cli/remnux-cli.js:762:21)
    at async main (/snapshot/remnux-cli/remnux-cli.js:778:5)

**Comment by digitalsleuth** [comment]
Hi @eyMiko , it looks like you have either a network connection problem, or you likely might be behind a proxy. If you believe you are behind a proxy, take a look at the docs [here](https://docs.remnux.org/tips/remnux-config-tips#behind-proxy) and this might help the install succeed.
