### ISSUE TITLE
i cant view the Remnux ethO Ip address and cant see /dev in remnux

### ISSUE THREAD

**Issue by koleademola** [REMnux/remnux-cli#51]
Good day Admin,

After installing Remnux on my virtualbox, i cant see the Ip address of the ethO. Also, the remnux is not pinging google.com.

Also, i cant see /dev folder through the cli.

Kindly assist as i am setting up lab.

Thanks

**Comment by digitalsleuth** [comment]
Good day @koleademola, can you possibly provide your saltstack.log file, and let us know what version of Ubuntu you used to install REMnux, including any commands you provided with the CLI?

**Comment by lennyzeltser** [comment]
@koleademola, also, please take a look at the instructions on [the REMnux documentation page](https://docs.remnux.org/install-distro/get-virtual-appliance#virtualbox) that start with "If your REMnux virtual machine is unable to communicate over the network..." Let us know if those steps end up working for you.
