### ISSUE TITLE
Install fails on remnux-perl-packages

### ISSUE THREAD

**Issue by msaltini** [REMnux/remnux-cli#53]
I am trying to instal remnux as an addon to my ubuntu 20.04 vm. I've tried both remnux install --mode=addon and remnux upgrade --mode=addon. Both commands fail at remnux-perl-packages

Distributor ID: Ubuntu
Description: Ubuntu 20.04.2 LTS
Release: 20.04
Codename: focal

[saltstack.log](https://github.com/REMnux/remnux-cli/files/7510898/saltstack.log)

**Comment by Dleau** [comment]
Same issue here

**Comment by lennyzeltser** [comment]
Thanks for reporting this, @msaltini and @Dleau. The issue was due to PyInstaller Extractor changing. I updated the distro to reflect the new version.
