### ISSUE TITLE
Installing Remnux on new system

### ISSUE THREAD

**Issue by pyhoff** [REMnux/remnux-cli#57]
Welp https://www.inetsim.org/packages.html their PGP key expired today, guess when I am trying to install it, welp today of course.

pub   4096R/6881B9A7E9F601C8 2016-08-12 [expires: 2021-12-31]
      Key fingerprint = 5ADF 5239 D9AA AD3C 4550  9491 6881 B9A7 E9F6 01C8
uid                          INetSim Archive Signing Key (2016-2021) <inetsim@inetsim.org>

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFetrjQBEACz15ALfIy71+4+s5uXNtl+MB5wA5E8TxtpqgMq7XxRtTyJ6pgg
NHDYXodKZYLhyS01QA2hDT1n5jSR+M39I47bXjFKbhdSrT5d01SmQ3o+t5w8AgKj
Je6Gq96s4/ryut7Nq/CJAsYNsNLiOJ+hHOtEFJ7VHg8KjFEtxvwCYnr9Y7rkPrd0
Dqi/22dBmaBceZC90U60dVrmG+rFzg/9kylaEL6Wl3E3wwS9P4/tjIKRrZopsVLi
4fYphaaUj4RV7u2lMgujrIjJ+IorqIqP8F+WALXQsV3I2APoxyd+MMG+HyamQth6
51qBDUCnXuEmbbH8+RNh69eeBF5jVTMHRcKkJ/RIWT91GFDJ1wTO20algIJ34Fqg
GWGPSU0DPiYSAikMzLHc63BvnAVscHUxexPeDx4CahNsSsgiG4v/oR2lqYTZNjzw
cLjrdt+PvKEhQUOd7SFltKW46ZUdsFW/0LSKoQM9axocK2GvyMxzgubyQ8StmKpb
KuEbMBPOIyJa61CZ4J02IbRDw3w300/mllBvoKvGKtFuKDmSuTtk/Mf/PGRFCgB4
VOZYZJ2aIdkFTMj4c/KbINET4Wr3Bh3lA/V/ciSZqTJheFN5yg2+G5ScJBVzQVJ9
dh/1AwT+Av2lf8CRlT3GZ6m1mpihUDvjguIpWi1IwDA2InKJE+TTLTM8hQARAQAB
tD1JTmV0U2ltIEFyY2hpdmUgU2lnbmluZyBLZXkgKDIwMTYtMjAyMSkgPGluZXRz
aW1AaW5ldHNpbS5vcmc+iQI9BBMBCAAnBQJXra40AhsDBQkKITaABQsJCAcDBRUK
CQgLBRYCAwEAAh4BAheAAAoJEGiBuafp9gHIJewP/Avb+dBELIIBhxxSDUPBBQNn
oYetyGAkPsUmeQMwZYVvBUWtYlJuZEd20AmyVS0chtm+kwiqT9aSMgFVvptOZFs5
KNwlEFkcZ7fatKXHM9JL7q1d7FxO2u4S/lfLPdPZgMiDLugU4Urzduo0ifhsyvMl
5XnYM4MZK19lSvGwFbK+pj5esdU3RMQFBVO/cgvSZAR6gRZxzFl5TpVjs0tyhCFU
1pg69m/D5YkTsC2h3mGfBnAtpEe8d6SWlm2Z1FGIdtW5twiKKxkPP4sL6EBrSmnS
ivIoOWYk2U9FbAsorByquF8AMFA9JiVYAnLbGnI2tiZC+mE65I1HcYl1RQ6DF/Xv
LNOxnwgT0jmhoqvTGXw4QHed8tlM046r9n07nBlWaq8TQ+b6JEfmA9RV5lSPCbHA
3W3gh6nAYxKnmLD6Nia5fMRmr2Y+EKVoncXBGL0Y/yr+GGj++gMKCebkFfhjP5Q6
zm9hnRsyYgs5Ekdz7fIGXMLtPlLT1hxXReV8aQn6xBBwVG5iKV6nLxRMEJfxWnzW
llNnJ8fm7/j0YG27vwYXVAxAqWveMFmkjubiodPnb4T//m30+Sb1ABnyxspdP9fB
yX6XGQtH7HqG22j1urgz/VPbV9lG+OvRiWCzVNjAx0u+yuyonzSGsVOu/hmjDqpz
jcQjzLg40+EQ4qAVgMqAiEYEExEIAAYFAletsIAACgkQayPseWtVEbGYsgCdH+HY
SWl/3R2DfbgPprEWXwSzoEMAoJilI9wYBANX96mfIQQdr2Z1Egj0iQIcBBMBCAAG
BQJXrbFSAAoJEODOMvseEkbAN0YP/iEBA0eGIU7fe5Iv/QaNl3YPUHFEi9pADwwi
Y++nOQbBqv9pnvCVY341kKEfXXeySNHVAMCum5FgP8VoFPNUvR9vYycjv6ENAs0f
yr+rWOokXf4eXM9KrnrF1vgGul9MGGz26iZ+jCHgypH+HicbJ1Ee812IwB2dB/3o
oqNZMEtGGn6AeHWbGWZ1ZPbeuGFCIGx581Bm7lS03lqTHHpPPUoJRhyKozxN1ZKR
YPZyyH7ohrZWfNBkt3h9aaYFH/oQwVPev8y8PFoxFf5UweUzy+Jm5elgT5xVd5Ti
kf3i+ifGDKrHTOYgcuf3BWiEgdzMX9twuHol8PoTFMnPfzy82PETrmP97hTCRjzm
TBwH7akPAgVZubSlJnomoTmHBwpVZwZPeLu6ZowvcEDCtHJu+IeOq32y7wdqOkPl
3u0YvS+Wr05WqbSjqxLBLRg9QWMYnDDudYZPdQgKo2H9cOhBVBGII60cbrEIM1m3
LznXzah7x4rjlnQb0BFDUHRavtaKnQyvkYpubKEUCR1C2TkahcwgLJ7Pg5BrAUyI
HM2u7jkg2LUTID5RlrxCRDuF5exO/Ou5BBEez3Sa/6M0RkaTKt1njL2vDsXIgfig
RvdruXnOHICjH0lilboxNXKC4PbpagwgrK/tcCrpGXH4tdwRrBCSPt8+IsuMctse
jrj2rUDliQIcBBMBCAAGBQJafVt5AAoJEOMENImrC0oD0LMP+gLZsGvKR9oA5GK1
TG7XnX18KZxzHAw4BqMTfEnnJ2cAO6U3MoAYuR4pHQRYf4ptSHhK/442FcgT5cTK
NBjgSanOALtO0vpNfpRPpMnjKsobp/1s+vGRs3HxJ758HsW89o7ULZS94WhuKXZJ
lPe+e57/VI9J/kkvwkx/lV2el4lV1U66F6dLaRh3N8aJv41FzUPTwRSjJvMgW8tc
HQ6Rr7I3VJIUcKdwcpCAib4VE2CzhVaf+j5oGcH54eIF0qjIulASWB5RQIKFCu7T
EDRPPM0+gf3bhOnYKusvl3UYvCmB68/V8wL4dTQNnDSotHJAvl8Ku56x9zB0e2cA
L2pmfx5M3EcGxuvB1e/8exa8nsVfDqYe8n+LhelT2pFmFjEWDOmCCswJ7rq7JB9u
iiGObqnBzR93qfoZkgm5ukvaLoDpcOZdqZsnImXDUv4u5KA68LAe36IotnKhicqn
Qh1yBy1//v6XvzacIxsHpDiyQSudya8dieGPv52BDn9U4h0OE5s4qPr91zFLyddS
iIOsG4hfyCgpqM6HPqiFW9X3mL8aWyxtkproAKSenfJjx0ufbyV3FQKHcagRdaMw
ZsC/x8i4jels4vfCEe8mlSWrtlhcbYo7+btI/F11QZ9vFyl2ZORh/Rjiw/cM4NhO
wVXRwyFd+qXHIdEkgFLjOYus0hcj
=MuaY
-----END PGP PUBLIC KEY BLOCK-----

**Comment by pyhoff** [comment]
Well apart from this issue, I found that I had a source repo issue with saltstack for some reason. Once the pgp key was updated, and apt saltstack.list was corrected everything installed properly.

**Comment by lennyzeltser** [comment]
@pyhoff, thanks for reporting that the PGP key for INetSim expired. I updated REMnux to use their new key.
