### ISSUE TITLE
Errors upgrading to saltstack v2022.1.2 

### ISSUE THREAD

**Issue by Wonny12** [REMnux/remnux-cli#58]
Hello I am new into the github and would like to ask this question. Below is the output of saltstack.log. I think there is an issue with polar proxy but I am not sure how to deal with this issue. Please help me, thank you for reading.

$ cat /var/cache/remnux/cli/v2022.1.2/saltstack.log | grep -a -i -C 5 'result: false'
    __run_num__: 724
    __sls__: remnux.tools.polarproxy
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-source'
    duration: 0.007
    result: false
    start_time: '14:31:45.399259'
  archive_|-remnux-python3-packages-stpyv8-archive_|-/usr/local/src/remnux/_|-extracted:
    __id__: remnux-python3-packages-stpyv8-archive
    __run_num__: 318
    __sls__: remnux.python3-packages.stpyv8
--
    __run_num__: 725
    __sls__: remnux.tools.polarproxy
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-archive'
    duration: 0.007
    result: false
    start_time: '14:31:45.407196'
  file_|-procdot-link_|-/usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0_|-symlink:
    __id__: procdot-link
    __run_num__: 157
    __sls__: remnux.packages.procdot
--
    __run_num__: 753
    __sls__: remnux.addon
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.remnux-tools'
    duration: 0.007
    result: false
    start_time: '14:32:08.511635'
  file_|-remnux-config-android-project-creator-permissions_|-/opt/AndroidProjectCreator/library_|-directory:
    __id__: remnux-config-android-project-creator-permissions
    __run_num__: 655
    __sls__: remnux.config.android-project-creator
--
    comment: Specified sha256 checksum for /usr/local/src/remnux/files/PolarProxy_0-8-16_linux-x64.tar
      (9c0bef3bff91ef66f70daf91a423829104728f99d0a2a52bbc13a5c1d7ed60b8) does not
      match actual checksum (7018ed331bed230fc1c3cf6accece2e925968361a7dcc8fe8725890636b57a21)
    duration: 111552.869
    name: /usr/local/src/remnux/files/PolarProxy_0-8-16_linux-x64.tar
    result: false
    start_time: '14:29:53.837933'
  file_|-remnux-polarproxy-wrapper_|-/usr/local/bin/polarproxy_|-managed:
    __run_num__: 726
    __sls__: remnux.tools.polarproxy
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy./usr/local/polarproxy/PolarProxy'
    duration: 0.008
    result: false
    start_time: '14:31:45.415616'
  file_|-remnux-pyinstaller-shebang_|-/usr/local/bin/pyinstxtractor.py_|-prepend:
    __id__: remnux-pyinstaller-shebang
    __run_num__: 457
    __sls__: remnux.scripts.pyinstaller-extractor
--
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-archive,
      remnux.tools.polarproxy./usr/local/polarproxy/PolarProxy, remnux.tools.polarproxy.remnux-polarproxy-source,
      remnux.tools.polarproxy.remnux-polarproxy-wrapper'
    duration: 0.008
    result: false
    start_time: '14:31:50.419822'
  user_|-remnux-user-sansforensics_|-sansforensics_|-present:
    __id__: remnux-user-sansforensics
    __run_num__: 360
    __sls__: remnux.config.user

**Comment by digitalsleuth** [comment]
Evening @Wonny12 , I've just submitted a PR for this and, once merged, should fix your issue. Everything else in your toolkit should have installed properly without an issue. Cheers!

**Comment by lennyzeltser** [comment]
Thanks for the quick fix, @digitalsleuth. I just incorporated it into the new release. @Wonny12, please give it a try.

**Comment by Wonny12** [comment]
Thank you @digitalsleuth and @lennyzeltser so much for your help :)
