### ISSUE TITLE
Errors Installing Remnux

### ISSUE THREAD

**Issue by r1leyfreeman** [REMnux/remnux-cli#59]
Looks like SSView.zip file has been updated and causes the install to fail.

    comment: Specified sha256 checksum for /usr/local/src/remnux/files/SSView.zip
      (59b8894889d39e7299d139010cd87c23031667ffa29c543679cd0ba953432d7f) does not
      match actual checksum (8ceb003a88ed985b772accb81551577ce363f268fe14ef23ec47f912b1abe111)
    duration: 4752.267
    name: /usr/local/src/remnux/files/SSView.zip
    result: false
    start_time: '12:53:10.842124'
  file_|-remnux-tools-ssview-wrapper_|-/usr/local/bin/ssview_|-managed:

**Comment by lennyzeltser** [comment]
Fixed. Thanks for reporting this issue, @r1leyfreeman!
