### ISSUE TITLE
Distro Installer for ESX 6.5?

### ISSUE THREAD

**Issue by romanf** [REMnux/remnux-cli#6]
Hi Everybody,
I'm trying to install Remnux v7 distro on a VM on a ESX 6.5. But that doesn't work because the distro installer requires feature-level 14 which is only avaialbe in ESX 6.7. Unfortunately we can't install 6.7 on our hardware as it's too old. 

Any chance to get a distro installer that only requires feature-level 13?

Thanks
Roman

**Comment by lennyzeltser** [comment]
I'll keep an eye out for the frequency of this request when building the OVA in the future.

For now, your best approach might be for your to build your own REMnux virtual machine by following the [Install REMnux from Scratch](https://docs.remnux.org/install-distro/install-from-scratch) instructions.

Alternatively, you can import the REMnux pre-built virtual appliance into VMware Workstation Pro or VMware Fusion Pro, then export it according to your hardware requirements. It's also possible that the [VMware ovftool](https://code.vmware.com/web/tool/4.4.0/ovf) can perform the conversion, but I'm not certain.

**Comment by romanf** [comment]
The tipp with the VMWare Workstation Pro was perfect: I was able to clone the Remnux v7 OVA with a lower feature-level and then import it into my ESXi 6.5. 

Cool! Thanks for your help, apreciate it very much! 👍
