### ISSUE TITLE
REMnux addon mode install fails on Xubuntu 20.04

### ISSUE THREAD

**Issue by seanthegeek** [REMnux/remnux-cli#61]
I really don't like GNOME  3, so I'm trying to install REMnux as an addon to a fresh installation of Xubuntu 20.04, but ran into some errors.

```bash
sudo remnux install --mode=addon
```
```text
>> Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

```texxt
 /var/cache/remnux/cli/v2022.3.1/saltstack.log
```

```text
 archive_|-remnux-networkminer-archive_|-/usr/local/_|-extracted:
    __run_num__: 583
    __sls__: remnux.tools.networkminer
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.networkminer.remnux-networkminer-source'
    duration: 0.007
    result: false
    start_time: '13:42:27.450887'
  archive_|-remnux-polarproxy-archive_|-/usr/local/polarproxy/_|-extracted:
    __run_num__: 724
    __sls__: remnux.tools.polarproxy
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-source'
    duration: 0.003
    result: false
    start_time: '13:53:13.954265'


archive_|-remnux-tools-trid-archive_|-/usr/local/trid_linux_64_|-extracted:
    __run_num__: 707
    __sls__: remnux.tools.trid
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.trid.remnux-tools-trid-source,
      remnux.tools.trid.remnux-tools-tridupdate-source'
    duration: 0.004
    result: false
    start_time: '13:49:44.701370'
  archive_|-remnux-tools-tridupdate-archive_|-/usr/local/trid_linux_64_|-extracted:
    __run_num__: 708
    __sls__: remnux.tools.trid
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.trid.remnux-tools-tridupdate-source,
      remnux.tools.trid.remnux-tools-trid-archive'
    duration: 0.021
    result: false
    start_time: '13:49:44.712117'


cmd_|-remnux-tools-tridupdate-run_|-/usr/bin/python3 /usr/local/bin/tridupdate_|-wait:
    __run_num__: 716
    __sls__: remnux.tools.trid
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.trid./usr/local/bin/tridupdate'
    duration: 0.002
    result: false
    start_time: '13:49:44.742621'
```

**Comment by lennyzeltser** [comment]
@seanthegeek,

It looks like the only tools that failed to install are TrID and PolarProxy, so almost all aspects of REMnux should be on your system now. If you share the full saltstack.log file, I'll take a look to see what went wrong with them; it's possible that it was some temporary network issue.

Also, take a look at the [bottom of this thread](https://github.com/REMnux/remnux-cli/issues/55) regarding one approach to installing REMnux on Xubuntu using `dedicated` mode. Let me know if this approach works better for you.

**Comment by seanthegeek** [comment]
I just tried the install again to test if it was some kind of network issue, and got a different set of errors. The results were the same for both the dedicated and install modes.

[saltstack.log](https://github.com/REMnux/remnux-cli/files/7974887/saltstack.log)

**Comment by lennyzeltser** [comment]
@seanthegeek, this time the only issue you encountered was with the installation of ViperMonkey. 

I looked into it and discovered that the ViperMonkey issue was affecting all REMnux users, not just you. 

ViperMonkey is still written in Python 2. The problem was due to ViperMonkey's dependencies, [regex, dropping support of Python 2 in a recent update](https://github.com/mrabarnett/mrab-regex/commit/227163df1b66a616e20a7f04424860540573949c).

I believe I found a workaround for this issue. Could you please give it another try?

**Comment by seanthegeek** [comment]
Success! Thank you for all of your work on on REMnux. I'm really enjoying the SANS course too.
