### ISSUE TITLE
remnux update error

### ISSUE THREAD

**Issue by JSHOX1** [REMnux/remnux-cli#64]
Good Morning

I can run remnux upgrade just fine.

remnux upgrade
> remnux-cli@1.3.3.0.g1df38b1
> remnux-version: v2022.7.1

No upgrades available

But when I try remnux update it gives the error below.

remnux update
> remnux-cli@1.3.3.0.g1df38b1
> remnux-version: v2022.7.1

> downloading v2022.7.1
>> downloading remnux-salt-states-v2022.7.1.tar.gz.asc
>> downloading remnux-salt-states-v2022.7.1.tar.gz.sha256
>> downloading remnux-salt-states-v2022.7.1.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2022.7.1.tar.gz
> validating file remnux-salt-states-v2022.7.1.tar.gz
> validating signature for remnux-salt-states-v2022.7.1.tar.gz.sha256
> extracting update remnux-salt-states-v2022.7.1.tar.gz
> using previous mode: cloud
> upgrading/updating to v2022.7.1
>> Log file: /var/cache/remnux/cli/v2022.7.1/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

saltstack.log 
cat /var/cache/remnux/cli/v2022.7.1/saltstack.log
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3001.8', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 439, in salt_call
    import salt.cli.call
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 6, in <module>
    import salt.cli.caller
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 19, in <module>
    import salt.minion
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 30, in <module>
    import salt.crypt
  File "/usr/lib/python3/dist-packages/salt/crypt.py", line 35, in <module>
    import salt.utils.crypt
  File "/usr/lib/python3/dist-packages/salt/utils/crypt.py", line 22, in <module>
    import Crypto.Random  # nosec
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Random/__init__.py", line 28, in <module>
    from Crypto.Random import OSRNG
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Random/OSRNG/__init__.py", line 32, in <module>
    from Crypto.Random.OSRNG.posix import new
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Random/OSRNG/posix.py", line 66
    except IOError, e:
                  ^
SyntaxError: invalid syntax

Also I tried this:
sudo apt update
sudo apt autoremove
sudo apt --fix-broken install 

and a reboot

System info: Ubuntu 20.04.4 LTS (GNU/Linux 5.11.0-1028-azure x86_64)

**Comment by digitalsleuth** [comment]
Hi @JSHOX1 , any chance you can provide the saltstack.log file as well so we can take a look?

**Comment by JSHOX1** [comment]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8124898/saltstack.log)
Hi @digitalsleuth  Here is the saltstack.log

**Comment by digitalsleuth** [comment]
Can you run `salt-call --versions-report` and post the output here? Also, I notice you're on a 'future' release of LTS, and on Azure as well. Have you tried this type of install on a bare metal host as well running that LTS point release?

**Comment by JSHOX1** [comment]
I have not. Here are the results 

salt-call --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3001.8', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 439, in salt_call
    import salt.cli.call
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 6, in <module>
    import salt.cli.caller
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 19, in <module>
    import salt.minion
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 30, in <module>
    import salt.crypt
  File "/usr/lib/python3/dist-packages/salt/crypt.py", line 35, in <module>
    import salt.utils.crypt
  File "/usr/lib/python3/dist-packages/salt/utils/crypt.py", line 22, in <module>
    import Crypto.Random  # nosec
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Random/__init__.py", line 28, in <module>
    from Crypto.Random import OSRNG
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Random/OSRNG/__init__.py", line 32, in <module>
    from Crypto.Random.OSRNG.posix import new
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Random/OSRNG/posix.py", line 66
    except IOError, e:
                  ^
SyntaxError: invalid syntax

**Comment by digitalsleuth** [comment]
Gotcha, this seems to be an issue with salt specifically. Can you provide me the output of the following commands?
```
$(which python) -V
$(which python2) -V
$(which python3) -V
python3 -m pip list | grep crypto
```

**Comment by JSHOX1** [comment]
output:

$(which python) -V
-V: command not found
$(which python2) -V
Python 2.7.18
$(which python3) -V
Python 3.8.10
python3 -m pip list | grep crypto
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
asn1crypto             1.4.0
cryptography           3.4.8
msoffcrypto-tool       5.0.0
pycrypto               2.6.1
pycryptodome           3.14.1
pycryptodomex          3.14.1
WARNING: You are using pip version 21.0.1; however, version 22.0.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

**Comment by digitalsleuth** [comment]
This looks specifically like a pycrypto problem. I'm unable to duplicate the issue, but you could try uninstalling pycrypto and seeing if that resolves the issue. If it was installed already via apt, try `sudo apt remove python-crypto`, otherwise if installed via python3 try `sudo python3 -m pip uninstall pycrypto`.

Once that's done, try running the `salt-call --versions-report` command again.

**Comment by JSHOX1** [comment]
I ran both sudo apt remove python-crypto and sudo python3 -m pip uninstall pycrypto

here are the results from salt-call --versions-report   The results look better this time

salt-call --versions-report
/usr/lib/python3/dist-packages/salt/utils/jinja.py:48: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  JINJA_VERSION = LooseVersion(jinja2.__version__)
/usr/lib/python3/dist-packages/salt/utils/jinja.py:716: DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.
  def show_full_context(ctx):
/usr/lib/python3/dist-packages/salt/version.py:677: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
  lin_ver = linux_distribution()
/usr/lib/python3/dist-packages/salt/version.py:741: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
  ("dist", " ".join(linux_distribution(full_distribution_name=False))),
Salt Version:
           Salt: 3001.8

Dependency Versions:
           cffi: 1.15.0
       cherrypy: Not Installed
       dateutil: 2.8.2
      docker-py: 5.0.3
          gitdb: 4.0.9
      gitpython: 3.1.27
         Jinja2: 3.0.3
        libgit2: Not Installed
       M2Crypto: 0.38.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.3
   mysql-python: Not Installed
      pycparser: 2.21
       pycrypto: Not Installed
   pycryptodome: 3.14.1
         pygit2: Not Installed
         Python: 3.8.10 (default, Nov 26 2021, 20:14:08)
   python-gnupg: 0.4.5
         PyYAML: 5.4.1
          PyZMQ: 22.3.0
          smmap: 5.0.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.4

System Versions:
           dist: ubuntu 20.04 Focal Fossa
         locale: utf-8
        machine: x86_64
        release: 5.11.0-1028-azure
         system: Linux
        version: Ubuntu 20.04 Focal Fossa

**Comment by digitalsleuth** [comment]
Excellent. The other errors can be safely ignored for now, they are just warnings about the modules in your running Salt version, but shouldn't impact anything.

You can try running the `sudo remnux upgrade` command again and see how it works out!

**Comment by kozanostra2x2i** [comment]
Thanks @JSHOX1 for great info!

**Comment by JSHOX1** [comment]
@digitalsleuth upgrade and update are both working now. thank you so much!

**Comment by JSHOX1** [comment]
One thing to note after running remnux update and rebooting, the host gave me the same error again. I ran those commands to remove pycrypto and it worked again, so I'm thinking the update is adding it back. At least I know how to fix the error now.

**Comment by digitalsleuth** [comment]
Thanks for the feedback @JSHOX1 , I'll take a look and see what's re-installing pycrypto and figure out what we can do about it.
Cheers!
