### ISSUE TITLE
Installer fails on Ubuntu 20.04.3

### ISSUE THREAD

**Issue by tlium** [REMnux/remnux-cli#65]
Installer fails at
>> Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by tlium** [comment]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8146350/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @tlium , it looks like there were only two minor errors in your installation. The install of bytehist showed a temporary DNS resolution error, which will likely be fixed if you try again. The second was that pyinstxtractor has been updated and the new SHA256 hash has to added to the salt state.

I will submit a PR for the pyinstxtractor update when I get to a PC, but the bytehist issue should be resolved by now. 

Other than that, everything else is installed properly.

**Comment by tlium** [comment]
Thanks a lot for the reply. Good to know that they were only minor errors and I'm not missing out on functionality. I'll do another install when the PR is merged and test on a clean system.

**Comment by lennyzeltser** [comment]
The distro now includes the new hash of pyinstxtractor, so this should be good to go.
