### ISSUE TITLE
Ubuntu 20.04 LTS w/Remnux - update fails

### ISSUE THREAD

**Issue by Duocast** [REMnux/remnux-cli#67]
Error occures after running remnux update ("remnux upgrade" works verifying I am on v2022.11.1).
The terminal error shows as 
Update returned exit code not zero
Error: Update returned exit code not zero
at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
at ChildProcess.emit (events.js:315:20)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

saltstack.log results:
Traceback (most recent call last):
File "/usr/bin/salt-call", line 11, in <module>
     load_entry_point('salt==3001.8', 'console_scripts', 'salt-call')()
File "/usr/lib/python3/dist-packages/salt/scripts.py", line 439, in salt_call
     import salt.cli.call
File "/usr/lib/python3/dist-packages/salt/call.py", line 6, in <module>
     import salt.cli.caller
File "/usr/lib/python3/dist-packages/salt/caller.py", line 19, in <module>
     import salt.minion
File "/usr/lib/python3/dist-packages/salt/minion.py", line 42, in <module>
     import salt.pillar
File "/usr/lib/python3/dist-packages/salt/pillar/__init__.py", line 19, in <module>
     import salt.fileclient
File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 32, in <module>
     import salt.utils.templates
File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 27, in <module>
     import salt.utils.jinja
File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 31, in <module>
     from jinja2 import BaseLoader, Markup, TemplateNotFound, nodes
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)

Looks to be related to python? Any guidance would be helpful. Thanks!
(This is on a fresh installation of Ubuntu 20.04 LTS and a fresh Remnux install following the guidance of the Remnux [documentation](https://docs.remnux.org/install-distro/install-from-scratch)).

Note: The post doesn't allow <>. Everything following an "in" on a line is "module" surrounded in arrow brackets.

**Comment by digitalsleuth** [comment]
Hi @Duocast , did you happen to attempt to install or uninstall SaltStack prior to running the remnux CLI? This looks curious as it seems to suggest part of the required salt components are missing. 

Also, with the SaltStack log results, is that the entirety of the log file, or just the error? If it's just a part of the log, can you upload the whole thing? There might be more hints in there. 

Cheers!

**Comment by Duocast** [comment]
No attempt to uninstall or reinstall Saltstack. 
This is the entire saltstack.log file.
This is from a fresh install.

**Comment by lennyzeltser** [comment]
Looks like a [recently reported SaltStack issue](https://github.com/saltstack/salt/issues/61848). @digitalsleuth, any chance you'd be able to look into it for a workaround?

**Comment by digitalsleuth** [comment]
Sure thing, I'm on it!

**Comment by digitalsleuth** [comment]
It looks like Saltstack has updated their version about an hour ago to 3004.1 which includes the pinning of pre-reqs for jinja to 3.0.3. I'm going to test against the newest version to confirm everything works, then I would probably recommend we upgrade the CLI to 3004.1. More to follow.

**Comment by digitalsleuth** [comment]
Looks like it didn't work, I'll keep working on a workaround :)

**Comment by phos2lampsei** [comment]
Hello everyone. I am new here but I ran into this same issue while trying to do a remnux-cli install in add-on mode for a recently built SIFT on Ubuntu 20.04 VM. I just figured out a workaround a few minutes ago and was trying to figure out how to reach out to share what I found in case that helps the broader effort.

From what I have found the issue was apparently caused by the changes in Jinja 2 3.1.x builds (my VM had been on Jinja 2 version 3.1.1).  I found some suggestions to back rev Jinja 2 to the older 3.0.x version (I used 3.0.3). I was able to use PIP to remove Jinja 2 version 3.1.1 and instead install Jinja 2 version 3.0.3. After I did this, the remnux-cli installer started working for me. 

Here are some of the URL's I found in my research if they help at all:

https://github.com/sphinx-doc/sphinx/issues/10291
https://stackoverflow.com/questions/71645272/importerror-cannot-import-name-markup-from-jinja2/71647006#71647006
https://github.com/holoviz/panel/issues/3260

Hope this helps!

**Comment by digitalsleuth** [comment]
Hi @phos2lampsei , thank you for providing your feedback! We actually just released a new version 2 days ago which addresses the issue going forward, but existing systems having the issue should do just what you mentioned; install jinja2==3.0.3 and start from there.
Cheers!

**Comment by phos2lampsei** [comment]
Wow...that was fast! Thanks! Yeah I saw the other note but in my case I think either the SIFT install or standard Apt-Get updates had already broken me by upgrading me to Jinja 2 3.1.1 so I was stuck until I did the manual forced downgrade. Been a learning experience for me since this broke on me last night trying to get this done. Not sure if there is a way to make the installer do a downgrade for unfortunate souls like me who got upgraded to the bum build? I just built the VM yesterday with a fresh download of the Remnux-CLI installer so I think in my case because I was in add-on mode I was broken by the existing presence of the newer jinja2 that my VM already had.

**Comment by phos2lampsei** [comment]
> It looks like Saltstack has updated their version about an hour ago to 3004.1 which includes the pinning of pre-reqs for jinja to 3.0.3. I'm going to test against the newest version to confirm everything works, then I would probably recommend we upgrade the CLI to 3004.1. More to follow.

So I think I spoke too soon. After fixing the Jinja 2 issues by the forced downgrade to Jina2 3.0.3 things were humming along with my Remnux addon mode install but it still failed on me. I ran into several more package failures. While trying to debug those I noticed apt-get update was referring to a non-existent https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3001/ directory. I was able to fix this manually in my apt-get config but pointing the path to a newer version and get Apt-Get update happy again. However I downloaded a fresh copy of remnux-cli (per the instructions at https://docs.remnux.org/install-distro/add-to-existing-system) to be sure and retried my install but it seems it is hardcoded to look for the non-existent https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3001/ directory. So it appears that not only has salt project been upgraded several times in the last few days but that the old 3001 folder referenced by the REMnux installer no longer even exists.

I think I am stuck at this point but would be happy to help test any changes when they are ready.

**Comment by digitalsleuth** [comment]
@phos2lampsei We were just made aware that the saltstack repo has removed support for 3001, so we're preparing a new CLI tool to support 3004. Currently running tests so we can confirm no breakage, then the changes will be applied.

We'll keep you, and everyone, posted!

**Comment by phos2lampsei** [comment]
Sounds like you all are already on top of it! Thanks a lot!!

**Comment by lennyzeltser** [comment]
@phos2lampsei, this should be fixed now. Please give it a a try!

**Comment by Y8765** [comment]
With all that have been written here , still encoutering the problem :(
at the moment im using the OVA , but preffering a fresh install
b.t.w. installation with the latest binary dosent works even as addon in sift workstation
hope that you guys will find a solution
**thank you for your time and efforts!**

**Comment by digitalsleuth** [comment]
Hi @Y8765 Can you possibly paste us your error, or upload the saltstack.log file, if applicable?
This will help us sort out the issue.

**Comment by phos2lampsei** [comment]
> 

Just had a chance to circle back on this. I pulled down a fresh copy of the remnux-cli, verified the hash and confirmed it was the newer version. While attempting to run it, there was an immediate "unable to locate package salt-minion" failure trying to remove salt-common and salt-minion. I dropped out and confirmed that these packages were not installed. Re-ran another apt-get update and noticed the failure again for the non-existent saltproject /3001 subdirectory (even though I had manually fixed that before). I went back in and manually fixed the /etc/apt/sources.list.d/saltstack.list file again to point it to the /3004 directory again and then made sure apt-get update was happy again. After doing this I was then able to get the new remnux-cli installer to run.

I don't know if my system had just been missed up by the prior testing and workaround attempts but I wonder if for those who tried the install before (either successfully when the /3001 saltproject directory still existed or during the failure period after that /3001 directory went away) that there may also be inconsistent machine artifacts that require a bit of cleanup before things will be happy again. 

Personally I think I may be finally fixed but raising this for awareness in case artifacts from the old /3001 saltstack repo cause other users install issues that may warrant a bit of automated cleanup in the install script. 

Thanks again for your speedy attention in updating the installer!

**Comment by Y8765** [comment]
HI !
Tried again today on fresh install , seems to work smoothly.
i think for the best of everyone i might will upload my ready machine for everyone for easy use.
thank you

**Comment by Y8765** [comment]
> Hi @Y8765 Can you possibly paste us your error, or upload the saltstack.log file, if applicable? This will help us sort out the issue.

i've deleted that machine so log source isnt available :(

**Comment by Y8765** [comment]
now encountering this issue - Fresh installation
Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


[saltstack.log](https://github.com/REMnux/remnux-cli/files/8416084/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @Y8765 It looks like Network Miner has been updated and the hash will have to be updated as well. We'll get that done today, but as for your install, everything except for Network Miner installed properly.

**Comment by Y8765** [comment]
> Hi @Y8765 It looks like Network Miner has been updated and the hash will have to be updated as well. We'll get that done today, but as for your install, everything except for Network Miner installed properly.

Yeh, i saw that the system backround has been changed to remnux etc
Thank you guys 👌

**Comment by muawyah** [comment]
I still can't go beyond this point when running $remnux upgrade
the upgrade does not take place and my background is still the same
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8471379/saltstack.log)


>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by digitalsleuth** [comment]
Hi @muawyah , the log file shows that everything except NetworkMiner installed correctly, and the background should change once you reboot.

Please give that a shot and let us know how it goes!

**Comment by muawyah** [comment]
Thank you @digitalsleuth , I have checked the versions for a couple of tools and they look to be the latest
but still the background wont change
<img width="533" alt="Screen Shot 2022-04-12 at 1 29 20 PM" src="https://user-images.githubusercontent.com/16303354/162943044-e84635bd-f28e-4d6d-b884-b6507cd176af.png">

**Comment by digitalsleuth** [comment]
You can try running the following script to see if that will work for you:
`/usr/local/share/remnux/gnome-config.sh`

**Comment by muawyah** [comment]
I ran the above script but the background did not change
I ran the following commands, then I got the success message for the upgrade, but the back ground is the same

curl -Lo remnux-cli-linux https://github.com/REMnux/remnux-cli/releases/download/v1.3.4/remnux-cli-linux
chmod +x remnux-cli-linux
sudo mv remnux-cli-linux /usr/local/bin/remnux

**Comment by digitalsleuth** [comment]
Can you paste the command you used, and the first few lines which follows, for the remnux upgrade command?
________________________________

**Comment by muawyah** [comment]
I did so many playing around since yesterday and tried many work arounds presented on the remnux github
I ran the $remnux update and I got successful message as well

I tried to run it again to get the lines but I cant after the upgrade 
and the screen is cleared

 curl -Lo remnux-cli-linux https://github.com/REMnux/remnux-cli/releases/download/v1.3.4/remnux-cli-linux
 chmod +x remnux-cli-linux
 sudo mv remnux-cli-linux /usr/local/bin/remnux 

  131  remnux upgrade
  132  sudo reboot
  133  ./usr/local/share/remnux/gnome-config.sh
  134  /usr/local/share/remnux/gnome-config.sh
  135  remnux update
  136  sudo reboot
 

remnux@remnux:~$ remnux upgrade
> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: v2022.13.3

**Comment by digitalsleuth** [comment]
@muawyah I think I see the issue. Try running the command as `sudo remnux upgrade` and `sudo ./usr/local/share/remnux/gnome-config.sh`. This should fix your problem.

**Comment by muawyah** [comment]
@digitalsleuth I did but nothing happened
<img width="860" alt="Screen Shot 2022-04-13 at 12 51 22 PM" src="https://user-images.githubusercontent.com/16303354/163152582-e6694deb-9a31-45a9-95c3-22b44f01064a.png">

**Comment by digitalsleuth** [comment]
I'm not sure what change you might be looking for, but the background I can see in the screenshot you provided is the actual background that's supposed to be configured. Are you expecting a different background?

**Comment by muawyah** [comment]
I thought I should get **etc** instead of **nux**

**Comment by digitalsleuth** [comment]
@muawyah I'm afraid I still don't quite understand what you mean, however the end result you have from the image above is the correct output.
