### ISSUE TITLE
remnux update Hangs

### ISSUE THREAD

**Issue by weslowsk** [REMnux/remnux-cli#69]
Downloaded a fresh .ova file today and ran it in VMware Workstation 16 Player and tried to update remnux and it hangs.
I attached the saltstack.log file.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8458019/saltstack.log)
Any ideas?

**Comment by digitalsleuth** [comment]
Hi @weslowsk, from the look of your log file, it was in the midst of upgrading the python3 packages. There is no further activity after that, and no errors that would have impacted the install. I would recommend either trying again, or updating the CLI tool (if it's not already up to date) and trying that as well.

**Comment by weslowsk** [comment]
I exited (CTRL + C) after waiting a long time so that would explain why no output after that.
I'm not confident it will finish if I tried it again, unless you expect it to take hours to complete?
How would I update the CLI tool? How do I check if it's up to date?

**Comment by digitalsleuth** [comment]
You can run the command `remnux version` and the first line should read something like `remnux-cli@1.x.x`. The latest version is [v1.3.4](https://github.com/REMnux/remnux-cli/releases/download/v1.3.4/remnux-cli-linux) if yours is not up to date.

**Comment by weslowsk** [comment]
$ remnux version
> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: v2021.15.2

**Comment by digitalsleuth** [comment]
Did you run `update` or `upgrade` when the command hung? I'm running a test right now to see if there's something stopping it, but the install can take up to 30 minutes at times.

**Comment by weslowsk** [comment]
I ran upgrade earlier today. It hung, so I tried update and have been trying that ever since and it has been hanging too.
I might not have waited a full 30 minutes, so maybe I can just let it run overnight and check it later?

**Comment by digitalsleuth** [comment]
Yes I'd say give that a shot for now. Once my test is complete here I'll let you know how it goes.

**Comment by weslowsk** [comment]
> Yes I'd say give that a shot for now. Once my test is complete here I'll let you know how it goes.

No good here. The script is stuck on that command and pins the CPU. How did your test go?

**Comment by digitalsleuth** [comment]
Sorry for the delay, I'm out of the house right now. Test ran fine with no issues. Can you tell me what RAM and CPU config you've provided the VM, and if you're behind a proxy? I have an idea to speed things up but I have to run another test once I get home.

**Comment by weslowsk** [comment]
> Sorry for the delay, I'm out of the house right now. Test ran fine with no issues. Can you tell me what RAM and CPU config you've provided the VM, and if you're behind a proxy? I have an idea to speed things up but I have to run another test once I get home.

Sounds like it's a me problem since it works fine for you.
No rush, it's Sunday. I never changed the defaults from when I pulled in the .ova file: vm settings tab says 2 CPU, 4 GB RAM. No proxy.
Unless you're really interested in finding out why my environment is pooched, I'm inclined to just spin up a new VM using the fresh .ova, chuck out this pooched VM, and just do an "update" as soon as I install it without doing the "upgrade" first and see how that goes. Thoughts?

**Comment by digitalsleuth** [comment]
An update only re-installs the existing software (like a refresh) where upgrade installs the latest. Trying to redo the VM isn't a bad idea either. I'll still keep working on my end to expedite the installer.

**Comment by weslowsk** [comment]
So, it still hangs immediately after booting up a fresh remnux VM and running `remnux update`.
I'm stumped.

**Comment by digitalsleuth** [comment]
Can you cancel that, reboot it, and run `remnux upgrade` instead? BTW, are you running it with `sudo`?

**Comment by weslowsk** [comment]
Will do. I'm not using `sudo`.
Should I be?

**Comment by digitalsleuth** [comment]
Try that and see how it goes.

**Comment by digitalsleuth** [comment]
And yes, it should be run with sudo. Sorry, forgot to answer that question. :)

**Comment by weslowsk** [comment]
Ah. The documentation isn't clear on that.
https://docs.remnux.org/install-distro/keep-the-distro-up-to-date
I'll run it with `sudo` and see how it goes.

**Comment by digitalsleuth** [comment]
Ahh, you're right. The installation docs (https://docs.remnux.org/install-distro/install-from-scratch#run-remnux-installer) do say to use sudo, but the page you provided does not. Thanks for pointing that out!

**Comment by weslowsk** [comment]
Still no good.
It ended like this:
```
>> Running: /usr/local/bin/docker
>> Running: apt-get autoremove -y
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: away-from-the-dog
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
```

[saltstack.log](https://github.com/REMnux/remnux-cli/files/8459851/saltstack.log)
attached

**Comment by digitalsleuth** [comment]
Actually, as strange as it sounds to say, it worked exactly as it should. Your log file shows that the Network Miner hash has changed (we have a PR in for that already), but other than that, everything else installed properly.

**Comment by weslowsk** [comment]
Good to hear. I'll keep using it as-is then.
Maybe flag this less-than-perfect status message as a known issue for future head-scratchers.
Thanks for the help!

**Comment by digitalsleuth** [comment]
Any time!
