### ISSUE TITLE
Remnux on SIFT Workstation Ubuntu 18.04

### ISSUE THREAD

**Issue by AMetz-InfosecGuy** [REMnux/remnux-cli#7]
I have been trying to add remnux to my SIFT Workstation installation running on Ubuntu 18.04 using 

`remnux install --mode=addon`

However, I keep running into the following issue:

 ```
       Running: remnux-perl-packages
        Update returned exit code not zero
        Error: Update returned exit code not zero
        at ChildProcess. (/snapshot/remnux-cli/remnux-cli.js:551:23)
        at ChildProcess.emit (events.js:315:20)
        at maybeClose (internal/child_process.js:1021:16)
        at Socket. (internal/child_process.js:443:11)
        at Socket.emit (events.js:315:20)
        at Pipe. (net.js:674:12)

```
Try rebooting your system and trying the operation again.

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Pay particular attention to lines that start with [ERROR].

Errors in saltstack.log:

```
[ERROR ] Command '['systemd-run', '--scope', '--description', '"salt.loaded.int.module.aptpkg"', 'apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'upgrade']' failed with return code: 100
[ERROR ] stderr: Running scope as unit: run-ree9a11d3d03447f4a0f5ada9be2cbc2f.scope
[ERROR ] retcode: 100
[ERROR ] Problem encountered upgrading packages. Additional info follows:
Binary file (standard input) matches
```

Here's the saltstack.log file:

[saltstack.log](https://github.com/REMnux/remnux-cli/files/5204145/saltstack.log)

Any help would be very much appreciated. Thanks!

**Comment by lennyzeltser** [comment]
Hi, @CousinOkri. Here are the relevant line from the log file that I noticed:

```
# [ERROR   ] stderr: Running scope as unit: run-ree9a11d3d03447f4a0f5ada9be2cbc2f.scope
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```
This indicates that the APT package database is locked because there's an upgrade happening behind the scenes. This prevents the REMnux installer from adding packages. 

Before proceeding, make sure your system doesn't have an active Ubuntu unattended upgrade in progress. One way to do this is check whether the "unattended-upgrade" process is active (`ps aux | grep unattended-upgrade`.) If the upgrade is active, let it finish, then reboot the system before installing REMnux.

**Comment by AMetz-InfosecGuy** [comment]
I've tried everything. I've installed all available updates, I've disabled automatic updates, edited the apt config files, but I can't seem to get rid of unattended-upgrade. Could you tell me how I can do that?

**Comment by AMetz-InfosecGuy** [comment]
Ok, so I've gotten rid of unattended-upgrades and I can use APT to install other packages as well, but the remnux installation fails at the same point.  I get the same errors in the saltstack.log file as before.

**Comment by lennyzeltser** [comment]
May I take a look at the latest saltstack.log file?

**Comment by AMetz-InfosecGuy** [comment]
Ok, so apparently I was looking at the wrong log and the errors are different now. However, the installation fails at the same point.
Here's the log:

[saltstack.log](https://github.com/REMnux/remnux-cli/files/5215026/saltstack.log)

**Comment by lennyzeltser** [comment]
For some reason the attempt to download SSView was failing due to an SSL error. Strange, as I'm unable to reproduce this. Regardless, I created a workaround. Could you give it a try, please?

**Comment by AMetz-InfosecGuy** [comment]
Installation still stops at remnux-perl-packages.

[saltstack.log](https://github.com/REMnux/remnux-cli/files/5216389/saltstack.log)

**Comment by digitalsleuth** [comment]
From the log, it appears that SSView.zip has a sha256 checksum that doesn't match the intended checksum. I've just verified on the site that the sha256 of SSview.zip is correct. It's possible that the file which actually got downloaded may have been corrupted in the transfer. Can you check the file at path: /usr/local/src/remnux/files/SSView.zip to see if it is in fact a zip file, with a file size of 2630KB, and provide the SHA256 here?

**Comment by AMetz-InfosecGuy** [comment]
So, I checked that directory and SSView.zip wasn't even present there. Did some digging around, and apparently Malwarebytes on my host was blocking requests to www.mitec.cz from the VM during the installation. Added an exception, ran the installation again and it completed successfully!! Thanks to everyone who helped and apologies for taking up so much of your time!

**Comment by lennyzeltser** [comment]
Glad it worked out. This will come in handy for troubleshooting future scenarios where AV interferes with a download.
