### ISSUE TITLE
Remnux Update/Upgrade Failure

### ISSUE THREAD

**Issue by parrostroika** [REMnux/remnux-cli#71]
Greetings - for the past few months I've intermittently attempted to update/upgrade Remnux on Ubuntu 18.04 to no avail. Tried updating/upgrading Ubuntu and even that fails with complaints about no Release file. And following various attempts at troubleshooting...  I'm wondering if this is an 18.04 problem or have I overlooked something else? Thanks for any help available. 

Regards --

Parro 

Attaching saltstack logs for both "remnux update" and remnux "upgrade as well as output of 'sudo apt update && sudo apt upgrade
[saltstack_remnux_update_20220414.log](https://github.com/REMnux/remnux-cli/files/8500592/saltstack_remnux_update_20220414.log)
[saltstack_remnux_upgrade_20220410.log](https://github.com/REMnux/remnux-cli/files/8500593/saltstack_remnux_upgrade_20220410.log)
![remnux_upgrade_fail](https://user-images.githubusercontent.com/48295506/163690367-59232251-01c7-4846-b4fc-01a74086587c.png)
'

**Comment by lennyzeltser** [comment]
Sorry, we no longer support REMnux on Ubuntu 18.04. Please migrate to the release based on 20.04 when you get the chance.

**Comment by parrostroika** [comment]
thank you Sir
