### ISSUE TITLE
Hash mismatch 

### ISSUE THREAD

**Issue by GulIqbal87** [REMnux/remnux-cli#74]
sansforensics@siftworkstation: ~
$ sha256sum remnux-cli
23c7f4eefa7599ea2c4156f083906ea5fd99df18f306e4bb43eec0430073985a  remnux-cli
sansforensics@siftworkstation: ~
$ mv remnux-cli remnux
sansforensics@siftworkstation: ~
$ chmod +x remnux
chmod: changing permissions of 'remnux': Operation not permitted
sansforensics@siftworkstation: ~
$ sudo chmod +x remnux
sansforensics@siftworkstation: ~
$ sudo mv remnux /usr/local/bin
sansforensics@siftworkstation: ~
$ 
sansforensics@siftworkstation: ~
$ sudo remnux install --mode=addon
> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: notinstalled

> mode: addon
> downloading v2022.17.1
>> downloading remnux-salt-states-v2022.17.1.tar.gz.asc
>> downloading remnux-salt-states-v2022.17.1.tar.gz.sha256
>> downloading remnux-salt-states-v2022.17.1.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2022.17.1.tar.gz
> validating file remnux-salt-states-v2022.17.1.tar.gz

Hashes for remnux-salt-states-v2022.17.1.tar.gz do not match. Expected: 2588d4ddd34ed63d2a613e95b3dfc41d23ac329b0a6cc952c05efe162a4dd0a1  /tmp/remnux-salt-states-v2022.17.1.tar.gz
. Actual: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  /tmp/remnux-salt-states-v2022.17.1.tar.gz
.
Error: Hashes for remnux-salt-states-v2022.17.1.tar.gz do not match. Expected: 2588d4ddd34ed63d2a613e95b3dfc41d23ac329b0a6cc952c05efe162a4dd0a1  /tmp/remnux-salt-states-v2022.17.1.tar.gz
. Actual: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  /tmp/remnux-salt-states-v2022.17.1.tar.gz
.
    at validateFile (/snapshot/remnux-cli/remnux-cli.js:414:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async downloadUpdate (/snapshot/remnux-cli/remnux-cli.js:481:3)
    at async run (/snapshot/remnux-cli/remnux-cli.js:755:5)
    at async main (/snapshot/remnux-cli/remnux-cli.js:778:5)

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

sansforensics@siftworkstation: ~

**Comment by lennyzeltser** [comment]
@GulIqbal87, I just confirmed on my system that the states file is downloading correctly and matches the expected hash `2588d4ddd34ed63d2a613e95b3dfc41d23ac329b0a6cc952c05efe162a4dd0a1`.

It's possible that you have an upstream issue that interference with the download. Could you try your operation from another network?

**Comment by GulIqbal87** [comment]
Thank you Lenny for reply 
i still faceing same issue
![image](https://user-images.githubusercontent.com/55154180/166466998-87a0a857-8076-4892-bf68-7403e74626df.png)

![image](https://user-images.githubusercontent.com/55154180/166468053-1d103dc2-6481-459c-aa1f-45f92245e90e.png)

![image](https://user-images.githubusercontent.com/55154180/166467260-1f8af007-6dd9-42b4-8d53-767604efc3fb.png)

Please help me.
Regard

**Comment by lennyzeltser** [comment]
@GulIqbal87, what happens if you try to download the file directly, like:

```
wget https://github.com/REMnux/salt-states/archive/refs/tags/v2022.17.1.tar.gz
```
Then compute the file's hash:
```
sha256sum v2022.17.1.tar.gz
```
