### ISSUE TITLE
 sudo remnux upgrade returns 

### ISSUE THREAD

**Issue by waydaws** [REMnux/remnux-cli#75]
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8693948/saltstack.log)
)

**Comment by digitalsleuth** [comment]
Good morning @waydaws , can you provide the saltstack.log file from your installation so we can help you troubleshoot? Thanks!

**Comment by ghost** [comment]
having the same issue with
- using the remnux VM and run remnux upgrade
- using a clean ubuntu 20.04 mashine and running remnux install / log attached
- 
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8693728/saltstack.log)

**Comment by waydaws** [comment]
> Good morning @waydaws , can you provide the saltstack.log file from your installation so we can help you troubleshoot? Thanks!

I attached it now to my original comment

**Comment by digitalsleuth** [comment]
Looks like the hash has changed for pyinstxtractor. Everything else seems to have installed fine. I'll submit a PR to fix this as soon as I get to a computer!

**Comment by ghost** [comment]
Hi,
Thank you for the update, would be great if the installation process would be robust in a way that it does not break the process if one package throws an error. 



> Am 15.05.2022 um 16:16 schrieb Digital Sleuth ***@***.***>:
> 
> ﻿
> Looks like the hash has changed for pyinstxtractor. Everything else seems to have installed fine. I'll submit a PR to fix this as soon as I get to a computer!
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.
> 
> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/REMnux/remnux-cli/issues/75#issuecomment-1126950508", "url": "https://github.com/REMnux/remnux-cli/issues/75#issuecomment-1126950508", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Gruß

**Comment by lennyzeltser** [comment]
@waydaws and @mesam16, thanks for sending this notice about the error. I believe I addressed it a few minutes ago to correct it. In your upgrades, the other tools installed/updated fine, despite the issue with pyinstxtractor.

@mesam16, the installation process doesn't break if one package throws an error. All other packages get installed regardless, unless the broken package is a dependency for other packages.

**Comment by ghost** [comment]
Thx seems to work for me!

> Am 15.05.2022 um 22:23 schrieb Lenny Zeltser ***@***.***>:
> 
> ﻿
> @waydaws and @mesam16, thanks for sending this notice about the error. I believe I addressed it a few minutes ago to correct it. In your upgrades, the other tools installed/updated fine, despite the issue with pyinstxtractor.
> 
> @mesam16, the installation process doesn't break if one package throws an error. All other packages get installed regardless, unless the broken package is a dependency for other packages.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
> 
> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/REMnux/remnux-cli/issues/75#issuecomment-1127019610", "url": "https://github.com/REMnux/remnux-cli/issues/75#issuecomment-1127019610", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Gruß

**Comment by waydaws** [comment]
> @waydaws and @mesam16, thanks for sending this notice about the error. I believe I addressed it a few minutes ago to correct it. In your upgrades, the other tools installed/updated fine, despite the issue with pyinstxtractor.
> 
> @mesam16, the installation process doesn't break if one package throws an error. All other packages get installed regardless, unless the broken package is a dependency for other packages.

My output form remnux upgrade: 
COMPLETED SUCCESSFULLY! Success: 813, Failure: 0

Thanks, Lenny and everyone that worked on this.
