### ISSUE TITLE
REMnux CLI install failure

### ISSUE THREAD

**Issue by Clayton35** [REMnux/remnux-cli#76]
Tried multiple times to install remnux-cli on Ubuntu VM. Always fails at the same spot. Appears to have 6 'result: false' messages. 

[saltstack.log](https://github.com/REMnux/remnux-cli/files/8701637/saltstack.log)

**Comment by evansnjeru** [comment]
Me too. I have the exact saltstack.log file. I'm using QEMU.

**Comment by digitalsleuth** [comment]
Hi @Clayton35 , it looks like NetworkMiner has a new hash, and it just needs to be updated. Everything else has installed properly though. @evansnjeru , provided you have the same log, your issue will be the same. However, to be safe, it might be best if you upload your log as well so we can review.

**Comment by evansnjeru** [comment]
Issue remains unresolved. As per your request @digitalsleuth here's my saltstack.log
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8707550/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @evansnjeru , after looking at your log, it appears that you had a brief loss of connectivity during the installation process, which caused the volatility installation and the NetworkMiner download to fail.

I would recommend reviewing your network connectivity stability and trying again.

**Comment by evansnjeru** [comment]
Thanks @digitalsleuth for your prompt response you legend. I've attempted to get this installed over the past 3 days. Over and over again. My internet connection seems to work correctly for everything else except for this particular task. The process seems to fail every time at the exact point. I'm currently running the installer one more time. I will be posting the latest saltstack.log shortly.

**Comment by digitalsleuth** [comment]
Are you operating behind a proxy perhaps? That could be preventing the proper download of those packages.

**Comment by evansnjeru** [comment]
Yes I am currently behind a proxy. I will switch my internet connection then try again. Please standby.

**Comment by digitalsleuth** [comment]
You can also try the steps listed here: https://docs.remnux.org/tips/remnux-config-tips#behind-proxy

They should help you work within the proxy.
