### ISSUE TITLE
Can't update 

### ISSUE THREAD

**Issue by futex** [REMnux/remnux-cli#77]
I wanted to update my old remnux VM, so i run _remnux update_ in terminal and get this error

```
> remnux-cli@1.3.1.4.ge28588c

Invalid OS or unable to determine Ubuntu version
Error: Invalid OS or unable to determine Ubuntu version
    at validOS (/snapshot/remnux-cli/remnux-cli.js:170:11)
    at run (/snapshot/remnux-cli/remnux-cli.js:674:9)
    at main (/snapshot/remnux-cli/remnux-cli.js:771:11)
    at Object.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:777:1)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:17:47


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues`
```

I'm on Ubuntu 20.04 LTS, imho it should be well supported

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:    20.04
Codename:   focal
```

**Comment by lennyzeltser** [comment]
Hmmm... Very strange. Could you please update the REMnux installer first:

```
curl -Lo remnux-cli-linux https://github.com/REMnux/remnux-cli/releases/download/v1.3.4/remnux-cli-linux
chmod +x remnux-cli-linux
sudo mv remnux-cli-linux /usr/local/bin/remnux 
```

Then, try `remux upgrade`. (The `update` command generally shouldn't be used.)

**Comment by futex** [comment]
Arf, I thought it updated itself. I have another error now with the last cli binary, see the log, and of course pip is well installed
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8718240/saltstack.log)

thanks you!

**Comment by lennyzeltser** [comment]
@futex, the updater typically updates itself, but in your case for some reason the updated refused to run, so it was unable to update itself :-)

I see in saltstack.log that all the tools installed or upgraded correctly except Malwoverview. I'm not certain why that is, but I just introduced a tweak that might fix the issue. Could you try running `remnux upgrade` again, please?

**Comment by futex** [comment]
I got the same error. 
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8720340/saltstack.log)

**Comment by digitalsleuth** [comment]
It looks like in both of these cases to be an issue with distutils not being installed or not available. @futex Could you run the following commands and post the output here:
`python3 -c "from distutils import sysconfig"`
`sudo apt list | grep distutils`

This should help give us a clearer idea of what's happening.

**Comment by futex** [comment]
```
⚡ root@remnux  ~  python3 -c "from distutils import sysconfig"  
⚡ root@remnux  ~  apt list | grep distutils

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

python-distutils-extra/focal,focal 2.43 all
python3-distutils-extra/focal,focal 2.43 all
python3-distutils/focal-updates,focal-updates,focal-security,focal-security,now 3.8.10-0ubuntu1~20.04 all [installed,automatic]
python3-stsci.distutils/focal,focal 0.3.7-5 all
```

**Comment by digitalsleuth** [comment]
Can you modify one of the commands to:  `python3 -c "from distutils import dist, sysconfig"`
Just to be on the safe side.

**Comment by futex** [comment]
Nothing change, same output

```
 ⚡ root@remnux  ~  python3 -c "from distutils import dist, sysconfig"
 ⚡ root@remnux  ~  apt list | grep distutils  
```

**Comment by digitalsleuth** [comment]
Can you try completing a full update / upgrade of your VM (`sudo apt-get update && sudo apt-get upgrade -y`) and then try the installation again? I noticed that your release is 20.04.2, but the latest focal is 20.04.4. Perhaps something in those missing release upgrades is causing the issue.

Also, the VM you're using, is it the VM available from remnux.org, or is this a custom one?

**Comment by futex** [comment]
The VM is not a custom one, i have installed it from remnux website.
I already made a complete upgrade of it:

```
 ⚡ root@remnux  ~  apt-get update && apt-get upgrade -y
Hit:1 http://www.inetsim.org/debian binary/ InRelease                                                               
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                           
Hit:3 http://us.archive.ubuntu.com/ubuntu focal InRelease                                                           
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease                                                   
Hit:5 https://download.docker.com/linux/ubuntu focal InRelease                                                      
Hit:6 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/3004 focal InRelease                                       
Hit:7 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease                                                 
Hit:8 http://deb.nodesource.com/node_14.x focal InRelease                                                           
Hit:9 http://download.draios.com/stable/deb stable-amd64/ InRelease                                                 
Hit:10 http://packages.microsoft.com/repos/code stable InRelease                                                    
Hit:11 https://download.mono-project.com/repo/ubuntu stable-focal InRelease                                         
Hit:12 http://packages.microsoft.com/repos/vscode stable InRelease                                                  
Hit:13 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease       
Fetched 114 kB in 2s (47.1 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded

root@remnux  /home/remnux/Desktop  lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8720931/saltstack.log)

```

And reboot it, in case off something magic appends, but i still have the same error.

**Comment by futex** [comment]
Doesn't it sounds weird for you?

```
# dpkg -L python3-pip | grep bin
/usr/bin
/usr/bin/pip
/usr/bin/pip3

# which pip 
/usr/local/bin/pip

# dpkg -S /usr/local/bin/pip
dpkg-query: no path found matching pattern /usr/local/bin/pip


pip list | grep pip
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
pip                          22.1
```

**Comment by AlexaVonTess** [comment]
I was having this same issue.  I ran `sudo python3 -m pip install jinja2==3.0.3` and then tried `remnux upgrade` again and it worked.

**Comment by futex** [comment]
I have already installed it to correct few other bugs, but  it doesn't fix this one for me. 
Thank you anyway

**Comment by digitalsleuth** [comment]
Hi @futex, can you submit your most recent saltstack.log file after running the `sudo python3 -m pip install jinja2==3.0.3` command and attempting the install again? I'm wondering if there is a different issue at play now after pinning the jinja2 version.

**Comment by futex** [comment]
Sorry for the delay, here is the log, you will see i still have the same errors.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8950633/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @futex , It looks like the original distutils error is still happening, but you also had an issue with the download of PolarProxy. The PolarProxy issue isn't something we can really resolve as the server which serves the executable seems to have some intermittent connectivity issues.

Can you try running the following commands for me and post the results here:
```bash
ls -la /opt/malwoverview/lib
ls -la /opt/malwoverview/bin
cat /opt/malwoverview/pyvenv.cfg | grep version_info
/opt/malwoverview/bin/python3 -V
```

**Comment by futex** [comment]
Here is the results:

`ls -la /opt/malwoverview/lib
total 12
drwxr-xr-x 3 root root 4096 Nov 17  2020 .
drwxr-xr-x 6 root root 4096 Nov 17  2020 ..
drwxr-xr-x 5 root root 4096 Nov 17  2020 python3.6


ls -la /opt/malwoverview/bin
total 4988
drwxr-xr-x 3 root root    4096 Jul 26  2021 .
drwxr-xr-x 6 root root    4096 Nov 17  2020 ..
-rw-r--r-- 1 root root    2076 Nov 17  2020 activate
-rw-r--r-- 1 root root    1018 Nov 17  2020 activate.csh
-rw-r--r-- 1 root root    2172 Nov 17  2020 activate.fish
-rw-r--r-- 1 root root    1137 Nov 17  2020 activate_this.py
-rwxr-xr-x 1 root root     234 Nov 17  2020 chardetect
-rwxr-xr-x 1 root root     247 Nov 17  2020 easy_install
-rwxr-xr-x 1 root root     247 Nov 17  2020 easy_install-3.6
-rwxr-xr-x 1 root root     228 Nov 17  2020 futurize
-rwxr-xr-x 1 root root     222 Nov 17  2020 geocode
-rwxr-xr-x 1 root root  499026 Jul 26  2021 malwoverview.py
-rwxr-xr-x 1 root root     230 Nov 17  2020 pasteurize
-rwxr-xr-x 1 root root     238 Nov 17  2020 pip
-rwxr-xr-x 1 root root     238 Nov 17  2020 pip3
-rwxr-xr-x 1 root root     238 Nov 17  2020 pip3.6
drwxr-xr-x 2 root root    4096 Jul 26  2021 __pycache__
lrwxrwxrwx 1 root root       7 Nov 17  2020 python -> python3
-rwxr-xr-x 1 root root 4526456 Nov 17  2020 python3
lrwxrwxrwx 1 root root       7 Nov 17  2020 python3.6 -> python3
-rwxr-xr-x 1 root root    2335 Nov 17  2020 python-config
-rwxr-xr-x 1 root root     236 Nov 17  2020 valhalla-cli
-rwxr-xr-x 1 root root     225 Nov 17  2020 wheel

cat /opt/malwoverview/pyvenv.cfg | grep version_info
cat: /opt/malwoverview/pyvenv.cfg: No such file or directory

/opt/malwoverview/bin/python3 -V
Python 3.6.9`

Thanks for your help

**Comment by digitalsleuth** [comment]
Well for some reason it looks like you have the wrong Python Virtual Env for the OS. You mentioned you got the VM from the remnux.org website, how long ago did you download that VM, or was it a Bionic VM when you got it and you upgraded it to Focal?

**Comment by futex** [comment]
ah yes it's an old VM, previously updated from Bionic. I should resintall it from scratch i think.
