### ISSUE TITLE
Remnux CLI install fails at SSH

### ISSUE THREAD

**Issue by DonnyPereira** [REMnux/remnux-cli#79]
I am running qemu on my Endeavour OS.
I use libvirt as the graphical vm manager.

First I tried downloading the remnux ova file and then converting it to qcow2 file using qemu-img, however that failed every time and I am not sure why.

So I then created an Ubuntu 20.04 machine and followed the steps outlined in the [docs](https://docs.remnux.org/install-distro/install-from-scratch) to install remnux from scratch..

While running Step 3, i.e. the command `sudo remnux install`, the install fails when trying to install ssh:

```bash
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.C
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8747183/saltstack.log)
hildProcess._handle.onexit (internal/child_process.js:286:5)
```

I tried looking at the saltstack log file for `result: false` but was unable to make sense of it.
I have attached my saltstack log file
[saltstack.log](https://github.com/REMnux/remnux-cli/files/8747189/saltstack.log)

**Comment by lennyzeltser** [comment]
@DonnyPereira, thanks for reporting this issue. There might've been a problem with the installation of Thug. I'll try looking into it later today.

**Comment by lennyzeltser** [comment]
I believe I corrected the issue. Please run `remnux upgrade` on your system to give it a try. (There's no need to do run the whole installation from the beginning.)

**Comment by DonnyPereira** [comment]
@lennyzeltser thanks for the prompt response!
I have run the command and everything runs fine, really appreciate the assistance!
