### ISSUE TITLE
REMnux on Ubuntu 18.04 with sift-cli v1.9.0-rc4: Install fails.

### ISSUE THREAD

**Issue by gebhard73** [REMnux/remnux-cli#8]
Hi,

I installed Ubuntu 18.04 from scratch on a HW box and added SIFT using v1.9.0-rc4 (https://github.com/teamdfir/sift-cli/releases/tag/v1.9.0-rc4).

I got an error during `sudo remnux install --mode=addon`. I manually executed `apt-get update`, `apt-get -u dist-upgrade`, `apt-get autoremove` which did some work.

Just to be safe I disabled the Ubuntu upgrade watch process as mentioned here: https://askubuntu.com/questions/1098757/ubuntu-18-10-unattended-upgrades-shutdown-wait-for-signal#1099258

Then re-ran remnux install script. Failed again. 

Any idea? Tnx.

[saltstack.log](https://github.com/REMnux/remnux-cli/files/5211510/saltstack.log)

**Comment by lennyzeltser** [comment]
Looks like there's an issue with a recently-updated Viper Framework. We're looking into it.

Also, thanks for the pointer to the instructions for stopping the unattended upgrade process! I was looking for something like this, but couldn't find it.

**Comment by gebhard73** [comment]
> Looks like there's an issue with a recently-updated Viper Framework. We're looking into it.

Tnx, Lenny.

> Also, thanks for the pointer to the instructions for stopping the unattended upgrade process! I was looking for something like this, but couldn't find it.

You're very welcome.

**Comment by lennyzeltser** [comment]
You should be able to install without errors now us. Thanks to @digitalsleuth for looking into the Viper Framework problem and creating a workaround!

**Comment by gebhard73** [comment]
CLI version as of 2020-09-12 (b550e13003d5d805214a79e019e9a5854d09b95f09f9c024803dd2d0275cb1d2) worked, many thanks to  @digitalsleuth and @lennyzeltser

**Comment by gebhard73** [comment]
just for the records - the new version of REMnux cli also worked fine intalling REMnux into a fresh Ubuntu 18.04 template running on Qubes OS

**Comment by lennyzeltser** [comment]
Thanks great to know, thanks for sharing this info!
