### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by adastra247** [REMnux/remnux-cli#82]
This is a base Ubuntu 20 VM that I found using this guide - https://docs.remnux.org/install-distro/install-from-scratch

I've ran apt-get update and rebooted several times. 

Thanks!

>> Running: /etc/ssh/sshd_config
>> Running: away-from-the-dog
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

    start_time: '14:35:57.252132'
  test_|-remnux-theme-gnome-config_|-remnux-theme-gnome-config_|-nop:
    __id__: remnux-theme-gnome-config
    __run_num__: 786
    __sls__: remnux.theme.gnome-config.init
    changes: {}
    comment: Success!
    duration: 9.731
    name: remnux-theme-gnome-config
    result: true
    start_time: '14:35:57.999504'
  test_|-remnux-theme_|-remnux-theme_|-nop:
    __id__: remnux-theme
    __run_num__: 810
    __sls__: remnux.theme
    changes: {}
    comment: Success!
    duration: 12.403
    name: remnux-theme
    result: true
    start_time: '14:36:01.223127'
  test_|-remnux-tools_|-remnux-tools_|-nop:
    __id__: remnux-tools
    __run_num__: 749
    __sls__: remnux.tools
    changes: {}
    comment: Success!
    duration: 1.97
    name: remnux-tools
    result: true
    start_time: '14:35:38.304029'
  user_|-remnux-user-remnux_|-remnux_|-present:
    __id__: remnux-user-remnux
    __run_num__: 364
    __sls__: remnux.config.user
    changes: {}
    comment: User remnux is present and up to date
    duration: 7.062
    name: remnux
    result: true
    start_time: '14:31:14.910777'
  virtualenv_|-remnux-python-packages-vipermonkey-virtualenv_|-/opt/vipermonkey_|-managed:
    __id__: remnux-python-packages-vipermonkey-virtualenv
    __run_num__: 243
    __sls__: remnux.python-packages.vipermonkey
    changes: {}
    comment: virtualenv exists
    duration: 4028.388
    name: /opt/vipermonkey
    result: true
    start_time: '14:28:16.851345'
  virtualenv_|-remnux-python3-packages-malwoverview-virtualenv_|-/opt/malwoverview_|-managed:
    __id__: remnux-python3-packages-malwoverview-virtualenv
    __run_num__: 365
    __sls__: remnux.python3-packages.malwoverview
    changes: {}
    comment: virtualenv exists
    duration: 6434.065
    name: /opt/malwoverview
    result: true
    start_time: '14:31:14.943819'

[saltstack.log](https://github.com/REMnux/remnux-cli/files/8855745/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @adastra247 , It looks like the sha256 hash for pyinstaller-extractor has changed again, thus causing your error. Everything else has installed and configured properly except that tool. A new release will be coming shortly to address this.

Cheers!

**Comment by lennyzeltser** [comment]
Today's build fixes this error.
