### ISSUE TITLE
VM images are outdated

### ISSUE THREAD

**Issue by ralf-koenig** [REMnux/remnux-cli#83]
Hello,
the VM images that are provided for download on https://docs.remnux.org/install-distro/get-virtual-appliance are more than 14 months old and on v2021.15.2. This means, each user that has downloaded the VM image has to go through an extensive updating and upgrading the distro to get to v2022.21.4 with multiple opportunities for bugs/issues in this upgrade process.

Can you please provide new VM images (at least once a year or for every major yearly release), that are on the latest release right away?

Thanks in advance, Ralf

**Comment by lennyzeltser** [comment]
Yeah, good point, I just need to find the time to regenerate the images.

**Comment by lennyzeltser** [comment]
Done! I generated and published new OVA files last night.
