### ISSUE TITLE
ubuntu 20.04 clean install error

### ISSUE THREAD

**Issue by monfora** [REMnux/remnux-cli#85]
Clean install from mini.iso with errors

[saltstack.log](https://github.com/REMnux/remnux-cli/files/9020280/saltstack.log)

**Comment by lennyzeltser** [comment]
Thanks for opening an issue, @monfora. It looks like all tools installed fine except Malwoverview. I [corrected the issue](https://github.com/REMnux/salt-states/commit/e6306672a1a456fdf1c2bbc606547edd196055aa), I believe, so you shouldn't encounter it anymore. Could you please run `remnux upgrade` on your system to confirm that you no longer see any errors?

**Comment by monfora** [comment]
Installed successfully. Thank you.
