### ISSUE TITLE
Installation for an existing system fails at remnux-perl-packages

### ISSUE THREAD

**Issue by RobotsOnDrugs** [REMnux/remnux-cli#87]
```
>> Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

This is the exact same output as in issue #65, and my saltstack.log looks very similar to that one, though I can upload it if needed.

**Comment by digitalsleuth** [comment]
Hi @RobotsOnDrugs , anytime there is an error in the installation process the output will always look the same. The differences exist within the log file (saltstack.log), which help us identify the problem. 

It would be helpful if you could upload it, so we can help identify and fix the issue.

Also, just in case you weren't aware, running `remnux update` will only reinstall the current version of packages, and not `upgrade` the packages. Additionally, `update` does not install an older version of the installer. If there is an update to the installer, then the new version should be downloaded and used for future installations. The newest installer can always be found at https://github.com/remnux-cli.

Once you've uploaded your saltstack.log file, we'll review it and provide you a solution as soon as we can.

Cheers!

**Comment by RobotsOnDrugs** [comment]
Here is the saltstack.log:
[saltstack.log](https://github.com/REMnux/remnux-cli/files/9036152/saltstack.log)


`remux update` *will* install the old version if the packages have not been upgraded. I looked at the version when it ran and the update was run with the latest installer which I manually put into /usr/local/bin. When I ran a subsequent `upgrade`, it was the old version. It is surprising for someone new, but it makes sense once you understand what `update` does, and it's exactly what you say - it will reinstall the packages and not upgrade them. It will clobber whatever manual changes you've made. Once the packages are upgraded, then `remnux update` will reinstall the installer alongside the other packages, giving you the installer for that version - nothing older and nothing newer. If you've upgraded to the latest version for all of REMnux, then `remnux update` will give you the latest version.

Anyway, thanks for taking a look.

**Comment by jw4n6** [comment]
Can confirm the same error described in the above saltstack.log by installing remnux from scratch with "sudo remnux install --mode=addon"
[saltstack.log](https://github.com/REMnux/remnux-cli/files/9039349/saltstack.log)
.

**Comment by digitalsleuth** [comment]
Hi @B10haZardX , can you also upload your saltstack.log file so we can check? Thanks!

**Comment by digitalsleuth** [comment]
@RobotsOnDrugs , I've finished reviewing your saltstack.log file, and it looks like there were two errors there. One of them appears to be as a result of a temporary DNS issue with launchpad.net in the adding of one of the repos. 
The second error came from malwoverview, showing that it could not find one of the config files. I suspect this is due to some recent changes with the malwoverview tool. 

Could you try running `malwoverview.py -h` and look near the top of the help contents for a line saying `This version is` and tell me the version number?

As for the installer question, I can see where the confusion may lie. The installer itself (the binary placed in /usr/local/bin) does not change, but the salt-states which get downloaded (v2022.26.3 for example) change depending on the command `update` or `upgrade`. If you have v2022.12.9 installed (for example) and run `update`, it will download the packages for that version, and the installer will install those packages. If you run `upgrade`, it will go get the latest package. But the installer itself does not change unless you replace it.

**Comment by digitalsleuth** [comment]
@B10haZardX , after looking at your log file, there were two errors with yours as well. The first was during the download of PolarProxy, there was a brief connectivity issue with the server and your download timed out. Unfortunately this isn't something we can remedy, as it is an issue with the destination server itself.

The second error was the same malwoverview error above. Can you run the same command `malwoverview.py -h` and tell us the version listed near the top of the help content menu?

**Comment by jw4n6** [comment]
@digitalsleuth , thanks for checking the logs. The version of malwoverview.py is **5.0.3**

**Comment by digitalsleuth** [comment]
@RobotsOnDrugs and @B10haZardX , can you both run the following commands and provide the output?
```bash
ls /opt/malwoverview/lib/python3.8/site-packages/
ls -la /opt/malwoverview/lib/python3.8/site-packages/home
```

**Comment by jw4n6** [comment]
@digitalsleuth 

ls /opt/malwoverview/lib/python3.8/site-packages/

```

backports                           colorama-0.4.5.dist-info      future-0.18.2.dist-info    magic                         pefile.py                       polyswarm_api                    requests-2.28.1.dist-info     urllib3                      wheel-0.34.2.virtualenv
certifi                             configparser-5.2.0.dist-info  geocoder                   malwoverview                  peutils.py                      polyswarm_api-3.0.0.dist-info    setuptools                    urllib3-1.26.9.dist-info
certifi-2022.6.15.dist-info         configparser.py               geocoder-1.38.1.dist-info  malwoverview-5.0.3.dist-info  pip                             __pycache__                      setuptools-44.0.0.dist-info   validators
charset_normalizer                  dateutil                      home                       ordlookup                     pip-20.0.2.dist-info            python_dateutil-2.8.2.dist-info  setuptools-44.0.0.virtualenv  validators-0.20.0.dist-info
charset_normalizer-2.1.0.dist-info  decorator-5.1.1.dist-info     idna                       past                          pip-20.0.2.virtualenv           python_magic-0.4.27.dist-info    simplejson                    _virtualenv.pth
click                               decorator.py                  idna-3.3.dist-info         pathlib-1.0.1.dist-info       pkg_resources                   ratelim                          simplejson-3.17.6.dist-info   _virtualenv.py
click-8.1.3.dist-info               easy_install.py               libfuturize                pathlib.py                    pkg_resources-0.0.0.dist-info   ratelim-0.1.6.dist-info          six-1.16.0.dist-info          wheel
colorama                            future                        libpasteurize              pefile-2022.5.30.dist-info    pkg_resources-0.0.0.virtualenv  requests                         six.py                        wheel-0.34.2.dist-info
```

ls -la /opt/malwoverview/lib/python3.8/site-packages/home

```
total 12
drwxr-xr-x  3 root root 4096  7月  4 21:03 .
drwxr-xr-x 54 root root 4096  7月  4 21:03 ..
drwxr-xr-x  2 root root 4096  7月  4 21:03 remnux
```

**Comment by digitalsleuth** [comment]
Perfect, I think I see where the error might be. I'll look into it and get back to you both!

**Comment by digitalsleuth** [comment]
@B10haZardX and @RobotsOnDrugs , I've found a solution for the issue, and a PR has been submitted (above). Once approved, it should be available for the next release.

**Comment by lennyzeltser** [comment]
@digitalsleuth, thanks for submitting the fix. I incorporated it into the new release today. @B10haZardX and @RobotsOnDrugs, please give it a try by running `remnux upgrade`.

**Comment by RobotsOnDrugs** [comment]
`remnux install --mode=addon` completes successfully now, and a subsequent `remnux upgrade` runs fine saying that there are no upgrades. I consider this fixed. @digitalsleuth and @lennyzeltser, thank you both.
