### ISSUE TITLE
Cant install on WSL - Ubunut 20.04

### ISSUE THREAD

**Issue by itsjakey** [REMnux/remnux-cli#90]
Hello,
Getting failures trying to install using command; sudo remnux install --mode=addon
Have tried after waiting 24 hours as I noticed a post reporting issues with timeouts on polarproxy 
However, still no luck. Seems to be many packages failing.

Below is a grep of result: false from saltstack.log

Any help would be appreciated.

    __run_num__: 728
    __sls__: remnux.tools.polarproxy
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-source'
    duration: 0.01
    result: false
    start_time: '19:24:12.476792'
  archive_|-remnux-python3-packages-stpyv8-archive_|-/usr/local/src/remnux/_|-extracted:
    __id__: remnux-python3-packages-stpyv8-archive
    __run_num__: 322
    __sls__: remnux.python3-packages.stpyv8
--
    __run_num__: 729
    __sls__: remnux.tools.polarproxy
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-archive'
    duration: 0.01
    result: false
    start_time: '19:24:12.579850'
  file_|-procdot-link_|-/usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0_|-symlink:
    __id__: procdot-link
    __run_num__: 159
    __sls__: remnux.packages.procdot
--
    __run_num__: 757
    __sls__: remnux.addon
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.remnux-tools, remnux.python3-packages.remnux-python3-packages'
    duration: 0.008
    result: false
    start_time: '19:25:32.599691'
  file_|-remnux-config-android-project-creator-permissions_|-/opt/AndroidProjectCreator/library_|-directory:
    __id__: remnux-config-android-project-creator-permissions
    __run_num__: 659
    __sls__: remnux.config.android-project-creator
--
    comment: Specified sha256 checksum for /usr/local/src/remnux/files/PolarProxy_0-9-6_linux-x64.tar.gz
      (0e910d0e53b6f7d8fbd706c7ea3bedca6f4b0d1f529c4c9a6c2976b128077038) does not
      match actual checksum (7995593700748946082fcb3e56f182d86f289a28b64ba9ee7cedca63a0a5d69d)
    duration: 37654.073
    name: /usr/local/src/remnux/files/PolarProxy_0-9-6_linux-x64.tar.gz
    result: false
    start_time: '19:23:34.735575'
  file_|-remnux-polarproxy-wrapper_|-/usr/local/bin/polarproxy_|-managed:
    __run_num__: 730
    __sls__: remnux.tools.polarproxy
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy./usr/local/polarproxy/PolarProxy'
    duration: 0.01
    result: false
    start_time: '19:24:12.681882'
  file_|-remnux-python-packages-droidlysis-droidconfig-set1_|-/usr/local/lib/python3.8/dist-packages/droidconfig.py_|-replace:
    __id__: remnux-python-packages-droidlysis-droidconfig-set1
    __run_num__: 360
    __sls__: remnux.python3-packages.droidlysis
--
    changes: {}
    comment: Local file source /opt/malwoverview/lib/python3.8/site-packages/home/devuser1/.malwapi.conf
      does not exist
    duration: 3.967
    name: /home/devuser1/.malwapi.conf
    result: false
    start_time: '19:19:39.509599'
  file_|-remnux-python3-packages-malwoverview-symlink_|-/usr/local/bin/malwoverview.py_|-symlink:
    __id__: remnux-python3-packages-malwoverview-symlink
    __run_num__: 368
    __sls__: remnux.python3-packages.malwoverview
--
    __run_num__: 410
    __sls__: remnux.python3-packages
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.malwoverview.remnux-python3-packages-malwoverview-config-file'
    duration: 0.004
    result: false
    start_time: '19:21:55.832132'
  test_|-remnux-repos_|-remnux-repos_|-nop:
    __id__: remnux-repos
    __run_num__: 17
    __sls__: remnux.repos
--
    changes: {}
    comment: 'One or more requisite failed: remnux.tools.polarproxy.remnux-polarproxy-wrapper,
      remnux.tools.polarproxy.remnux-polarproxy-archive, remnux.tools.polarproxy.remnux-polarproxy-source,
      remnux.tools.polarproxy./usr/local/polarproxy/PolarProxy'
    duration: 0.011
    result: false
    start_time: '19:24:36.782917'
  user_|-remnux-user-devuser1_|-devuser1_|-present:
    __id__: remnux-user-devuser1
    __run_num__: 364
    __sls__: remnux.config.user

**Comment by digitalsleuth** [comment]
Hi @itsjakey , the errors you have aren't specific to WSL, and will be addressed during the next release. PolarProxy has a new release so the hash value is incorrect, and malwoverview had some recent updates which the new update will account for. 

All of the rest of the tools will have installed correctly, so once the next release is out you can just run the upgrade command and those will be installed.

**Comment by lennyzeltser** [comment]
@digitalsleuth, thanks for submitting the fix. I incorporated it into the new REMnux release today. @itsjakey, please give it a try by running `remnux upgrade`.
