### ISSUE TITLE
remnux upgrade fails

### ISSUE THREAD

**Issue by pzafar1974** [REMnux/remnux-cli#92]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/9131565/saltstack.log)
Hi,
I am trying to upgrade remnux by running the upgrade command. its keep failing. I would really appreciate if you can help me to find out the problem. Attaching saltstack.log file.

Thanks

**Comment by digitalsleuth** [comment]
Hi @zpravaiz , it looks like there might have been an issue installing a couple of tools, both of which come from the same repo.
Can you run the following commands and provide the output?
```bash
ls -la /etc/apt/sources.list.d/
cat /etc/apt/sources.list.d/remnux-ubuntu-stable*
```

**Comment by pzafar1974** [comment]
Thanks for the response. Please find the output below 


$ ls -la /etc/apt/sources.list.d/
total 172
drwxr-xr-x 2 root root 4096 May  9 17:10 .
drwxr-xr-x 7 root root 4096 Jul 18 15:00 ..
-rw-r--r-- 1 root root  102 Jul 18 15:00 docker.list
-rw-r--r-- 1 root root   72 Feb 14 09:45 docker.list.distUpgrade
-rw-r--r-- 1 root root  102 Mar 21 17:29 docker.list.save
-rw-r--r-- 1 root root   87 Jul 18 15:00 draios.list
-rw-r--r-- 1 root root   56 Feb 14 09:45 draios.list.distUpgrade
-rw-r--r-- 1 root root   87 Mar 21 17:29 draios.list.save
-rw-r--r-- 1 root root  158 Jul 18 15:00 gift-ubuntu-stable-bionic.list
-rw-r--r-- 1 root root  126 Feb 14 09:45 gift-ubuntu-stable-bionic.list.distUpgrade
-rw-r--r-- 1 root root  158 Mar 21 17:29 gift-ubuntu-stable-bionic.list.save
-rw-r--r-- 1 root root   73 Jul 18 15:00 inetsim.list
-rw-r--r-- 1 root root   42 Feb 14 09:45 inetsim.list.distUpgrade
-rw-r--r-- 1 root root   73 Mar 21 17:29 inetsim.list.save
-rw-r--r-- 1 root root  187 Jul 18 15:00 microsoft.list
-rw-r--r-- 1 root root   78 Feb 14 09:45 microsoft.list.distUpgrade
-rw-r--r-- 1 root root  187 Mar 21 17:29 microsoft.list.save
-rw-r--r-- 1 root root  196 Jul 18 15:00 mono-official-stable.list
-rw-r--r-- 1 root root   82 Feb 14 09:45 mono-official-stable.list.distUpgrade
-rw-r--r-- 1 root root  196 Mar 21 17:29 mono-official-stable.list.save
-rw-r--r-- 1 root root   82 Jul 18 15:00 nodesource.list
-rw-r--r-- 1 root root   52 Feb 14 09:45 nodesource.list.distUpgrade
-rw-r--r-- 1 root root   82 Mar 21 17:29 nodesource.list.save
-rw-r--r-- 1 root root  142 Jul 18 15:00 oisf-ubuntu-suricata-stable-focal.list
-rw-r--r-- 1 root root  162 Jul 18 15:00 openjdk-r-ubuntu-ppa-bionic.list
-rw-r--r-- 1 root root  130 Feb 14 09:45 openjdk-r-ubuntu-ppa-bionic.list.distUpgrade
-rw-r--r-- 1 root root  162 Mar 21 17:29 openjdk-r-ubuntu-ppa-bionic.list.save
-rw-r--r-- 1 root root  162 Jul 18 15:00 remnux-ubuntu-stable-bionic.list
-rw-r--r-- 1 root root  130 Feb 14 09:45 remnux-ubuntu-stable-bionic.list.distUpgrade
-rw-r--r-- 1 root root  162 Mar 21 17:29 remnux-ubuntu-stable-bionic.list.save
-rw-r--r-- 1 root root   84 Jul 18 15:00 saltstack.list
-rw-r--r-- 1 root root   85 Feb 14 09:45 saltstack.list.distUpgrade
-rw-r--r-- 1 root root   84 May  9 11:54 saltstack.list.save
-rw-r--r-- 1 root root  158 Jul 18 15:00 sift-ubuntu-stable-bionic.list
-rw-r--r-- 1 root root  126 Feb 14 09:45 sift-ubuntu-stable-bionic.list.distUpgrade
-rw-r--r-- 1 root root  158 Mar 21 17:29 sift-ubuntu-stable-bionic.list.save
-rw-r--r-- 1 root root   50 Jul 18 15:00 sublime-text.list
-rw-r--r-- 1 root root  275 Jul 18 15:00 vscode.list
-rw-r--r-- 1 root root  203 Feb 14 09:45 vscode.list.distUpgrade
-rw-r--r-- 1 root root  275 Mar 21 17:29 vscode.list.save
-rw-r--r-- 1 root root  176 Jul 18 15:00 wireshark-dev-ubuntu-stable-bionic.list
-rw-r--r-- 1 root root  144 Feb 14 09:45 wireshark-dev-ubuntu-stable-bionic.list.distUpgrade
-rw-r--r-- 1 root root  176 Mar 21 17:29 wireshark-dev-ubuntu-stable-bionic.list.save


$ cat /etc/apt/sources.list.d/remnux-ubuntu-stable*
# deb http://ppa.launchpad.net/remnux/stable/ubuntu focal main # disabled on upgrade to focal
# deb-src http://ppa.launchpad.net/remnux/stable/ubuntu bionic main
deb http://ppa.launchpad.net/remnux/stable/ubuntu bionic main
# deb-src http://ppa.launchpad.net/remnux/stable/ubuntu bionic main
# deb http://ppa.launchpad.net/remnux/stable/ubuntu focal main # disabled on upgrade to focal
# deb-src http://ppa.launchpad.net/remnux/stable/ubuntu bionic main

**Comment by digitalsleuth** [comment]
Can you confirm if you are on bionic or focal?
```bash
cat /etc/os-release
or
lsb_release -a
```

**Comment by pzafar1974** [comment]
Sorry for late reply due to time difference. Its Focal 


```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal


$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

```

**Comment by pzafar1974** [comment]
Hi @digitalsleuth 

waiting for your response.I would appreciate your help 

Thanks

**Comment by pzafar1974** [comment]
Update:

I removed all bionic repo from the source.list.d and it fix the problem.

**Comment by digitalsleuth** [comment]
Hi @zpravaiz , sorry for the delay in getting back to you, but I'm glad you got it fixed! That's exactly what I was going to suggest :)

Cheers!
