### ISSUE TITLE
Remnux fresh install failed on focal 

### ISSUE THREAD

**Issue by TheWanderer1983** [REMnux/remnux-cli#93]
renmux install fails at the same point after a couple of tries, specifically after SSH. Here are the result: failed parts of the log:
**Update:** I deleted everything and tried again. Here are the latest fails.

    start_time: '18:33:24.410852'
  file_|-remnux-addon-version-file_|-/etc/remnux-version_|-managed:
    __run_num__: 757
    __sls__: remnux.addon
    changes: {}
    comment: 'One or more requisite failed: remnux.packages.remnux-packages'
    duration: 0.012
    result: false

    start_time: '18:33:22.529314'
  pkg_|-remnux-packages-rar_|-rar_|-installed:
    __id__: remnux-packages-rar
    __run_num__: 221
    __sls__: remnux.packages.rar
    changes: {}
    comment: "Problem encountered installing package(s). Additional info follows
:\n\nerrors:\n
      \   - Running scope as unit: run-rec59e57475fd477d9e5274bd3a909c54.scope\n
      E:
      Package 'rar' has no installation candidate"
    duration: 1304.853
    name: rar
    result: false

    start_time: '18:41:37.259814'
  test_|-remnux-dedicated_|-remnux-dedicated_|-nop:
    __run_num__: 814
    __sls__: remnux.dedicated
    changes: {}
    comment: 'One or more requisite failed: remnux.addon.remnux-addon-version-fi
le'
    duration: 0.009
    result: false

    start_time: '18:42:21.775217'
  test_|-remnux-packages_|-remnux-packages_|-nop:
    __run_num__: 225
    __sls__: remnux.packages
    changes: {}
    comment: 'One or more requisite failed: remnux.packages.rar.remnux-packages-
rar'
    duration: 0.013
    result: false

**Comment by TheWanderer1983** [comment]
Fixed. RAR wouldn't install as I didn't have multiverse repo enabled.

**Comment by digitalsleuth** [comment]
Hi @TheWanderer1983 , from looking at the logs, it appears that you ran out of space in the VM and some of the tools didn't install:
```ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device"```

You may have to increase your disk space or clear some up room and run the installer again.
