### ISSUE TITLE
Install fail in Kali. And missing var/cache/remnux/cli

### ISSUE THREAD

**Issue by ghost** [REMnux/remnux-cli#96]
Virtualization: oracle
Operating System: Kali GNU/Linux Rolling          
          Kernel: Linux 5.18.0-kali5-amd64
    Architecture: x86-64
 Hardware Vendor: innotek GmbH
  Hardware Model: VirtualBox
Release:	2022.3

![Screenshot 2022-08-30 11:01:07](https://user-images.githubusercontent.com/107531767/187340647-28c8cb24-d86f-470f-a5fa-569b13edbf45.png)

![Screenshot 2022-08-30 11:10:00](https://user-images.githubusercontent.com/107531767/187340583-f96b8e6f-9cd2-4ad3-b358-ee9fca97fad2.png)

Also, I cannot even find saltstack.log file under /var/cache/remnux/cli because remnux directory did not exist.

**Comment by digitalsleuth** [comment]
Hi @PlutoDoma00, the reason for this error (Invalid OS) is that REMnux is only supported on Ubuntu Focal (20.04) at this time.

**Comment by jediD83** [comment]
Same result with a new Ubuntu OS too.

Virtualization: oracle
Operating System: Ubuntu 22.04.1 LTS              
          Kernel: Linux 5.15.0-46-generic
    Architecture: x86-64
 Hardware Vendor: innotek GmbH
  Hardware Model: VirtualBox

**Comment by ghost** [comment]
@digitalsleuth Same result with a new Ubuntu OS. 

Virtualization: oracle
Operating System: Ubuntu 22.04.1 LTS              
          Kernel: Linux 5.15.0-46-generic
    Architecture: x86-64
 Hardware Vendor: innotek GmbH
  Hardware Model: VirtualBox

**Comment by digitalsleuth** [comment]
Hi @PlutoDoma00, currently Ubuntu Jammy (22.04) is also unsupported, as some of the repos which house some of the software do not have a Jammy repo yet. This is definitely something we're working towards, however our latest supported version of Ubuntu is 20.04 (Focal).
