### ISSUE TITLE
Something changed by running remnux upgrade is breaking Ubuntu update settings (software-properties-gtk)

### ISSUE THREAD

**Issue by DanFelton** [REMnux/remnux-cli#98]
I have narrowed this issue down to only arising after ran `remnux upgrade`. I haven't yet been able to pinpoint exactly why, but I have snapshots of my vm before and after (fully updated 20.04) and this only happens after.

Trying to launch 'Software & Updates' or navigating to Settings->About->Software Updates, both just silently fail, with no error, but with the update settings not opening.

If I try to launch software-properties-gtk via the command line I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'com.ubuntu.SoftwareProperties': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/software-properties-gtk", line 100, in <module>
    app = SoftwarePropertiesGtk(datadir=options.data_dir, options=options, file=file)
  File "/usr/lib/python3/dist-packages/softwareproperties/gtk/SoftwarePropertiesGtk.py", line 208, in __init__
    proxy = bus.get_object("com.ubuntu.SoftwareProperties", "/")
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1

```

I have tried reinstalling dbus, python3-dbus and anything else involved in the update process but I cannot seem to get this fixed once it happens, and had to roll back my vm to a snapshot from before I ran remnux upgrade.

**Comment by digitalsleuth** [comment]
Hi @DanFelton , any chance you can attach your saltstack.log file so we can take a look? Additionally, since it seems like a potential dbus problem, you could also try re-installing dbus-x11.

Did you run the `remnux upgrade` command with `sudo` as well?

**Comment by DanFelton** [comment]
- I ran without sudo, but was prompted for my password after running `remnux upgrade` (side note, it's only after rebooting that I get this issue)
- I tried reinstalling dbus-x11, didn't seem to change anything.
- saltstack.log is here: https://fastupload.io/en/DdCufTYF4NftAtO/file

**Comment by DanFelton** [comment]
I also went back and re-did the upgrade using sudo from the start, but the result was the same

**Comment by digitalsleuth** [comment]
Hi @DanFelton , I've looked at your saltstack log and there are no errors, or causes of the error you've received above. 
I have a few questions I'm hoping you can answer so we can narrow down the issue:
- Are you using a standard Ubuntu 20.04 install, or have you customized it with a different desktop environment?
- Was this OS an upgrade from Ubuntu 18.04?
- Can you check (recursively) the permissions for all items in your home directory, especially throughout the .config directory?
- Do you have an updated / customized version of Python installed (>= 3.9)?

The last thing I can recommend is to try to re-install both software-properties-common and software-properties-gtk, since both of these are required for the software-properties to properly operate.

**Comment by DanFelton** [comment]
- It is 20.04, I have sift installed as well, but didn't change anything on that front for a while.
- This was a vanilla 20.04 install with sift+remnux installed, has worked for over a year.
- There's a heck of a lot of stuff in nested directories in my home directory, I wouldn't know where to start, permissions in the root of ~/.config look fine, but I don't know what I'd be looking for.
- everything in the path rgarding python ultimately points to 3.8, I think that's just what's the latest in ubuntu repos for 20.04. I would never make changes to the OS's python install.
- I just tested reinstalling software-properties-common and software-properties-gtk, but that didn't change anything.

**Comment by digitalsleuth** [comment]
For permissions, you'd want to make sure that you are the owner of all files in your home directory. You can ensure this by running:
`sudo chown -R <user>:<group> .config/`
Where `<user>` is your username and `<group>` is your home group (this is typically a group named for your username).

Can you check to see if the dbus service is started and in the correct state? Also, it might help if you check for errors using:
`sudo journalctl -xe`

**Comment by DanFelton** [comment]
Apologies for not responding, I was away from a while and didn't have access to my Computer.

- The VM is Ubuntu 20.04, with both SIFT and Remnux installed together (as per https://www.sans.org/blog/how-to-install-sift-workstation-and-remnux-on-the-same-forensics-system/)

- The OS wasn't upgraded. I created a fresh Ubuntu 20.04 vm, then installed SIFT and Remnux. I didn't make any custom modifications.

- Re the permissions in the home directory, I don't really know what I'm looking for. There's a lot of nested directories.

- I haven't manually changed anything about the python install. It seems that Ubuntu 20.04 has both 2.7 and 3.8 installed, presumably for OS/ditros features that require both of those. 

Re-installing software-properties-common and software-properties-gtk didn't seem to change anything,

**Comment by digitalsleuth** [comment]
Hi @DanFelton , could you try the following:
- `sudo service --status-all | grep dbus`
- `dbus-launch`
- `dbus-monitor` - if this works without error you can `CTRL-C` after a couple of seconds
- `sudo systemctl status dbus.service`

It would be great if you could provide the output here, and sanitize if necessary.  
Cheers!

**Comment by digitalsleuth** [comment]
I believe I've found the source of the issue and a resolution, but I'm working on refining both right now.

**Comment by digitalsleuth** [comment]
So the issue centers around Thug (and its requirements) in REMnux, and Geoip2 in SIFT. Mainly, how it affects the requests and other python3 modules it installs. Try running this and let me know how it goes:  

`sudo apt reinstall python3-urllib3 python3-chardet python3-requests-unixsocket python3-requests`  

Then reboot.

**Comment by digitalsleuth** [comment]
If, for some reason, this doesn't work, then do the following:
Edit the file /lib/python3/softwareproperties/LivepatchService.py and change:

![before](https://user-images.githubusercontent.com/62841822/197832572-c466048a-d31a-4b99-ab7d-c7dda2067e23.png)

to this:

![after](https://user-images.githubusercontent.com/62841822/197832755-3d1f1d04-3b2a-4a4f-9c35-8ea195c388fa.png)

Make note, you're moving the `import requests_unixsocket` line out of the try loop to just before it.
Then run `software-properties-gtk` again and it should work.

I haven't found the exact cause yet, but that should fix it permanently.

**Comment by digitalsleuth** [comment]
Hey @DanFelton , just checking in to see if you've tried this and had any luck?

**Comment by DanFelton** [comment]
I've been busy with work, will test tonight.
